# Generated by Django 6.0.5 on 2026-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=30)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Audit Log',
                'verbose_name_plural': 'OTP Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
