# Generated by Django 6.0.5 on 2026-07-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_otp_user_otp_created_at_user_phone_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, default='IN', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('trust_score', models.IntegerField(default=0)),
                ('reg_form_data', models.JSONField(blank=True, default=dict)),
                ('doc_form_data', models.JSONField(blank=True, default=dict)),
                ('academy_state_data', models.JSONField(blank=True, default=dict)),
                ('interview_state_data', models.JSONField(blank=True, default=dict)),
                ('admin_clearance_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Dossier',
                'verbose_name_plural': 'Registration Dossiers',
                'ordering': ['-created_at'],
            },
        ),
    ]
