# Generated by Django 6.0.5 on 2026-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_savedaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedaddress',
            options={'ordering': ['-is_default', '-last_used_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
