# Generated by Django 6.0.8 on 2026-08-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_otprequest_user_last_known_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='flat_house_no',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='formatted_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='receiver_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
