# Generated by Django 6.0.8 on 2026-08-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_workforce_from_accounts'),
        ('accounts', '0015_otprequest_identifier_channel'),
    ]

    operations = [
    ]
