# Generated by Django 6.0.8 on 2026-08-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20260818_1500'),
        ('companies', '0011_alter_company_data_region_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'date_joined'], name='idx_user_role_date_joined'),
        ),
    ]
