# Generated by Django 6.0.8 on 2026-08-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20260818_1512'),
        ('accounts', '0017_user_idx_user_role_date_joined'),
    ]

    operations = [
    ]
