# Generated by Django 6.0.8 on 2026-08-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_options'),
        ('companies', '0011_alter_company_data_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Permanent unique Customer ID (e.g. CUS0001)', max_length=30, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['customer_id'], name='idx_user_customer_id'),
        ),
    ]
