# Generated by Django on 2026-08-21

from django.db import migrations


def populate_customer_ids(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    users = list(User.objects.all().order_by("id"))
    existing_cids = {u.customer_id for u in users if u.customer_id}
    num = 1
    to_update = []
    for user in users:
        if not user.customer_id:
            cid = f"CUS{str(num).zfill(4)}"
            while cid in existing_cids:
                num += 1
                cid = f"CUS{str(num).zfill(4)}"
            user.customer_id = cid
            existing_cids.add(cid)
            to_update.append(user)
            num += 1
    if to_update:
        User.objects.bulk_update(to_update, ["customer_id"], batch_size=500)


def reverse_customer_ids(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_user_customer_id_user_idx_user_customer_id"),
    ]

    operations = [
        migrations.RunPython(populate_customer_ids, reverse_customer_ids),
    ]
