# Generated by Django 6.0.8 on 2026-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_populate_customer_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('support', 'Support'), ('catalog', 'Catalog Manager'), ('finance', 'Finance'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
