# Generated by Django 6.0.8 on 2026-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='geocoding_status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='location_source',
            field=models.CharField(blank=True, default='geocoding', max_length=50),
        ),
    ]
