# Generated by Django 6.0.8 on 2026-08-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_savedaddress_country_savedaddress_geocoded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='location_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
