# Generated by Django 6.0.8 on 2026-09-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_referral_code_and_referral'),
        ('accounts', '0024_savedaddress_location_confirmed_at'),
    ]

    operations = [
    ]
