# Generated by Django 6.0.8 on 2026-08-18 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('service_requests', '0042_servicerequest_cancellation_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=15)),
                ('email_normalized', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('first_booking_at', models.DateTimeField(blank=True, null=True)),
                ('merge_note', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_identities', to='companies.company')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_identities', to='customer_analytics.customeridentity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Identities',
            },
        ),
        migrations.CreateModel(
            name='CustomerLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('otp_phone', 'Phone OTP'), ('otp_email', 'Email OTP'), ('google', 'Google Sign-In'), ('generic', 'Generic Login')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=15)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_login_events', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_persona', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('admin', 'Admin'), ('system', 'System')], max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('reason_note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_status_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_events', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_events', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['company', 'to_status', 'occurred_at'], name='customer_an_company_ed84e1_idx'), models.Index(fields=['customer', 'occurred_at'], name='customer_an_custome_ffc917_idx'), models.Index(fields=['company', 'occurred_at'], name='customer_an_company_312508_idx')],
            },
        ),
    ]
