# Generated by Django 6.0.8 on 2026-08-18 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_analytics', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatusevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerloginevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
