# Generated by Django 6.0.8 on 2026-08-18 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_customer_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    CustomerUser = apps.get_model('customer_analytics', 'CustomerUser')

    for u in User.objects.filter(role='customer'):
        full_name = f"{u.first_name} {u.last_name}".strip() or u.username
        CustomerUser.objects.get_or_create(
            user=u,
            defaults={
                "name": full_name,
                "phone": getattr(u, "phone", "") or "",
                "email": getattr(u, "email", "") or "",
                "company": getattr(u, "company", None),
                "last_login": u.last_login
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('customer_analytics', '0003_alter_bookingstatusevent_occurred_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_users', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_users',
            },
        ),
        migrations.RunPython(populate_customer_users, reverse_code=migrations.RunPython.noop),
    ]
