# Generated by Django 6.0.8 on 2026-08-24 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_analytics', '0004_customeruser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeridentity',
            name='merge_note',
        ),
        migrations.AddField(
            model_name='customeridentity',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customeridentity',
            name='customer_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='customeridentity',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customeridentity',
            name='risk_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('flagged', 'Flagged'), ('restricted', 'Restricted'), ('blacklisted', 'Blacklisted')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='customeridentity',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PlatformAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'timestamp'], name='customer_an_module_465f58_idx'), models.Index(fields=['action', 'timestamp'], name='customer_an_action_6bcaf2_idx'), models.Index(fields=['actor', 'timestamp'], name='customer_an_actor_i_d68070_idx')],
            },
        ),
    ]
