# Generated by Django 6.0.8 on 2026-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_analytics', '0005_remove_customeridentity_merge_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeridentity',
            name='merge_note',
            field=models.TextField(blank=True),
        ),
    ]
