"""service_requests/urls.py"""
from django.urls import path

from .views import (
    # Public & Customer
    BookingCreateView,
    BookingVerifyStartOTPView,
    CustomerMyBookingsView,
    CustomerBookingRetryPaymentView,
    CustomerBookingLiveLocationView,
    CustomerPublicTrackingView,
    CustomerBookingCancelView,
    FeedbackTokenView,
    PublicFeedbackListView,
    CustomerReverseGeocodeView,
    CatalogCategoryListView,
    CatalogServiceListView,
    CatalogSubServiceListView,
    CustomerQuoteDetailView,

    # Admin — Service Requests
    AdminSRListView,
    AdminSRDetailView,
    AdminSRReviewView,
    AdminSRPriorityView,
    AdminSRAssignView,
    AdminSRDispatchView,
    AdminSRUpdateTechnicianLocationView,
    AdminSRRejectView,
    AdminSRVerifyView,
    AdminSRReworkView,
    AdminSRCloseView,
    AdminSRResendFeedbackView,

    # Admin — Feedback
    AdminFeedbackListView,
    AdminFeedbackMetricsView,

    # Work Extensions
    AdminWorkExtensionListView,
    AdminWorkExtensionApproveView,
    AdminWorkExtensionApprovePurchaseView,
    AdminWorkExtensionAssignView,
    CustomerWorkExtensionPortalView,
    CustomerWorkExtensionDecideView,
    SupportWorkExtensionRecordDecisionView,
    ServiceRequestSupplementalInvoiceView,

    # Reschedule
    CustomerActiveBookingsListView,
    CustomerBookingAvailableSlotsView,
    CustomerRescheduleRequestListView,
    CustomerRescheduleRequestCreateView,
    CustomerRescheduleRequestCancelView,
    CustomerRescheduleRespondToSuggestionView,
    CustomerRescheduleView,
    AdminRescheduleRequestListView,
    AdminRescheduleRequestReviewView,
    AdminRescheduleApproveView,
    AdminRescheduleRejectView,
    AdminRescheduleSuggestSlotView,
    AdminRescheduleListView,
    AdminRescheduleActionView,

    # Refund
    CustomerEligibleBookingsListView,
    CustomerBookingRefundSummaryView,
    CustomerRefundRequestCreateView,
    CustomerRefundRequestListView,
    CustomerRefundRequestDetailView,
    CustomerRefundView,
    AdminRefundRequestListView,
    AdminRefundRequestDetailView,
    AdminRefundApproveView,
    AdminRefundRejectView,
    AdminRefundRequestInfoView,
    AdminRefundSendToFinanceView,
    AdminRefundInternalNoteView,
    AdminRefundListView,
    AdminRefundActionView,
    CustomerWalletView, AdminWalletCreditView, TechnicianProfileView,
    CustomerInsuranceClaimListCreateView, AdminInsuranceClaimListView, AdminInsuranceClaimResolveView,

    # Complaints
    CustomerComplaintListView,
    CustomerComplaintCreateView,
    CustomerComplaintDetailView,
    CustomerComplaintMessageCreateView,
    AdminComplaintListView,
    AdminComplaintDetailView,
    AdminComplaintAssignView,
    AdminComplaintStatusUpdateView,
    AdminComplaintResolveView,
    AdminComplaintMessageCreateView,

    # Marketing & Coupons
    CouponListCreateView,
    CouponDetailView,
    CustomerCouponListView,
    CustomerCouponValidateView,
    AdminCouponAnalyticsView,
)
from .payment_views import (
    PaymentInitiateView,
    PaymentVerifyView,
    AdminPaymentUpdateView,
    InvoiceDownloadView,
)

urlpatterns = [
    # ── Public & Customer ─────────────────────────────────────────────────────
    path("catalog/categories/",              CatalogCategoryListView.as_view(), name="catalog-categories"),
    path("catalog/services/",                CatalogServiceListView.as_view(),  name="catalog-services"),
    path("catalog/sub-services/",            CatalogSubServiceListView.as_view(), name="catalog-sub-services"),
    path("booking/",                         BookingCreateView.as_view(),    name="sr-booking"),
    path("booking/my-bookings/",             CustomerMyBookingsView.as_view(), name="sr-my-bookings"),
    path("booking/<int:pk>/retry-payment/",  CustomerBookingRetryPaymentView.as_view(), name="sr-retry-payment"),
    path("booking/<int:pk>/invoice/",        InvoiceDownloadView.as_view(),  name="sr-invoice"),
    path("booking/<int:pk>/live-location/",  CustomerBookingLiveLocationView.as_view(), name="sr-booking-live-location"),
    path("booking/<str:identifier>/live-location/", CustomerBookingLiveLocationView.as_view(), name="sr-booking-live-location-identifier"),
    path("workforce/jobs/<int:pk>/live-tracking/", CustomerBookingLiveLocationView.as_view(), name="workforce-job-live-tracking"),
    path("workforce/jobs/<str:identifier>/live-tracking/", CustomerBookingLiveLocationView.as_view(), name="workforce-job-live-tracking-str"),
    path("tracking/<str:tracking_token>/",   CustomerPublicTrackingView.as_view(), name="sr-public-tracking-token"),
    path("booking/quote/<str:token>/",       CustomerQuoteDetailView.as_view(), name="sr-customer-quote-detail"),
    path("booking/<int:pk>/verify-start-otp/", BookingVerifyStartOTPView.as_view(), name="sr-booking-verify-start-otp"),
    path("booking/<str:identifier>/verify-start-otp/", BookingVerifyStartOTPView.as_view(), name="sr-booking-verify-start-otp-identifier"),
    path("booking/<int:pk>/cancel/",         CustomerBookingCancelView.as_view(),       name="sr-booking-cancel"),
    path("booking/<str:identifier>/cancel/", CustomerBookingCancelView.as_view(),       name="sr-booking-cancel-identifier"),
    path("customer/bookings/<int:pk>/cancel/", CustomerBookingCancelView.as_view(),     name="customer-booking-cancel"),
    path("customer/bookings/<str:identifier>/cancel/", CustomerBookingCancelView.as_view(), name="customer-booking-cancel-identifier"),
    path("feedback/<uuid:token>/",           FeedbackTokenView.as_view(),    name="sr-feedback-token"),
    path("public/feedback/",                 PublicFeedbackListView.as_view(), name="sr-public-feedback"),

    # ── Customer Address Geocoding ─────────────────────────────────────────────
    path("customer/addresses/reverse-geocode/", CustomerReverseGeocodeView.as_view(), name="customer-reverse-geocode"),

    # ── Payment ───────────────────────────────────────────────────────────────
    path("payment/initiate/",                PaymentInitiateView.as_view(),  name="payment-initiate"),
    path("payment/verify/",                  PaymentVerifyView.as_view(),    name="payment-verify"),

    # ── Admin — Service Requests ──────────────────────────────────────────────
    path("admin/service-requests/",          AdminSRListView.as_view(),      name="sr-admin-list"),
    path("admin/service-requests/<int:pk>/", AdminSRDetailView.as_view(),    name="sr-admin-detail"),
    path("admin/service-requests/<int:pk>/review/",       AdminSRReviewView.as_view(),   name="sr-admin-review"),
    path("admin/service-requests/<int:pk>/priority/",     AdminSRPriorityView.as_view(), name="sr-admin-priority"),
    path("admin/service-requests/<int:pk>/assign/",       AdminSRAssignView.as_view(),   name="sr-admin-assign"),
    path("admin/service-requests/<int:pk>/dispatch/",     AdminSRDispatchView.as_view(), name="sr-admin-dispatch"),
    path("admin/service-requests/<int:pk>/technician-location/", AdminSRUpdateTechnicianLocationView.as_view(), name="sr-admin-technician-location"),
    path("admin/service-requests/<str:identifier>/technician-location/", AdminSRUpdateTechnicianLocationView.as_view(), name="sr-admin-technician-location-identifier"),
    path("booking/<int:pk>/update-location/", AdminSRUpdateTechnicianLocationView.as_view(), name="sr-booking-update-location"),
    path("booking/<str:identifier>/update-location/", AdminSRUpdateTechnicianLocationView.as_view(), name="sr-booking-update-location-identifier"),
    path("admin/service-requests/<int:pk>/reject/",       AdminSRRejectView.as_view(),   name="sr-admin-reject"),
    path("admin/service-requests/<int:pk>/verify/",       AdminSRVerifyView.as_view(),   name="sr-admin-verify"),
    path("admin/service-requests/<int:pk>/request-rework/", AdminSRReworkView.as_view(), name="sr-admin-rework"),
    path("admin/service-requests/<int:pk>/close/",        AdminSRCloseView.as_view(),    name="sr-admin-close"),
    path("admin/service-requests/<int:pk>/resend-feedback/", AdminSRResendFeedbackView.as_view(), name="sr-admin-resend-feedback"),
    path("admin/service-requests/<int:pk>/payment/",      AdminPaymentUpdateView.as_view(), name="sr-admin-payment"),

    # ── Admin — Feedback ──────────────────────────────────────────────────────
    path("admin/feedback/",                  AdminFeedbackListView.as_view(),   name="sr-admin-feedback-list"),
    path("admin/feedback/metrics/",          AdminFeedbackMetricsView.as_view(),name="sr-admin-feedback-metrics"),

    # ── Work Extensions ───────────────────────────────────────────────────────
    path("admin/work-extensions/",                         AdminWorkExtensionListView.as_view(), name="sr-admin-work-extensions"),
    path("admin/work-extensions/<int:ext_id>/approve/",    AdminWorkExtensionApproveView.as_view(), name="sr-admin-work-extension-approve"),
    path("admin/work-extensions/items/<int:item_id>/approve-purchase/", AdminWorkExtensionApprovePurchaseView.as_view(), name="sr-admin-work-extension-approve-purchase"),
    path("admin/work-extensions/<int:ext_id>/assign/",     AdminWorkExtensionAssignView.as_view(), name="sr-admin-work-extension-assign"),
    path("customer/work-extensions/<str:token>/",         CustomerWorkExtensionPortalView.as_view(), name="sr-customer-work-extension-portal"),
    path("customer/work-extensions/<str:token>/decide/",  CustomerWorkExtensionDecideView.as_view(), name="sr-customer-work-extension-decide"),
    path("support/work-extensions/<int:ext_id>/record-decision/", SupportWorkExtensionRecordDecisionView.as_view(), name="sr-support-work-extension-record-decision"),
    path("service-requests/<int:sr_id>/supplemental-invoice/", ServiceRequestSupplementalInvoiceView.as_view(), name="sr-supplemental-invoice"),

    # ── Complaints ────────────────────────────────────────────────────────────
    path('booking/complaints/',                          CustomerComplaintListView.as_view(),          name='customer-complaint-list'),
    path('booking/complaints/create/',                   CustomerComplaintCreateView.as_view(),        name='customer-complaint-create'),
    path('booking/complaints/<int:pk>/',                 CustomerComplaintDetailView.as_view(),        name='customer-complaint-detail'),
    path('booking/complaints/<int:pk>/response/',        CustomerComplaintMessageCreateView.as_view(), name='customer-complaint-response'),
    path('admin/complaints/',                            AdminComplaintListView.as_view(),             name='admin-complaint-list'),
    path('admin/complaints/<int:pk>/',                   AdminComplaintDetailView.as_view(),           name='admin-complaint-detail'),
    path('admin/complaints/<int:pk>/assign/',            AdminComplaintAssignView.as_view(),           name='admin-complaint-assign'),
    path('admin/complaints/<int:pk>/status/',            AdminComplaintStatusUpdateView.as_view(),     name='admin-complaint-status'),
    path('admin/complaints/<int:pk>/resolve/',           AdminComplaintResolveView.as_view(),          name='admin-complaint-resolve'),
    path('admin/complaints/<int:pk>/response/',          AdminComplaintMessageCreateView.as_view(),    name='admin-complaint-response'),

    # ── Reschedule ────────────────────────────────────────────────────────────
    path('customer/active-bookings/',                    CustomerActiveBookingsListView.as_view(),      name='customer-active-bookings'),
    path('customer/bookings/<int:booking_id>/slots/',    CustomerBookingAvailableSlotsView.as_view(),   name='customer-booking-slots'),
    path('customer/reschedules/',                        CustomerRescheduleRequestListView.as_view(),   name='customer-reschedule-list'),
    path('customer/reschedules/create/',                 CustomerRescheduleRequestCreateView.as_view(), name='customer-reschedule-create'),
    path('customer/reschedules/<int:pk>/cancel/',        CustomerRescheduleRequestCancelView.as_view(), name='customer-reschedule-cancel'),
    path('booking/reschedule/<int:pk>/cancel/',          CustomerRescheduleRequestCancelView.as_view(), name='booking-reschedule-cancel-alias'),
    path('service-requests/customer/reschedules/create/', CustomerRescheduleRequestCreateView.as_view(), name='sr-customer-reschedule-create'),
    path('service-requests/customer/reschedules/',      CustomerRescheduleRequestListView.as_view(),   name='sr-customer-reschedule-list'),
    path('admin/reschedules/list/',                      AdminRescheduleRequestListView.as_view(),      name='admin-reschedule-request-list'),
    path('service-requests/admin/reschedules/',          AdminRescheduleRequestListView.as_view(),      name='sr-admin-reschedule-request-list'),
    path('admin/reschedules/<int:pk>/review/',           AdminRescheduleRequestReviewView.as_view(),    name='admin-reschedule-request-review'),
    path('service-requests/admin/reschedules/<int:pk>/review/', AdminRescheduleRequestReviewView.as_view(), name='sr-admin-reschedule-request-review'),
    path('admin/reschedules/<int:pk>/approve/',          AdminRescheduleApproveView.as_view(),          name='admin-reschedule-approve'),
    path('admin/reschedules/<int:pk>/reject/',           AdminRescheduleRejectView.as_view(),           name='admin-reschedule-reject'),
    path('admin/reschedules/<int:pk>/suggest-slot/',     AdminRescheduleSuggestSlotView.as_view(),      name='admin-reschedule-suggest-slot'),
    path('customer/reschedules/<int:pk>/respond-suggestion/', CustomerRescheduleRespondToSuggestionView.as_view(), name='customer-reschedule-respond-suggestion'),
    path('booking/reschedule/',                          CustomerRescheduleView.as_view(),             name='customer-reschedule'),
    path('admin/reschedules/',                           AdminRescheduleListView.as_view(),            name='admin-reschedule-list'),
    path('admin/reschedules/<int:pk>/<str:action>/',     AdminRescheduleActionView.as_view(),          name='admin-reschedule-action'),

    # ── Refund ────────────────────────────────────────────────────────────────
    path('booking/refunds/',                             CustomerRefundView.as_view(),                 name='customer-refund'),
    path('admin/refunds/',                               AdminRefundListView.as_view(),                name='admin-refund-list'),
    path('admin/refunds/<int:pk>/<str:action>/',         AdminRefundActionView.as_view(),              name='admin-refund-action'),
    path('wallet/',                                        CustomerWalletView.as_view(),                 name='customer-wallet'),
    path('technicians/<str:technician_id>/profile/',       TechnicianProfileView.as_view(),              name='technician-profile'),
    path('insurance-claims/',                              CustomerInsuranceClaimListCreateView.as_view(), name='insurance-claims'),
    path('admin/insurance-claims/',                         AdminInsuranceClaimListView.as_view(),        name='admin-insurance-claims'),
    path('admin/insurance-claims/<int:pk>/resolve/',        AdminInsuranceClaimResolveView.as_view(),     name='admin-insurance-claim-resolve'),
    path('admin/customers/<int:user_id>/wallet/credit/',   AdminWalletCreditView.as_view(),              name='admin-wallet-credit'),
    path('customer/refunds/eligible-bookings/',          CustomerEligibleBookingsListView.as_view(),   name='customer-refund-eligible-bookings'),
    path('customer/refunds/bookings/<int:booking_id>/summary/', CustomerBookingRefundSummaryView.as_view(), name='customer-refund-summary'),
    path('customer/refunds/create/',                     CustomerRefundRequestCreateView.as_view(),    name='customer-refund-create'),
    path('customer/refunds/',                            CustomerRefundRequestListView.as_view(),      name='customer-refund-list'),
    path('customer/refunds/<int:pk>/',                   CustomerRefundRequestDetailView.as_view(),    name='customer-refund-detail'),
    path('admin/refunds/list/',                          AdminRefundRequestListView.as_view(),         name='admin-refund-request-list'),
    path('admin/refunds/<int:pk>/detail/',               AdminRefundRequestDetailView.as_view(),       name='admin-refund-request-detail'),
    path('admin/refunds/<int:pk>/approve/',              AdminRefundApproveView.as_view(),             name='admin-refund-approve'),
    path('admin/refunds/<int:pk>/reject/',               AdminRefundRejectView.as_view(),              name='admin-refund-reject'),
    path('admin/refunds/<int:pk>/request-info/',         AdminRefundRequestInfoView.as_view(),        name='admin-refund-request-info'),
    path('admin/refunds/<int:pk>/send-to-finance/',      AdminRefundSendToFinanceView.as_view(),       name='admin-refund-send-to-finance'),
    path('admin/refunds/<int:pk>/internal-note/',        AdminRefundInternalNoteView.as_view(),        name='admin-refund-internal-note'),

    # ── Marketing & Coupons ───────────────────────────────────────────────────
    path('coupons/',                                     CouponListCreateView.as_view(),               name='coupon-list-create'),
    path('coupons/<int:pk>/',                            CouponDetailView.as_view(),                   name='coupon-detail'),
    path('coupons/apply/',                               CustomerCouponValidateView.as_view(),        name='coupon-apply'),
    path('admin/coupons/',                               CouponListCreateView.as_view(),               name='admin-coupon-list-create'),
    path('admin/coupons/analytics/',                     AdminCouponAnalyticsView.as_view(),           name='admin-coupon-analytics'),
    path('admin/coupons/<int:pk>/',                      CouponDetailView.as_view(),                   name='admin-coupon-detail'),
    path('admin/coupons/<int:pk>/status/',               CouponDetailView.as_view(),                   name='admin-coupon-status'),
    path('customer/coupons/',                            CustomerCouponListView.as_view(),             name='customer-coupon-list'),
    path('customer/coupons/validate/',                   CustomerCouponValidateView.as_view(),         name='customer-coupon-validate'),
]
