"""service_requests/urls.py"""
from django.urls import path

from .views import (
    # Public & Customer
    BookingCreateView,

    BookingVerifyStartOTPView,
    CustomerMyBookingsView,
    CustomerBookingRetryPaymentView,
    CustomerBookingLiveLocationView,
    CustomerPublicTrackingView,
    CustomerBookingCancelView,
    CustomerBookingTripStopsView,
    CustomerBookingMessagesView,
    CustomerBookingSeriesListCreateView,
    CustomerBookingSeriesStatusView,
    FeedbackTokenView,
    PublicFeedbackListView,
    CustomerReverseGeocodeView,
    CatalogCategoryListView,
    CatalogServiceListView,
    CatalogSubServiceListView,
    VegetableRecipeListView,
    VegetableRecipeDetailView,
    VegetableRecommendationListView,
    CustomerQuoteDetailView,
    CustomerQuoteDecideView,
    CustomerQuotePDFView,
    WorkforceQuoteDecisionBridgeView,
    AdminPaintingRateCardListView,
    AdminPaintingRateCardDetailView,
    AdminACRateCategoryListCreateView,
    AdminACRateCategoryDetailView,
    AdminACRateItemListCreateView,
    AdminACRateItemDetailView,
    AdminACInspectionConfigView,
    AdminACInspectionResetDefaultsView,
    ACRateCardPublicView,
    TechnicianACQuotationCreateView,
    AdminQuoteCreateView,
    AdminQuoteActionView,

    # Admin — Service Requests
    AdminSRListView,
    AdminSRDetailView,
    AdminSRReviewView,
    AdminSRPriorityView,
    AdminSRAssignView,
    AdminSRDispatchView,
    AdminSRUpdateTechnicianLocationView,
    AdminSRRejectView,
    AdminSRVerifyView,
    AdminSRReworkView,
    AdminSRCloseView,
    AdminSRResendFeedbackView,

    # Admin — Feedback
    AdminFeedbackListView,
    AdminFeedbackMetricsView,

    # Work Extensions
    AdminWorkExtensionListView,
    AdminWorkExtensionApproveView,
    AdminWorkExtensionApprovePurchaseView,
    AdminWorkExtensionAssignView,
    CustomerWorkExtensionPortalView,
    CustomerWorkExtensionDecideView,
    SupportWorkExtensionRecordDecisionView,
    ServiceRequestSupplementalInvoiceView,

    # Reschedule
    CustomerActiveBookingsListView,
    CustomerBookingAvailableSlotsView,
    CustomerRescheduleRequestListView,
    CustomerRescheduleRequestCreateView,
    CustomerRescheduleRequestCancelView,
    CustomerRescheduleRespondToSuggestionView,
    CustomerRescheduleView,
    AdminRescheduleRequestListView,
    AdminRescheduleRequestReviewView,
    AdminRescheduleApproveView,
    AdminRescheduleRejectView,
    AdminRescheduleSuggestSlotView,
    AdminRescheduleListView,
    AdminRescheduleActionView,

    # Refund
    CustomerEligibleBookingsListView,
    CustomerBookingRefundSummaryView,
    CustomerRefundRequestCreateView,
    CustomerRefundRequestListView,
    CustomerRefundRequestDetailView,
    CustomerRefundView,
    AdminRefundRequestListView,
    AdminRefundRequestDetailView,
    AdminRefundApproveView,
    AdminRefundRejectView,
    AdminRefundRequestInfoView,
    AdminRefundSendToFinanceView,
    AdminRefundInternalNoteView,
    AdminRefundListView,
    AdminRefundActionView,
    CustomerWalletView, AdminWalletCreditView, TechnicianProfileView, AdminNotificationOutboxView,
    CustomerInsuranceClaimListCreateView, AdminInsuranceClaimListView, AdminInsuranceClaimResolveView,

    # Complaints
    CustomerComplaintListView,
    CustomerComplaintCreateView,
    CustomerComplaintDetailView,
    CustomerComplaintMessageCreateView,
    AdminComplaintListView,
    AdminComplaintDetailView,
    AdminComplaintAssignView,
    AdminComplaintStatusUpdateView,
    AdminComplaintResolveView,
    AdminComplaintMessageCreateView,

    # Marketing & Coupons
    CouponListCreateView,
    CouponDetailView,
    CustomerCouponListView,
    CustomerCouponValidateView,
    AdminCouponAnalyticsView,
)
from .payment_views import (
    PaymentInitiateView,
    PaymentVerifyView,
    AdminPaymentUpdateView,
    InvoiceDownloadView,
)
from .views_estimation import (
    CustomerBookingDetailView,
    CustomerEstimationDetailView,
    CustomerInspectionDetailView,
    CustomerBookingRateCardSnapshotView,
    CustomerQuotationDetailView,
    CustomerQuotationApproveView,
    CustomerQuotationRejectView,
)
from .views_ac_admin import (
    AdminACInspectionListView,
    AdminACInspectionDetailView,
    AdminACInspectionEstimationApproveView,
    AdminACInspectionEstimationSendBackView,
)
from .technician_views import (
    TechnicianAvailableBookingsView,
    TechnicianAcceptBookingView,
    TechnicianUpdateLocationView,
    TechnicianStatusUpdateView,
    TechnicianVerifyStartOTPView,
    TechnicianBookingDetailView,
)
from .views_time_slots import (
    CustomerServiceTimeSlotsView,
    AdminServiceTimeSlotListView,
    AdminGlobalTimeSlotConfigView,
    AdminServiceRevertDefaultView,
    AdminServiceTimeSlotDetailView,
    AdminServiceWeeklyScheduleView,
    AdminServiceDateOverrideView,
    AdminServiceDateOverrideDetailView,
    AdminServiceTimeSlotPreviewView,
)

urlpatterns = [
    # ── Service-wise Time Slot Management ─────────────────────────────────────
    path("services/<str:service_id>/time-slots/", CustomerServiceTimeSlotsView.as_view(), name="customer-service-time-slots"),
    path("admin/time-slots/services/", AdminServiceTimeSlotListView.as_view(), name="admin-time-slots-services-list"),
    path("admin/time-slots/global-default/", AdminGlobalTimeSlotConfigView.as_view(), name="admin-time-slots-global-default"),
    path("admin/time-slots/<str:service_id>/revert-default/", AdminServiceRevertDefaultView.as_view(), name="admin-time-slots-revert-default"),
    path("admin/time-slots/<str:service_id>/", AdminServiceTimeSlotDetailView.as_view(), name="admin-time-slots-detail"),
    path("admin/time-slots/<str:service_id>/config/", AdminServiceTimeSlotDetailView.as_view(), name="admin-time-slots-config"),
    path("admin/time-slots/<str:service_id>/weekly-schedule/", AdminServiceWeeklyScheduleView.as_view(), name="admin-time-slots-weekly-schedule"),
    path("admin/time-slots/<str:service_id>/date-overrides/", AdminServiceDateOverrideView.as_view(), name="admin-time-slots-date-overrides"),
    path("admin/time-slots/<str:service_id>/date-overrides/<int:override_id>/", AdminServiceDateOverrideDetailView.as_view(), name="admin-time-slots-date-override-detail"),
    path("admin/time-slots/<str:service_id>/preview/", AdminServiceTimeSlotPreviewView.as_view(), name="admin-time-slots-preview"),

    # ── Public & Customer ─────────────────────────────────────────────────────
    path("catalog/categories/",              CatalogCategoryListView.as_view(), name="catalog-categories"),
    path("catalog/services/",                CatalogServiceListView.as_view(),  name="catalog-services"),
    path("catalog/sub-services/",            CatalogSubServiceListView.as_view(), name="catalog-sub-services"),
    path("catalog/vegetables/recipes/",      VegetableRecipeListView.as_view(), name="catalog-vegetables-recipes"),
    path("catalog/vegetables/recipes/<str:pk>/", VegetableRecipeDetailView.as_view(), name="catalog-vegetables-recipe-detail"),
    path("catalog/vegetables/<int:product_id>/recommendations/", VegetableRecommendationListView.as_view(), name="catalog-vegetables-recommendations"),
    path("booking/",                         BookingCreateView.as_view(),    name="sr-booking"),

    path("booking/my-bookings/",             CustomerMyBookingsView.as_view(), name="sr-my-bookings"),
    path("booking/<int:pk>/retry-payment/",  CustomerBookingRetryPaymentView.as_view(), name="sr-retry-payment"),
    path("booking/<int:pk>/invoice/",        InvoiceDownloadView.as_view(),  name="sr-invoice"),
    path("booking/<int:pk>/live-location/",  CustomerBookingLiveLocationView.as_view(), name="sr-booking-live-location"),
    path("booking/<str:identifier>/live-location/", CustomerBookingLiveLocationView.as_view(), name="sr-booking-live-location-identifier"),
    path("customer/bookings/<int:pk>/tracking/", CustomerBookingLiveLocationView.as_view(), name="customer-booking-tracking"),
    path("customer/bookings/<str:identifier>/tracking/", CustomerBookingLiveLocationView.as_view(), name="customer-booking-tracking-identifier"),
    path("workforce/jobs/<int:pk>/live-tracking/", CustomerBookingLiveLocationView.as_view(), name="workforce-job-live-tracking"),
    path("workforce/jobs/<str:identifier>/live-tracking/", CustomerBookingLiveLocationView.as_view(), name="workforce-job-live-tracking-str"),
    path("tracking/<str:tracking_token>/",   CustomerPublicTrackingView.as_view(), name="sr-public-tracking-token"),
    path("booking/quote/<str:token>/",       CustomerQuoteDetailView.as_view(), name="sr-customer-quote-detail"),
    path("booking/<int:pk>/verify-start-otp/", BookingVerifyStartOTPView.as_view(), name="sr-booking-verify-start-otp"),
    path("booking/<str:identifier>/verify-start-otp/", BookingVerifyStartOTPView.as_view(), name="sr-booking-verify-start-otp-identifier"),
    path("booking/<int:pk>/cancel/",         CustomerBookingCancelView.as_view(),       name="sr-booking-cancel"),
    path("booking/<str:identifier>/cancel/", CustomerBookingCancelView.as_view(),       name="sr-booking-cancel-identifier"),
    path("customer/bookings/<int:pk>/cancel/", CustomerBookingCancelView.as_view(),     name="customer-booking-cancel"),
    path("customer/bookings/<str:identifier>/cancel/", CustomerBookingCancelView.as_view(), name="customer-booking-cancel-identifier"),

    # ── AC Inspection & Estimation (Phase 2) ──────────────────────────────────
    path("booking/<int:pk>/estimation/",      CustomerEstimationDetailView.as_view(),    name="sr-booking-estimation-pk"),
    path("booking/<str:identifier>/estimation/", CustomerEstimationDetailView.as_view(), name="sr-booking-estimation-identifier"),
    path("booking/<int:pk>/inspection/",      CustomerInspectionDetailView.as_view(),    name="sr-booking-inspection-pk"),
    path("booking/<str:identifier>/inspection/", CustomerInspectionDetailView.as_view(), name="sr-booking-inspection-identifier"),
    path("booking/<int:pk>/inspection-rate-card/", CustomerBookingRateCardSnapshotView.as_view(), name="sr-booking-inspection-rate-card-pk"),
    path("booking/<str:identifier>/inspection-rate-card/", CustomerBookingRateCardSnapshotView.as_view(), name="sr-booking-inspection-rate-card-identifier"),
    path("booking/<int:pk>/quotation/",       CustomerQuotationDetailView.as_view(),     name="sr-booking-quotation-pk"),
    path("booking/<str:identifier>/quotation/", CustomerQuotationDetailView.as_view(),   name="sr-booking-quotation-identifier"),
    path("booking/<int:pk>/quotation/approve/", CustomerQuotationApproveView.as_view(),  name="sr-booking-quotation-approve-pk"),
    path("booking/<str:identifier>/quotation/approve/", CustomerQuotationApproveView.as_view(), name="sr-booking-quotation-approve-identifier"),
    path("booking/<int:pk>/quotation/reject/", CustomerQuotationRejectView.as_view(),    name="sr-booking-quotation-reject-pk"),
    path("booking/<str:identifier>/quotation/reject/", CustomerQuotationRejectView.as_view(), name="sr-booking-quotation-reject-identifier"),
    path("booking/<int:pk>/",                 CustomerBookingDetailView.as_view(),       name="sr-booking-detail-pk"),
    path("booking/<str:identifier>/",         CustomerBookingDetailView.as_view(),       name="sr-booking-detail-identifier"),
    path("booking/<int:pk>/stops/",         CustomerBookingTripStopsView.as_view(), name="sr-booking-stops"),
    path("booking/<str:identifier>/stops/", CustomerBookingTripStopsView.as_view(), name="sr-booking-stops-identifier"),
    path("booking/<int:pk>/messages/",         CustomerBookingMessagesView.as_view(), name="sr-booking-messages"),
    path("booking/<str:identifier>/messages/", CustomerBookingMessagesView.as_view(), name="sr-booking-messages-identifier"),
    path("booking-series/", CustomerBookingSeriesListCreateView.as_view(), name="sr-booking-series"),
    path("booking-series/<int:pk>/status/", CustomerBookingSeriesStatusView.as_view(), name="sr-booking-series-status"),
    path("feedback/<uuid:token>/",           FeedbackTokenView.as_view(),    name="sr-feedback-token"),
    path("public/feedback/",                 PublicFeedbackListView.as_view(), name="sr-public-feedback"),

    # ── Customer Address Geocoding ─────────────────────────────────────────────
    path("customer/addresses/reverse-geocode/", CustomerReverseGeocodeView.as_view(), name="customer-reverse-geocode"),

    # ── Payment ───────────────────────────────────────────────────────────────
    path("payment/initiate/",                PaymentInitiateView.as_view(),  name="payment-initiate"),
    path("payment/verify/",                  PaymentVerifyView.as_view(),    name="payment-verify"),

    # ── Admin — Service Requests ──────────────────────────────────────────────
    path("admin/service-requests/",          AdminSRListView.as_view(),      name="sr-admin-list"),
    path("admin/service-requests/<int:pk>/", AdminSRDetailView.as_view(),    name="sr-admin-detail"),
    path("admin/service-requests/<int:pk>/review/",       AdminSRReviewView.as_view(),   name="sr-admin-review"),
    path("admin/service-requests/<int:pk>/priority/",     AdminSRPriorityView.as_view(), name="sr-admin-priority"),
    path("admin/service-requests/<int:pk>/assign/",       AdminSRAssignView.as_view(),   name="sr-admin-assign"),
    path("admin/service-requests/<int:pk>/dispatch/",     AdminSRDispatchView.as_view(), name="sr-admin-dispatch"),
    path("admin/service-requests/<int:pk>/technician-location/", AdminSRUpdateTechnicianLocationView.as_view(), name="sr-admin-technician-location"),
    path("admin/service-requests/<str:identifier>/technician-location/", AdminSRUpdateTechnicianLocationView.as_view(), name="sr-admin-technician-location-identifier"),
    path("booking/<int:pk>/update-location/", AdminSRUpdateTechnicianLocationView.as_view(), name="sr-booking-update-location"),
    path("booking/<str:identifier>/update-location/", AdminSRUpdateTechnicianLocationView.as_view(), name="sr-booking-update-location-identifier"),
    path("admin/service-requests/<int:pk>/reject/",       AdminSRRejectView.as_view(),   name="sr-admin-reject"),
    path("admin/service-requests/<int:pk>/verify/",       AdminSRVerifyView.as_view(),   name="sr-admin-verify"),
    path("admin/service-requests/<int:pk>/request-rework/", AdminSRReworkView.as_view(), name="sr-admin-rework"),
    path("admin/service-requests/<int:pk>/close/",        AdminSRCloseView.as_view(),    name="sr-admin-close"),
    path("admin/service-requests/<int:pk>/resend-feedback/", AdminSRResendFeedbackView.as_view(), name="sr-admin-resend-feedback"),
    path("admin/service-requests/<int:pk>/payment/",      AdminPaymentUpdateView.as_view(), name="sr-admin-payment"),

    # ── Admin — Feedback ──────────────────────────────────────────────────────
    path("admin/feedback/",                  AdminFeedbackListView.as_view(),   name="sr-admin-feedback-list"),
    path("admin/feedback/metrics/",          AdminFeedbackMetricsView.as_view(),name="sr-admin-feedback-metrics"),

    # ── Work Extensions ───────────────────────────────────────────────────────
    path("admin/work-extensions/",                         AdminWorkExtensionListView.as_view(), name="sr-admin-work-extensions"),
    path("admin/work-extensions/<int:ext_id>/approve/",    AdminWorkExtensionApproveView.as_view(), name="sr-admin-work-extension-approve"),
    path("admin/work-extensions/items/<int:item_id>/approve-purchase/", AdminWorkExtensionApprovePurchaseView.as_view(), name="sr-admin-work-extension-approve-purchase"),
    path("admin/work-extensions/<int:ext_id>/assign/",     AdminWorkExtensionAssignView.as_view(), name="sr-admin-work-extension-assign"),
    path("customer/work-extensions/<str:token>/",         CustomerWorkExtensionPortalView.as_view(), name="sr-customer-work-extension-portal"),
    path("customer/work-extensions/<str:token>/decide/",  CustomerWorkExtensionDecideView.as_view(), name="sr-customer-work-extension-decide"),
    path("support/work-extensions/<int:ext_id>/record-decision/", SupportWorkExtensionRecordDecisionView.as_view(), name="sr-support-work-extension-record-decision"),
    path("service-requests/<int:sr_id>/supplemental-invoice/", ServiceRequestSupplementalInvoiceView.as_view(), name="sr-supplemental-invoice"),

    # ── Complaints ────────────────────────────────────────────────────────────
    path('booking/complaints/',                          CustomerComplaintListView.as_view(),          name='customer-complaint-list'),
    path('booking/complaints/create/',                   CustomerComplaintCreateView.as_view(),        name='customer-complaint-create'),
    path('booking/complaints/<int:pk>/',                 CustomerComplaintDetailView.as_view(),        name='customer-complaint-detail'),
    path('booking/complaints/<int:pk>/response/',        CustomerComplaintMessageCreateView.as_view(), name='customer-complaint-response'),
    path('admin/complaints/',                            AdminComplaintListView.as_view(),             name='admin-complaint-list'),
    path('admin/complaints/<int:pk>/',                   AdminComplaintDetailView.as_view(),           name='admin-complaint-detail'),
    path('admin/complaints/<int:pk>/assign/',            AdminComplaintAssignView.as_view(),           name='admin-complaint-assign'),
    path('admin/complaints/<int:pk>/status/',            AdminComplaintStatusUpdateView.as_view(),     name='admin-complaint-status'),
    path('admin/complaints/<int:pk>/resolve/',           AdminComplaintResolveView.as_view(),          name='admin-complaint-resolve'),
    path('admin/complaints/<int:pk>/response/',          AdminComplaintMessageCreateView.as_view(),    name='admin-complaint-response'),

    # ── Reschedule ────────────────────────────────────────────────────────────
    path('customer/active-bookings/',                    CustomerActiveBookingsListView.as_view(),      name='customer-active-bookings'),
    path('customer/bookings/<int:booking_id>/slots/',    CustomerBookingAvailableSlotsView.as_view(),   name='customer-booking-slots'),
    path('customer/reschedules/',                        CustomerRescheduleRequestListView.as_view(),   name='customer-reschedule-list'),
    path('customer/reschedules/create/',                 CustomerRescheduleRequestCreateView.as_view(), name='customer-reschedule-create'),
    path('customer/reschedules/<int:pk>/cancel/',        CustomerRescheduleRequestCancelView.as_view(), name='customer-reschedule-cancel'),
    path('booking/reschedule/<int:pk>/cancel/',          CustomerRescheduleRequestCancelView.as_view(), name='booking-reschedule-cancel-alias'),
    path('service-requests/customer/reschedules/create/', CustomerRescheduleRequestCreateView.as_view(), name='sr-customer-reschedule-create'),
    path('service-requests/customer/reschedules/',      CustomerRescheduleRequestListView.as_view(),   name='sr-customer-reschedule-list'),
    path('admin/reschedules/list/',                      AdminRescheduleRequestListView.as_view(),      name='admin-reschedule-request-list'),
    path('service-requests/admin/reschedules/',          AdminRescheduleRequestListView.as_view(),      name='sr-admin-reschedule-request-list'),
    path('admin/reschedules/<int:pk>/review/',           AdminRescheduleRequestReviewView.as_view(),    name='admin-reschedule-request-review'),
    path('service-requests/admin/reschedules/<int:pk>/review/', AdminRescheduleRequestReviewView.as_view(), name='sr-admin-reschedule-request-review'),
    path('admin/reschedules/<int:pk>/approve/',          AdminRescheduleApproveView.as_view(),          name='admin-reschedule-approve'),
    path('admin/reschedules/<int:pk>/reject/',           AdminRescheduleRejectView.as_view(),           name='admin-reschedule-reject'),
    path('admin/reschedules/<int:pk>/suggest-slot/',     AdminRescheduleSuggestSlotView.as_view(),      name='admin-reschedule-suggest-slot'),
    path('customer/reschedules/<int:pk>/respond-suggestion/', CustomerRescheduleRespondToSuggestionView.as_view(), name='customer-reschedule-respond-suggestion'),
    path('booking/reschedule/',                          CustomerRescheduleView.as_view(),             name='customer-reschedule'),
    path('admin/reschedules/',                           AdminRescheduleListView.as_view(),            name='admin-reschedule-list'),
    path('admin/reschedules/<int:pk>/<str:action>/',     AdminRescheduleActionView.as_view(),          name='admin-reschedule-action'),

    # ── Refund ────────────────────────────────────────────────────────────────
    path('booking/refunds/',                             CustomerRefundView.as_view(),                 name='customer-refund'),
    path('admin/refunds/',                               AdminRefundListView.as_view(),                name='admin-refund-list'),
    path('admin/refunds/<int:pk>/<str:action>/',         AdminRefundActionView.as_view(),              name='admin-refund-action'),
    path('wallet/',                                        CustomerWalletView.as_view(),                 name='customer-wallet'),
    path('technicians/<str:technician_id>/profile/',       TechnicianProfileView.as_view(),              name='technician-profile'),
    path('admin/notifications/outbox/',                    AdminNotificationOutboxView.as_view(),        name='admin-notification-outbox'),
    path('insurance-claims/',                              CustomerInsuranceClaimListCreateView.as_view(), name='insurance-claims'),
    path('admin/insurance-claims/',                         AdminInsuranceClaimListView.as_view(),        name='admin-insurance-claims'),
    path('admin/insurance-claims/<int:pk>/resolve/',        AdminInsuranceClaimResolveView.as_view(),     name='admin-insurance-claim-resolve'),
    path('admin/customers/<int:user_id>/wallet/credit/',   AdminWalletCreditView.as_view(),              name='admin-wallet-credit'),
    path('customer/refunds/eligible-bookings/',          CustomerEligibleBookingsListView.as_view(),   name='customer-refund-eligible-bookings'),
    path('customer/refunds/bookings/<int:booking_id>/summary/', CustomerBookingRefundSummaryView.as_view(), name='customer-refund-summary'),
    path('customer/refunds/create/',                     CustomerRefundRequestCreateView.as_view(),    name='customer-refund-create'),
    path('customer/refunds/',                            CustomerRefundRequestListView.as_view(),      name='customer-refund-list'),
    path('customer/refunds/<int:pk>/',                   CustomerRefundRequestDetailView.as_view(),    name='customer-refund-detail'),
    path('admin/refunds/list/',                          AdminRefundRequestListView.as_view(),         name='admin-refund-request-list'),
    path('admin/refunds/<int:pk>/detail/',               AdminRefundRequestDetailView.as_view(),       name='admin-refund-request-detail'),
    path('admin/refunds/<int:pk>/approve/',              AdminRefundApproveView.as_view(),             name='admin-refund-approve'),
    path('admin/refunds/<int:pk>/reject/',               AdminRefundRejectView.as_view(),              name='admin-refund-reject'),
    path('admin/refunds/<int:pk>/request-info/',         AdminRefundRequestInfoView.as_view(),        name='admin-refund-request-info'),
    path('admin/refunds/<int:pk>/send-to-finance/',      AdminRefundSendToFinanceView.as_view(),       name='admin-refund-send-to-finance'),
    path('admin/refunds/<int:pk>/internal-note/',        AdminRefundInternalNoteView.as_view(),        name='admin-refund-internal-note'),

    # ── Marketing & Coupons ───────────────────────────────────────────────────
    path('coupons/',                                     CouponListCreateView.as_view(),               name='coupon-list-create'),
    path('coupons/<int:pk>/',                            CouponDetailView.as_view(),                   name='coupon-detail'),
    path('coupons/apply/',                               CustomerCouponValidateView.as_view(),        name='coupon-apply'),
    path('admin/coupons/',                               CouponListCreateView.as_view(),               name='admin-coupon-list-create'),
    path('admin/coupons/analytics/',                     AdminCouponAnalyticsView.as_view(),           name='admin-coupon-analytics'),
    path('admin/coupons/<int:pk>/',                      CouponDetailView.as_view(),                   name='admin-coupon-detail'),
    path('customer/coupons/',                            CustomerCouponListView.as_view(),             name='customer-coupon-list'),
    path('customer/coupons/validate/',                   CustomerCouponValidateView.as_view(),         name='customer-coupon-validate'),

    # ── Customer Quotation Decision & Tracking by Token ──────────────────────
    path('booking/quote/<str:token>/',                   CustomerQuoteDetailView.as_view(),             name='customer-quote-detail'),
    path('booking/quote/<str:token>/decide/',            CustomerQuoteDecideView.as_view(),             name='customer-quote-decide'),
    path('booking/quote/<str:token>/pdf/',               CustomerQuotePDFView.as_view(),                name='customer-quote-pdf'),
    path('workforce/quotes/decision/<str:token>/',       WorkforceQuoteDecisionBridgeView.as_view(),    name='workforce-quote-decision-bridge'),
    path('customer/quote-token/<str:token>/',            WorkforceQuoteDecisionBridgeView.as_view(),    name='customer-quote-token-bridge'),
    path('booking/<int:booking_id>/quote/pdf/',          CustomerQuotePDFView.as_view(),               name='customer-booking-quote-pdf'),
    path('booking/<str:identifier>/quote/pdf/',          CustomerQuotePDFView.as_view(),               name='customer-booking-str-quote-pdf'),
    path('admin/painting/rate-card/',                    AdminPaintingRateCardListView.as_view(),       name='admin-painting-rate-card-list'),
    path('admin/painting/rate-card/<int:pk>/',           AdminPaintingRateCardDetailView.as_view(),     name='admin-painting-rate-card-detail'),
    path('admin/painting/quotes/create/',                AdminQuoteCreateView.as_view(),                name='admin-painting-quote-create'),
    path('admin/painting/quotes/<int:pk>/action/',       AdminQuoteActionView.as_view(),                name='admin-painting-quote-action'),
    path('admin/mason/quotes/create/',                   AdminQuoteCreateView.as_view(),                name='admin-mason-quote-create'),
    path('admin/mason/quotes/<int:pk>/action/',          AdminQuoteActionView.as_view(),                name='admin-mason-quote-action'),

    # ── AC Inspection & Spare Parts Rate Card (PostgreSQL Single Source of Truth) ──
    path('ac-inspection/rate-card/',                     ACRateCardPublicView.as_view(),                name='ac-rate-card-public'),
    path('service-requests/ac-inspection/rate-card/',    ACRateCardPublicView.as_view(),                name='sr-ac-rate-card-public'),
    path('admin/ac-inspection/categories/',              AdminACRateCategoryListCreateView.as_view(),   name='admin-ac-category-list'),
    path('service-requests/admin/ac-inspection/categories/', AdminACRateCategoryListCreateView.as_view(), name='sr-admin-ac-category-list'),
    path('admin/ac-inspection/categories/<int:pk>/',     AdminACRateCategoryDetailView.as_view(),       name='admin-ac-category-detail'),
    path('service-requests/admin/ac-inspection/categories/<int:pk>/', AdminACRateCategoryDetailView.as_view(), name='sr-admin-ac-category-detail'),
    path('admin/ac-inspection/items/',                   AdminACRateItemListCreateView.as_view(),       name='admin-ac-item-list'),
    path('service-requests/admin/ac-inspection/items/',  AdminACRateItemListCreateView.as_view(),       name='sr-admin-ac-item-list'),
    path('admin/ac-inspection/items/<int:pk>/',          AdminACRateItemDetailView.as_view(),           name='admin-ac-item-detail'),
    path('service-requests/admin/ac-inspection/items/<int:pk>/', AdminACRateItemDetailView.as_view(),   name='sr-admin-ac-item-detail'),
    path('admin/ac-inspection/config/',                  AdminACInspectionConfigView.as_view(),         name='admin-ac-inspection-config'),
    path('service-requests/admin/ac-inspection/config/', AdminACInspectionConfigView.as_view(),         name='sr-admin-ac-inspection-config'),
    path('admin/ac-inspection/reset-defaults/',          AdminACInspectionResetDefaultsView.as_view(),   name='admin-ac-inspection-reset'),
    path('service-requests/admin/ac-inspection/reset-defaults/', AdminACInspectionResetDefaultsView.as_view(), name='sr-admin-ac-inspection-reset'),
    path('technician/bookings/<str:identifier>/quotation/', TechnicianACQuotationCreateView.as_view(),  name='technician-ac-quotation-create'),
    path('service-requests/technician/bookings/<str:identifier>/quotation/', TechnicianACQuotationCreateView.as_view(),  name='sr-technician-ac-quotation-create'),
    path('technician/bookings/<int:identifier>/quotation/', TechnicianACQuotationCreateView.as_view(),  name='technician-ac-quotation-create-int'),
    path('service-requests/technician/bookings/<int:identifier>/quotation/', TechnicianACQuotationCreateView.as_view(),  name='sr-technician-ac-quotation-create-int'),

    # ── Technician Portal / App Endpoints ─────────────────────────────────────
    path('technician/bookings/',                         TechnicianAvailableBookingsView.as_view(),    name='technician-bookings-list'),
    path('technician/bookings/<int:pk>/accept/',         TechnicianAcceptBookingView.as_view(),        name='technician-booking-accept'),
    path('technician/bookings/<str:identifier>/accept/', TechnicianAcceptBookingView.as_view(),        name='technician-booking-accept-str'),
    path('technician/bookings/<int:pk>/location/',       TechnicianUpdateLocationView.as_view(),       name='technician-booking-location'),
    path('technician/bookings/<str:identifier>/location/', TechnicianUpdateLocationView.as_view(),     name='technician-booking-location-str'),
    path('technician/bookings/<int:pk>/status/',         TechnicianStatusUpdateView.as_view(),         name='technician-booking-status'),
    path('technician/bookings/<str:identifier>/status/', TechnicianStatusUpdateView.as_view(),         name='technician-booking-status-str'),
    path('technician/bookings/<int:pk>/verify-otp/',     TechnicianVerifyStartOTPView.as_view(),       name='technician-booking-verify-otp'),
    path('technician/bookings/<str:identifier>/verify-otp/', TechnicianVerifyStartOTPView.as_view(),   name='technician-booking-verify-otp-str'),
    # Full detail for a single booking (includes cart_data, fare_breakdown, trip_stops)
    path('technician/bookings/<int:pk>/detail/',          TechnicianBookingDetailView.as_view(),        name='technician-booking-detail'),
    path('technician/bookings/<str:identifier>/detail/',  TechnicianBookingDetailView.as_view(),        name='technician-booking-detail-str'),

    # ── Customer AC Inspection & Estimation Lifecycle ─────────────────────────
    path('booking/<int:pk>/',                            CustomerBookingDetailView.as_view(),           name='customer-booking-detail-int'),
    path('booking/<str:identifier>/',                    CustomerBookingDetailView.as_view(),           name='customer-booking-detail-str'),
    path('service-requests/booking/<int:pk>/',           CustomerBookingDetailView.as_view(),           name='sr-customer-booking-detail-int'),
    path('service-requests/booking/<str:identifier>/',   CustomerBookingDetailView.as_view(),           name='sr-customer-booking-detail-str'),

    path('booking/<int:pk>/estimation/',                 CustomerEstimationDetailView.as_view(),        name='customer-estimation-detail-int'),
    path('booking/<str:identifier>/estimation/',         CustomerEstimationDetailView.as_view(),        name='customer-estimation-detail-str'),
    path('service-requests/booking/<int:pk>/estimation/', CustomerEstimationDetailView.as_view(),       name='sr-customer-estimation-detail-int'),
    path('service-requests/booking/<str:identifier>/estimation/', CustomerEstimationDetailView.as_view(), name='sr-customer-estimation-detail-str'),

    path('booking/<int:pk>/inspection/',                 CustomerInspectionDetailView.as_view(),        name='customer-inspection-detail-int'),
    path('booking/<str:identifier>/inspection/',         CustomerInspectionDetailView.as_view(),        name='customer-inspection-detail-str'),
    path('service-requests/booking/<int:pk>/inspection/', CustomerInspectionDetailView.as_view(),       name='sr-customer-inspection-detail-int'),
    path('service-requests/booking/<str:identifier>/inspection/', CustomerInspectionDetailView.as_view(), name='sr-customer-inspection-detail-str'),

    path('booking/<int:pk>/inspection-rate-card/',       CustomerBookingRateCardSnapshotView.as_view(), name='customer-inspection-rate-card-int'),
    path('booking/<str:identifier>/inspection-rate-card/', CustomerBookingRateCardSnapshotView.as_view(), name='customer-inspection-rate-card-str'),
    path('service-requests/booking/<int:pk>/inspection-rate-card/', CustomerBookingRateCardSnapshotView.as_view(), name='sr-customer-inspection-rate-card-int'),
    path('service-requests/booking/<str:identifier>/inspection-rate-card/', CustomerBookingRateCardSnapshotView.as_view(), name='sr-customer-inspection-rate-card-str'),

    path('booking/<int:pk>/quotation/',                  CustomerQuotationDetailView.as_view(),         name='customer-quotation-detail-int'),
    path('booking/<str:identifier>/quotation/',          CustomerQuotationDetailView.as_view(),         name='customer-quotation-detail-str'),
    path('service-requests/booking/<int:pk>/quotation/', CustomerQuotationDetailView.as_view(),         name='sr-customer-quotation-detail-int'),
    path('service-requests/booking/<str:identifier>/quotation/', CustomerQuotationDetailView.as_view(), name='sr-customer-quotation-detail-str'),

    path('booking/<int:pk>/quotation/approve/',          CustomerQuotationApproveView.as_view(),        name='customer-quotation-approve-int'),
    path('booking/<str:identifier>/quotation/approve/',  CustomerQuotationApproveView.as_view(),        name='customer-quotation-approve-str'),
    path('service-requests/booking/<int:pk>/quotation/approve/', CustomerQuotationApproveView.as_view(), name='sr-customer-quotation-approve-int'),
    path('service-requests/booking/<str:identifier>/quotation/approve/', CustomerQuotationApproveView.as_view(), name='sr-customer-quotation-approve-str'),

    path('booking/<int:pk>/quotation/reject/',           CustomerQuotationRejectView.as_view(),         name='customer-quotation-reject-int'),
    path('booking/<str:identifier>/quotation/reject/',   CustomerQuotationRejectView.as_view(),         name='customer-quotation-reject-str'),
    path('service-requests/booking/<int:pk>/quotation/reject/', CustomerQuotationRejectView.as_view(),  name='sr-customer-quotation-reject-int'),
    path('service-requests/booking/<str:identifier>/quotation/reject/', CustomerQuotationRejectView.as_view(), name='sr-customer-quotation-reject-str'),

    # ── Customer Admin: Dedicated AC Inspection Bookings Module ────────────────
    path('admin/ac-inspections/',                        AdminACInspectionListView.as_view(),           name='admin-ac-inspections-list'),
    path('service-requests/admin/ac-inspections/',       AdminACInspectionListView.as_view(),           name='sr-admin-ac-inspections-list'),
    path('admin/ac-inspections/<int:pk>/',               AdminACInspectionDetailView.as_view(),         name='admin-ac-inspection-detail-int'),
    path('service-requests/admin/ac-inspections/<int:pk>/', AdminACInspectionDetailView.as_view(),      name='sr-admin-ac-inspection-detail-int'),
    path('admin/ac-inspections/<str:identifier>/',       AdminACInspectionDetailView.as_view(),         name='admin-ac-inspection-detail-str'),
    path('service-requests/admin/ac-inspections/<str:identifier>/', AdminACInspectionDetailView.as_view(), name='sr-admin-ac-inspection-detail-str'),

    path('admin/ac-inspections/<int:pk>/estimation/approve/', AdminACInspectionEstimationApproveView.as_view(), name='admin-ac-inspection-approve-int'),
    path('service-requests/admin/ac-inspections/<int:pk>/estimation/approve/', AdminACInspectionEstimationApproveView.as_view(), name='sr-admin-ac-inspection-approve-int'),
    path('admin/ac-inspections/<str:identifier>/estimation/approve/', AdminACInspectionEstimationApproveView.as_view(), name='admin-ac-inspection-approve-str'),
    path('service-requests/admin/ac-inspections/<str:identifier>/estimation/approve/', AdminACInspectionEstimationApproveView.as_view(), name='sr-admin-ac-inspection-approve-str'),

    path('admin/ac-inspections/<int:pk>/estimation/send-back/', AdminACInspectionEstimationSendBackView.as_view(), name='admin-ac-inspection-sendback-int'),
    path('service-requests/admin/ac-inspections/<int:pk>/estimation/send-back/', AdminACInspectionEstimationSendBackView.as_view(), name='sr-admin-ac-inspection-sendback-int'),
    path('admin/ac-inspections/<str:identifier>/estimation/send-back/', AdminACInspectionEstimationSendBackView.as_view(), name='admin-ac-inspection-sendback-str'),
    path('service-requests/admin/ac-inspections/<str:identifier>/estimation/send-back/', AdminACInspectionEstimationSendBackView.as_view(), name='sr-admin-ac-inspection-sendback-str'),
]
