# Generated by hand (not `makemigrations`) -- same reasoning as
# 0001_initial.py: the autodetector inspects the whole project graph, and
# this merged codebase has unrelated pending schema drift in
# `service_requests` that has nothing to do with this addition. Written by
# hand so it touches nothing outside `orders`.
#
# Depends on service_requests' latest migration at the time this was
# written (0085_merge_20260911_0935) only so Django can resolve the
# `package` ForeignKey target -- this migration does not alter that app's
# schema in any way.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("service_requests", "0085_merge_20260911_0935"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroceryOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ("status", models.CharField(choices=[("PLACED", "Placed"), ("PACKED", "Packed"), ("OUT_FOR_DELIVERY", "Out for Delivery"), ("DELIVERED", "Delivered"), ("CANCELLED", "Cancelled")], db_index=True, default="PLACED", max_length=20)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("delivery_address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(help_text="The customer who placed this grocery order.", on_delete=django.db.models.deletion.PROTECT, related_name="grocery_orders", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "orders_groceryorder",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroceryOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_grams", models.PositiveIntegerField()),
                ("unit_price_snapshot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.groceryorder")),
                ("package", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grocery_order_items", to="service_requests.package")),
            ],
            options={
                "db_table": "orders_groceryorderitem",
                "ordering": ["id"],
            },
        ),
    ]
