# Generated by Django 6.0.8 on 2026-09-19 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_grocery_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOrderOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER_INTAKE', 'Order Intake'), ('ORDER_CANCEL', 'Order Cancel')], max_length=30)),
                ('source_order_id', models.CharField(db_index=True, max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders_marketplaceorderoutbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('seller_id', models.IntegerField(db_index=True)),
                ('seller_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('vendor_order_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PACKING', 'Seller is packing'), ('READY_FOR_PICKUP', 'Ready for pickup'), ('OUT_FOR_DELIVERY', 'On the way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=25)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_address', models.TextField()),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_email', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(default='UPI', max_length=50)),
                ('payment_status', models.CharField(default='PAID', max_length=50)),
                ('payment_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_intake_synced', models.BooleanField(default=False)),
                ('vendor_intake_response', models.JSONField(blank=True, default=dict)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='The customer who placed this marketplace order.', on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_marketplaceorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_product_id', models.IntegerField(db_index=True)),
                ('product_title', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, default='', max_length=100)),
                ('product_brand', models.CharField(blank=True, default='', max_length=150)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('pack_size', models.CharField(blank=True, default='', max_length=50)),
                ('product_image', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.marketplaceorder')),
            ],
            options={
                'db_table': 'orders_marketplaceorderitem',
                'ordering': ['id'],
            },
        ),
    ]
