# Generated by Django 6.0.8 on 2026-09-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_marketplaceorderoutbox_marketplaceorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='cancellation_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_slot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='handover_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='last_applied_vendor_sequence',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='needs_refund_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplaceorderoutbox',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='MarketplaceOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0)),
                ('event_type', models.CharField(max_length=60)),
                ('vendor_status', models.CharField(max_length=50)),
                ('previous_vendor_status', models.CharField(blank=True, default='', max_length=50)),
                ('mapped_status', models.CharField(blank=True, default='', max_length=50)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('VENDOR_EVENT', 'Vendor Webhook Event'), ('RECONCILE', 'Reconcile Poll')], default='VENDOR_EVENT', max_length=30)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_by', models.CharField(blank=True, default='', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.marketplaceorder')),
            ],
            options={
                'db_table': 'orders_marketplaceorderevent',
                'ordering': ['sequence', 'occurred_at', 'id'],
            },
        ),
    ]
