# Generated by Django 6.0.8 on 2026-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_marketplaceorder_cancellation_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_group_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Shared identifier linking sibling marketplace orders checked out together from the same warehouse.', max_length=100),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='warehouse_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='warehouse_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
