# Generated by Django 6.0.8 on 2026-09-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_cleanup_migrated_vegetable_grocery_orders"),
        ("orders", "0004_marketplaceorder_cancellation_pending_and_more"),
    ]

    operations = []
