# Generated by Django 6.0.8 on 2026-09-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_marketplaceorder_delivery_group_id_and_more'),
        ('orders', '0005_merge_20260923_1722'),
    ]

    operations = [
    ]
