# Generated by Django 6.0.8 on 2026-09-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_marketplaceorder_delivery_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorderitem',
            name='basket_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceorderitem',
            name='basket_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='marketplaceorderitem',
            name='product_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='marketplaceorderitem',
            name='seller_product_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
