# Generated by Django 5.2.17 on 2026-09-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_marketplaceorder_delivery_group_id_and_more'),
        ('orders', '0005_merge_20260923_1722'),
    ]

    operations = [
    ]
