# Generated by Django 6.0.8 on 2026-09-28 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_basket_support'),
        ('orders', '0006_basket_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Authoritative amount in INR.', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='CREATED', max_length=20)),
                ('checkout_payload', models.JSONField(blank=True, default=dict, help_text='Snapshot of validated checkout fields.')),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, help_text='The marketplace cart this intent was created against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='carts.cart')),
                ('customer', models.ForeignKey(help_text='Customer who initiated this payment intent.', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_marketplacepaymentintent',
                'ordering': ['-created_at'],
            },
        ),
    ]
