# Generated by Django on 2026-09-16
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("role", models.CharField(blank=True, default="", max_length=50)),
                ("agent_type", models.CharField(default="customer", max_length=50)),
                ("user_query", models.TextField()),
                ("tool_name", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("resource_id", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("authorization_result", models.CharField(choices=[("granted", "Granted"), ("denied", "Denied"), ("not_required", "Not Required")], default="not_required", max_length=30)),
                ("status", models.CharField(choices=[("success", "Success"), ("error", "Error"), ("blocked_by_guardrail", "Blocked by Guardrail")], default="success", max_length=30)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.CharField(db_index=True, max_length=200)),
                ("source_category", models.CharField(choices=[("policy", "Policy"), ("package", "Package"), ("vendor_guide", "Vendor Guide"), ("faq", "FAQ"), ("help", "Help")], db_index=True, default="policy", max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source_category", "title"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("agent_type", models.CharField(choices=[("customer", "Customer Agent"), ("vendor", "Vendor Agent"), ("public", "Public Agent")], db_index=True, default="customer", max_length=32)),
                ("title", models.CharField(default="New Conversation", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="ai_conversations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sender", models.CharField(choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System"), ("tool", "Tool")], max_length=16)),
                ("content", models.TextField()),
                ("tool_calls", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="ai_assistant.conversation")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
