/**
 * catalogData.js
 * Quick-Commerce Catalog Data matching image1.png specifications
 */

export const QUICK_CATEGORIES = [
  { id: 'compressors', name: 'Compressors', assetId: 'cat-compressors', count: 24 },
  { id: 'filters', name: 'Filters', assetId: 'cat-filters', count: 48 },
  { id: 'dryers', name: 'Dryers', assetId: 'cat-dryers', count: 18 },
  { id: 'lubricants', name: 'Lubricants', assetId: 'cat-lubricants', count: 12 },
  { id: 'valves', name: 'Valves', assetId: 'cat-valves', count: 32 },
  { id: 'hoses', name: 'Hoses', assetId: 'cat-hoses', count: 28 },
  { id: 'spare-parts', name: 'Spare Parts', assetId: 'cat-spareparts', count: 64 },
  { id: 'all', name: 'All Categories', assetId: 'cat-all', count: 226 },
];

export const QUICK_PRODUCTS = [
  {
    id: 'prod-screw-compressor',
    title: 'Atlas Copco Screw Compressor GA55',
    category: 'compressors',
    price: 285000,
    mrp: 310000,
    rating: 4.5,
    reviewsCount: 128,
    assetId: 'prod-screw-compressor',
    sku: 'CP-GA55-01',
    stockStatus: 'In Stock',
    stockCount: 8,
    brand: 'Atlas Copco',
    description:
      'High-efficiency oil-injected rotary screw compressor engineered for continuous industrial duty with integrated Elektronikon monitoring.',
    features: ['55 kW Motor Rating', '8.5 bar Working Pressure', 'Low Sound Enclosure (68 dB)', 'IE4 Super Premium Efficiency'],
    warranty: '2 Year Factory Warranty',
  },
  {
    id: 'prod-piston-compressor',
    title: 'Ingersoll Rand Air Compressor 5HP',
    category: 'compressors',
    price: 95000,
    mrp: 110000,
    rating: 4.3,
    reviewsCount: 96,
    assetId: 'prod-piston-compressor',
    sku: 'CP-IR5-02',
    stockStatus: 'In Stock',
    stockCount: 12,
    brand: 'Ingersoll Rand',
    description:
      'Cast-iron two-stage industrial reciprocating air compressor with high-durability stainless steel reed valves and thermal overload switch.',
    features: ['5 HP Heavy Duty Motor', '175 PSI Max Pressure', '200 Liter Air Receiver', '100% Cast Iron Frame'],
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod-air-filter-element',
    title: 'Atlas Copco Air Filter Element',
    category: 'filters',
    price: 2450,
    mrp: 3200,
    rating: 4.6,
    reviewsCount: 342,
    assetId: 'prod-air-filter-element',
    sku: 'AC-10254',
    stockStatus: 'In Stock',
    stockCount: 45,
    brand: 'Atlas Copco',
    description:
      'Genuine Atlas Copco OEM air filter element for superior dust separation, maximum particulate capture, and optimal air intake.',
    features: ['High-efficiency cellulose media', '99.9% filtration at 3 microns', 'Anti-collapse wire mesh support'],
    warranty: '1 Year Genuine Warranty',
  },
  {
    id: 'prod-ir-air-filter',
    title: 'Ingersoll Rand Air Filter Cartridge',
    category: 'filters',
    price: 2750,
    mrp: 3400,
    rating: 4.3,
    reviewsCount: 210,
    assetId: 'prod-ir-air-filter',
    sku: 'FL-IR99-03',
    stockStatus: 'In Stock',
    stockCount: 24,
    brand: 'Ingersoll Rand',
    description:
      'Precision replacement air cartridge designed for extreme duty operations in high-dust industrial environments.',
    features: ['Radial seal technology', 'Corrosion-proof end caps', 'Optimized pleat geometry'],
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod-sullair-air-filter',
    title: 'Sullair Precision Air Filter',
    category: 'filters',
    price: 3100,
    mrp: 3900,
    rating: 4.5,
    reviewsCount: 98,
    assetId: 'prod-sullair-air-filter',
    sku: 'FL-SL44-04',
    stockStatus: 'In Stock',
    stockCount: 16,
    brand: 'Sullair',
    description:
      'Sullair OEM air filter element guaranteeing minimal pressure drop and maximum protection against abrasive particles.',
    features: ['High dirt holding capacity', 'Oil-resistant seal', 'Synthetic fiber matrix'],
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod-pressure-gauge',
    title: 'Pressure Gauge 0-16 bar',
    category: 'valves',
    price: 850,
    mrp: 1200,
    rating: 4.4,
    reviewsCount: 210,
    assetId: 'prod-pressure-gauge',
    sku: 'GA-16B-05',
    stockStatus: 'In Stock',
    stockCount: 65,
    brand: 'WIKA',
    description:
      'Glycerin-filled stainless steel pressure gauge with dual scale bar/psi readings and 1/4 inch NPT brass connection.',
    features: ['Vibration-resistant glycerin filling', 'Accuracy Class 1.6', 'Stainless steel 304 casing'],
    warranty: '1 Year Replacement Guarantee',
  },
  {
    id: 'prod-lubricant-oil',
    title: 'Synthetic Lubricant Oil (5L)',
    category: 'lubricants',
    price: 3200,
    mrp: 4100,
    rating: 4.7,
    reviewsCount: 154,
    assetId: 'prod-lubricant-oil',
    sku: 'LB-SYN5L-06',
    stockStatus: 'In Stock',
    stockCount: 30,
    brand: 'SEVO Pro',
    description:
      'Engineered premium ISO VG 46 synthetic compressor oil providing up to 4000 hours of thermal stability and wear reduction.',
    features: ['4000 Hours Drain Interval', 'Anti-foaming formulation', 'Rapid water separation'],
    warranty: '100% Quality Assurance',
  },
  {
    id: 'prod-kaeser-filter',
    title: 'Kaeser Micron Air Filter',
    category: 'filters',
    price: 2900,
    mrp: 3700,
    rating: 4.3,
    reviewsCount: 76,
    assetId: 'prod-kaeser-filter',
    sku: 'FL-KS12-07',
    stockStatus: 'In Stock',
    stockCount: 19,
    brand: 'Kaeser',
    description:
      'High-grade micro-filter element for compressed air systems providing clean intake air and extending pump lifespan.',
    features: ['OEM standard fit', 'Reinforced pleat design', 'Moisture resistant'],
    warranty: '1 Year Warranty',
  },
  {
    id: 'prod-donaldson-filter',
    title: 'Donaldson Heavy-Duty Air Filter',
    category: 'filters',
    price: 3400,
    mrp: 4200,
    rating: 4.7,
    reviewsCount: 112,
    assetId: 'prod-donaldson-filter',
    sku: 'FL-DN88-08',
    stockStatus: 'In Stock',
    stockCount: 22,
    brand: 'Donaldson',
    description:
      'Industrial heavy-duty engine and compressor filtration cartridge built for harsh operating conditions.',
    features: ['Ultra-Web nanofiber technology', 'Maximum dust capture efficiency', 'Extended service life'],
    warranty: '1 Year Warranty',
  },
];
