# Generated by Django 6.0.5 on 2026-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_hub', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='default_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='region',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('UK', 'United Kingdom')], max_length=2, null=True),
        ),
    ]
