# Generated by Django 6.0.5 on 2026-07-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_hub', '0003_teaminvite_default_state_teaminvite_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='region',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('IN', 'India')], max_length=2, null=True),
        ),
    ]
