# Generated by Django 6.0.8 on 2026-08-13 06:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_hub', '0004_alter_teaminvite_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('config_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home Page Config',
                'verbose_name_plural': 'Home Page Configs',
            },
        ),
        migrations.CreateModel(
            name='HomePageMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=50)),
                ('original_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=500, unique=True)),
                ('mime_type', models.CharField(default='image/webp', max_length=50)),
                ('file_size', models.IntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNREFERENCED', 'Unreferenced'), ('PENDING_DELETE', 'Pending Delete'), ('DELETED', 'Deleted'), ('DELETE_FAILED', 'Delete Failed')], default='UNREFERENCED', max_length=30)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home Page Media',
                'verbose_name_plural': 'Home Page Media Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
