# Generated by Django on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_hub', '0005_homepageconfig_homepagemedia'),
    ]

    operations = [
        # 1. Update NotificationPreference
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_leave_updates',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_payroll_ready',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_task_assigned',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_shift_reminders',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='inapp_leave_updates',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='inapp_task_assigned',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='inapp_clock_reminders',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='inapp_payroll_ready',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_clock_reminders',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_leave_updates',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_shift_reminders',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_booking_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='inapp_booking_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms_booking_updates',
            field=models.BooleanField(default=True),
        ),

        # 2. Update TeamInvite role
        migrations.AlterField(
            model_name='teaminvite',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('support', 'Customer Support')], default='support', max_length=20),
        ),
    ]
