# Generated by Django 6.0.8 on 2026-08-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_hub', '0006_clean_notification_and_team_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
