# Generated by Django 6.0.8 on 2026-08-20 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('settings_hub', '0007_alter_invoice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#4F46E5', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('zone_type', models.CharField(choices=[('circle', 'Circle (Radius)'), ('polygon', 'Polygon (Drawn)')], default='circle', max_length=10)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('radius_meters', models.FloatField(default=5000.0)),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_zones', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Zone',
                'verbose_name_plural': 'Service Zones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceZoneService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_slug', models.CharField(help_text='Service slug/key from catalog', max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=150)),
                ('is_available', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_services', to='settings_hub.servicezone')),
            ],
            options={
                'ordering': ['service_slug'],
                'unique_together': {('zone', 'service_slug')},
            },
        ),
    ]
