# Generated by hand (not `makemigrations`) -- same reasoning as
# orders/migrations/0001_initial.py: the autodetector inspects the whole
# project graph, and this merged codebase has unrelated pending schema
# drift in `service_requests` that has nothing to do with this new `carts`
# app. Written by hand so it touches nothing outside `carts`.
#
# Depends on service_requests' latest migration at the time this was
# written (0085_merge_20260911_0935) only so Django can resolve the
# `package` ForeignKey target -- this migration does not alter that app's
# schema in any way.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service_requests", "0085_merge_20260911_0935"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cart_type", models.CharField(choices=[("services", "Services"), ("daily_essentials", "Daily Essentials")], max_length=20)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("CHECKED_OUT", "Checked Out"), ("ABANDONED", "Abandoned")], default="ACTIVE", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="carts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "carts_cart",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price_snapshot", models.DecimalField(decimal_places=2, max_digits=10)),
                ("customization", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="carts.cart")),
                ("package", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to="service_requests.package")),
            ],
            options={
                "db_table": "carts_cartitem",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "ACTIVE")), fields=("customer", "cart_type"), name="unique_active_cart_per_customer_and_type"),
        ),
    ]
