# Generated by Django 6.0.8 on 2026-09-19 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('service_requests', '0087_alter_catalogchangelog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seller_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='seller_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='mrp_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pack_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_brand',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='seller_product_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_type',
            field=models.CharField(choices=[('services', 'Services'), ('daily_essentials', 'Daily Essentials'), ('marketplace', 'Marketplace')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='service_requests.package'),
        ),
    ]
