# Generated by Django 6.0.8 on 2026-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_seller_id_cart_seller_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='seller_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='seller_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='warehouse_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='warehouse_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
