# Generated by Django 6.0.8 on 2026-09-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cart_seller_id_cart_seller_name_and_more"),
        ("carts", "0002_cartitem_variant"),
    ]

    operations = []
