# Generated by Django 6.0.8 on 2026-09-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_seller_id_cartitem_seller_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='basket_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='basket_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
