# Generated by Django 6.0.8 on 2026-09-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_seller_id_cartitem_seller_name_and_more'),
        ('carts', '0003_merge_20260925_1540'),
    ]

    operations = [
    ]
