# Generated by Django 5.2.17 on 2026-09-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_merge_20260928_1831'),
        ('carts', '0004_merge_20260929_1202'),
    ]

    operations = [
    ]
