# Generated by Django 6.0.8 on 2026-08-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_care', '0002_message_template_and_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(choices=[('general', 'General Support'), ('billing', 'Billing & Payments'), ('technical', 'Technical Issue'), ('scheduling', 'Scheduling & Dispatch'), ('feedback', 'Customer Feedback'), ('other', 'Other')], max_length=30),
        ),
    ]
