# Generated by Django 6.0.7 on 2026-08-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_care', '0003_alter_messagetemplate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careagentprofile',
            name='care_role',
            field=models.CharField(choices=[('care_executive', 'Care Executive'), ('senior_care', 'Senior Care'), ('ops_manager', 'Ops Manager'), ('admin', 'Admin Support')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customercareticket',
            name='category',
            field=models.CharField(choices=[('booking_issue', 'Booking Issue'), ('service_quality', 'Service Quality'), ('technician_issue', 'Technician Issue'), ('payment_issue', 'Payment Issue'), ('refund', 'Refund'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule'), ('pricing_issue', 'Pricing Issue'), ('missing_damaged', 'Missing / Damaged Item'), ('safety_issue', 'Safety Issue'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(choices=[('booking_issue', 'Booking Issue'), ('service_quality', 'Service Quality'), ('technician_issue', 'Technician Issue'), ('payment_issue', 'Payment Issue'), ('refund', 'Refund'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule'), ('pricing_issue', 'Pricing Issue'), ('missing_damaged', 'Missing / Damaged Item'), ('safety_issue', 'Safety Issue'), ('other', 'Other')], max_length=30),
        ),
    ]
