# Generated by Django 6.0.7 on 2026-08-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_care', '0004_alter_careagentprofile_care_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercareticket',
            name='category',
            field=models.CharField(choices=[('booking_issue', 'Booking Issue'), ('service_quality', 'Service Quality'), ('technician_issue', 'Technician Issue'), ('payment_issue', 'Payment Issue'), ('refund', 'Refund'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule'), ('pricing_issue', 'Pricing Issue'), ('missing_damaged', 'Missing / Damaged Item'), ('safety_issue', 'Safety Issue'), ('other', 'General Support')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(choices=[('booking_issue', 'Booking Issue'), ('service_quality', 'Service Quality'), ('technician_issue', 'Technician Issue'), ('payment_issue', 'Payment Issue'), ('refund', 'Refund'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule'), ('pricing_issue', 'Pricing Issue'), ('missing_damaged', 'Missing / Damaged Item'), ('safety_issue', 'Safety Issue'), ('other', 'General Support')], max_length=30),
        ),
    ]
