# Generated by Django 6.0.8 on 2026-08-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('customer_care', '0006_alter_customercareticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careagentprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='customercareticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company'),
        ),
    ]
