# Generated by Django 6.0.5 on 2026-07-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
