# Generated by Django 6.0.5 on 2026-07-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_alter_servicerequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cart_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
