# Generated by Django 6.0.5 on 2026-07-13 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0005_catalogcategory_servicerequest_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='catalogservice',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='servicefeedback',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RenameField(
            model_name='catalogcategory',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='employeeperformance',
            old_name='completion_rate',
            new_name='issue_resolution_rate',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='catalogservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='catalogservice',
            name='excludes',
        ),
        migrations.RemoveField(
            model_name='catalogservice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='catalogservice',
            name='includes',
        ),
        migrations.RemoveField(
            model_name='catalogservice',
            name='payment_policy',
        ),
        migrations.RemoveField(
            model_name='catalogservice',
            name='popular',
        ),
        migrations.RemoveField(
            model_name='catalogservice',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='catalogservice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='customer_satisfaction_score',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='feedback_count',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='jobs_completed_count',
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='total_jobs_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='total_jobs_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('collected', 'Collected'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogservice',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeejob',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash on Service'), ('ONLINE', 'Online Payment')], default='COD', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new_request', 'New Request'), ('waiting_for_payment', 'Waiting for Payment'), ('confirmed', 'Confirmed'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('awaiting_verification', 'Awaiting Verification'), ('verified', 'Verified'), ('feedback_pending', 'Feedback Pending'), ('feedback_received', 'Feedback Received'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('rework_requested', 'Rework Requested')], default='new_request', max_length=30),
        ),
    ]
