# Generated by Django 6.0.5 on 2026-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0006_payment_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='jobs_count_str',
            field=models.CharField(blank=True, default='10K+', max_length=20),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='rating',
            field=models.CharField(blank=True, default='4.8', max_length=10),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='excludes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='includes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
