# Generated by Django 6.0.5 on 2026-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0007_catalogcategory_image_catalogcategory_jobs_count_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeperformance',
            name='issue_resolution_rate',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='total_jobs_assigned',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='total_jobs_completed',
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='customer_satisfaction_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='feedback_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='jobs_completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
