# Generated by Django 6.0.5 on 2026-07-27 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0009_complaint_complaintattachment_complaintresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintattachment',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=15),
        ),
        migrations.AddField(
            model_name='complaint',
            name='refund_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_complaints', to='service_requests.refundrequest'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('COMPLAINT_VALID', 'Complaint Valid'), ('COMPLAINT_INVALID', 'Complaint Invalid'), ('CUSTOMER_ERROR', 'Customer Error'), ('TECHNICIAN_ERROR', 'Technician Error'), ('COMPANY_ERROR', 'Company Error')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rework_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_source_complaints', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaintattachment',
            name='attachment_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('INVOICE', 'Invoice')], default='IMAGE', max_length=15),
        ),
        migrations.AddField(
            model_name='complaintattachment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('POOR_SERVICE', 'Poor Service'), ('TECHNICIAN_LATE', 'Technician Late'), ('TECHNICIAN_BEHAVIOUR', 'Technician Behaviour'), ('INCOMPLETE_WORK', 'Incomplete Work'), ('WRONG_BILLING', 'Wrong Billing'), ('DAMAGED_PROPERTY', 'Damaged Property'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('WAITING_CUSTOMER', 'Waiting on Customer'), ('WAITING_TECHNICIAN', 'Waiting on Technician'), ('ADMIN_REVIEW', 'Admin Review'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='ComplaintMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_persona', models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='service_requests.complaint')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_complaint_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='service_requests.complaint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ComplaintResponse',
        ),
    ]
