# Generated by Django 6.0.5 on 2026-07-28 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0010_remove_complaintattachment_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reschedulerequest',
            old_name='original_scheduled_at',
            new_name='current_date',
        ),
        migrations.RenameField(
            model_name='reschedulerequest',
            old_name='requested_scheduled_at',
            new_name='new_date',
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='alternate_slots_suggested',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='current_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='new_time_slot',
            field=models.CharField(choices=[('09-10', '09:00 - 10:00'), ('10-11', '10:00 - 11:00'), ('11-12', '11:00 - 12:00'), ('14-15', '14:00 - 15:00'), ('15-16', '15:00 - 16:00')], default='09-10', max_length=20),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='proposed_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_reschedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='technician_response_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='reason',
            field=models.CharField(choices=[('schedule_conflict', 'Schedule Conflict'), ('emergency', 'Emergency'), ('weather_delay', 'Weather Delay'), ('technical_issue', 'Technical Issue'), ('customer_request', 'Customer Request'), ('other', 'Other')], default='schedule_conflict', max_length=50),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ADMIN_REVIEW', 'Admin Review'), ('TECHNICIAN_CONFIRMATION', 'Technician Confirmation'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CUSTOMER_NOTIFIED', 'Customer Notified')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='RescheduleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reschedules/attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_requests', to='service_requests.rescheduleattachment'),
        ),
    ]
