# Generated by Django 6.0.5 on 2026-07-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0012_refund_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.CharField(choices=[('POOR_QUALITY', 'Poor Quality'), ('SERVICE_NOT_COMPLETED', 'Service Not Completed'), ('CANCELLED_BY_PROVIDER', 'Cancelled By Provider'), ('OVERCHARGED', 'Overcharged'), ('OTHER', 'Other')], default='POOR_QUALITY', max_length=50),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='refund_type',
            field=models.CharField(choices=[('FULL', 'Full Refund'), ('PARTIAL', 'Partial Refund')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('INFO_REQUESTED', 'Information Requested'), ('APPROVED_FULL', 'Approved Full'), ('APPROVED_PARTIAL', 'Approved Partial'), ('REJECTED', 'Rejected'), ('SENT_TO_FINANCE', 'Sent to Finance'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30),
        ),
    ]
