# Generated by Django 6.0.5 on 2026-07-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0014_reschedule_extended_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedulerequest',
            name='admin_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='approved_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='customer_response',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='employee_rejection_reason',
            field=models.CharField(blank=True, choices=[('ALREADY_ASSIGNED', 'Already Assigned'), ('LEAVE', 'On Leave'), ('EMERGENCY', 'Personal Emergency'), ('OUTSIDE_WORKING_HOURS', 'Outside Working Hours'), ('DISTANCE_TOO_FAR', 'Distance Too Far'), ('PERSONAL_CONFLICT', 'Personal Conflict'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='employee_response',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('EMPLOYEE_UNAVAILABLE', 'Employee Unavailable'), ('OUTSIDE_WORKING_HOURS', 'Outside Working Hours'), ('SERVICE_AREA_CLOSED', 'Service Area Closed'), ('DUPLICATE_REQUEST', 'Duplicate Request'), ('INVALID_REQUEST', 'Invalid Request'), ('POLICY_VIOLATION', 'Policy Violation'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('PENDING_ADMIN_REVIEW', 'Pending Admin Review'), ('ADMIN_REVIEW', 'Admin Review'), ('AWAITING_EMPLOYEE_RESPONSE', 'Awaiting Employee Response'), ('AWAITING_EMPLOYEE_CONFIRMATION', 'Awaiting Employee Confirmation'), ('TECHNICIAN_CONFIRMATION', 'Technician Confirmation'), ('EMPLOYEE_CONFIRMED', 'Employee Confirmed'), ('APPROVED', 'Approved'), ('CUSTOMER_NOTIFIED', 'Customer Notified'), ('SLOT_SUGGESTED', 'Slot Suggested by Admin'), ('CUSTOMER_ACCEPTED_SUGGESTION', 'Customer Accepted Suggestion'), ('CANCELLED_SUGGESTION', 'Cancelled Suggestion'), ('REASSIGNMENT_NEEDED', 'Reassignment Needed'), ('RESCHEDULED', 'Rescheduled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='RescheduleStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_history_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='service_requests.reschedulerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleSuggestedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_slots', to='service_requests.reschedulerequest')),
            ],
            options={
                'ordering': ['date', 'time_slot'],
            },
        ),
    ]
