# Generated by Django 6.0.5 on 2026-08-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0015_reschedulerequest_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedulerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('PENDING_ADMIN_REVIEW', 'Pending Admin Review'), ('ADMIN_REVIEW', 'Under Admin Review'), ('ADMIN_APPROVED', 'Admin Approved'), ('EMPLOYEE_ASSIGNMENT_IN_PROGRESS', 'Employee Assignment in Progress'), ('EMPLOYEE_ASSIGNED', 'Employee Assigned'), ('AWAITING_EMPLOYEE_RESPONSE', 'Awaiting Employee Confirmation'), ('AWAITING_EMPLOYEE_CONFIRMATION', 'Awaiting Employee Confirmation'), ('TECHNICIAN_CONFIRMATION', 'Technician Confirmation'), ('EMPLOYEE_CONFIRMED', 'Employee Confirmed'), ('EMPLOYEE_ACCEPTED', 'Employee Accepted'), ('EMPLOYEE_REJECTED', 'Employee Rejected'), ('REASSIGNMENT_NEEDED', 'Reassignment Needed'), ('BOOKING_UPDATED', 'Booking Being Updated'), ('APPROVED', 'Approved'), ('CUSTOMER_NOTIFIED', 'Customer Notified'), ('SLOT_SUGGESTED', 'Slot Suggested by Admin'), ('CUSTOMER_ACCEPTED_SUGGESTION', 'Customer Accepted Suggestion'), ('CANCELLED_SUGGESTION', 'Cancelled Suggestion'), ('RESCHEDULED', 'Rescheduled Successfully'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=60),
        ),
    ]
