# Generated by Django 6.0.5 on 2026-08-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0009_work_extension_system'),
        ('service_requests', '0016_alter_reschedulerequest_status'),
    ]

    operations = [
    ]
