# Generated by Django 6.0.8 on 2026-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0017_merge_20260804_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new_request', 'New Request'), ('waiting_for_payment', 'Waiting for Payment'), ('confirmed', 'Confirmed'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('awaiting_verification', 'Awaiting Verification'), ('verified', 'Verified'), ('feedback_pending', 'Feedback Pending'), ('feedback_received', 'Feedback Received'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('rework_requested', 'Rework Requested'), ('follow_up_required', 'Follow-up Required')], default='new_request', max_length=30),
        ),
    ]
