# Generated by Django 5.2.17 on 2026-08-08 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('service_requests', '0019_repair_work_extension_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='drop_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='logistics_lane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='logistics.lane'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='logistics_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='logistics.servicetier'),
        ),
    ]
