# Generated by Django 6.0.8 on 2026-08-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0020_alter_servicerequest_payment_status_and_more'),
        ('service_requests', '0020_servicerequest_drop_address_and_more'),
    ]

    operations = [
    ]
