# Generated by Django 6.0.8 on 2026-08-12 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0026_catalogchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Amount (₹)'), ('percentage', 'Percentage (%)')], default='flat', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer_eligibility', models.CharField(default='All Customers', max_length=100)),
                ('order_type', models.CharField(default='Any Order', max_length=100)),
                ('service_eligibility', models.CharField(default='All Services', max_length=100)),
                ('min_booking', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usage_per_customer', models.IntegerField(default=1)),
                ('total_usage_limit', models.IntegerField(default=1000)),
                ('current_usage', models.IntegerField(default=0)),
                ('stacking', models.CharField(default='No', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Scheduled', 'Scheduled'), ('Expired', 'Expired'), ('Paused', 'Paused')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='catalogchangelog',
            new_name='service_req_entity__1965a7_idx',
            old_name='service_req_entity__idx',
        ),
    ]
