# Generated by Django 6.0.8 on 2026-08-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0027_rename_service_req_entity__idx_service_req_entity__1965a7_idx_and_more'),
        ('service_requests', '0028_servicerequest_coupon_and_more'),
    ]

    operations = [
    ]
