# Generated by Django 6.0.8 on 2026-08-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0029_merge_20260813_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='employeejob',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('received', 'Received'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('awaiting_parts', 'Awaiting Parts'), ('completed', 'Completed'), ('unable_to_complete', 'Unable To Complete'), ('rejected', 'Rejected')], default='assigned', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_request', 'New Request'), ('pending_payment', 'Pending Payment'), ('waiting_for_payment', 'Waiting for Payment'), ('confirmed', 'Confirmed'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('received', 'Received'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('awaiting_verification', 'Awaiting Verification'), ('verified', 'Verified'), ('feedback_pending', 'Feedback Pending'), ('feedback_received', 'Feedback Received'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('rework_requested', 'Rework Requested'), ('follow_up_required', 'Follow-up Required')], default='new_request', max_length=30),
        ),
    ]
