# Generated by Django 6.0.8 on 2026-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0029_merge_20260813_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='ready',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='reviews',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
