# Generated by Django 6.0.8 on 2026-08-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0030_add_view_details_fields_to_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='package',
            name='service',
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ManyToManyField(related_name='packages', to='service_requests.service'),
        ),
    ]
