# Generated by Django 6.0.7 on 2026-08-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0030_add_view_details_fields_to_package'),
        ('service_requests', '0031_reseed_painting_services_and_packages'),
    ]

    operations = [
    ]
