# Generated by Django 6.0.8 on 2026-08-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0030_servicerequest_latitude_servicerequest_longitude_and_more'),
        ('service_requests', '0032_merge_20260814_1225'),
    ]

    operations = [
    ]
