# Generated by Django 6.0.8 on 2026-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0033_merge_20260816_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['service__category__sort_order', 'service__name', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='package',
            name='button_text',
            field=models.CharField(blank=True, default='Add', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='customization',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
