# Generated by Django 6.0.7 on 2026-08-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0031_alter_package_options_remove_package_service_and_more'),
        ('service_requests', '0034_alter_package_options_package_button_text_and_more'),
    ]

    operations = [
    ]
