# Generated by Django 6.0.8 on 2026-08-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0036_revert_package_service_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['service__category__sort_order', 'service__name', 'sort_order', 'name']},
        ),
    ]
