# Generated by Django 6.0.8 on 2026-08-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0037_alter_package_options'),
    ]

    operations = [
    ]
