# Generated by Django on 2026-08-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0037_alter_package_options'),
    ]

    operations = [
        # 1. Remove obsolete workforce models if they exist
        migrations.DeleteModel(
            name='JobCompletionProof',
        ),
        migrations.DeleteModel(
            name='EmployeePerformance',
        ),
        migrations.DeleteModel(
            name='RefundInvestigationNote',
        ),
        migrations.DeleteModel(
            name='JobReschedule',
        ),

        # 2. Add workforce integration and snapshot fields to ServiceRequest
        migrations.AddField(
            model_name='servicerequest',
            name='workforce_job_id',
            field=models.CharField(blank=True, null=True, db_index=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='external_assignment_id',
            field=models.CharField(blank=True, null=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technician_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_collected_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='collection_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='collection_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),

        # 3. Remove FKs on ServiceRequest
        migrations.RemoveField(
            model_name='servicerequest',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='payment_collected_by',
        ),

        # 4. Update WorkExtension fields
        migrations.AddField(
            model_name='workextension',
            name='workforce_job_id',
            field=models.CharField(blank=True, null=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='workextension',
            name='reported_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RemoveField(
            model_name='workextension',
            name='job',
        ),
        migrations.RemoveField(
            model_name='workextension',
            name='reported_by',
        ),

        # 5. Update WorkExtensionItem fields
        migrations.RemoveField(
            model_name='workextensionitem',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='location',
        ),

        # 6. Update RescheduleRequest
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='proposed_technician',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='employee_response',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='employee_response_note',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='employee_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='employee_responded_at',
        ),

        # 7. Update RefundRequest
        migrations.RemoveField(
            model_name='refundrequest',
            name='assigned_employee',
        ),

        # 8. Update Complaint
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_employee',
        ),

        # 9. Delete EmployeeJob
        migrations.DeleteModel(
            name='EmployeeJob',
        ),
    ]
