# Generated by Django 6.0.8 on 2026-08-17 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0038_remove_workforce_models_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='technician_response_note',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('WAITING_CUSTOMER', 'Waiting on Customer'), ('ADMIN_REVIEW', 'Admin Review'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintmessage',
            name='sender_persona',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='info_requested_from',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='persona',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], default='CUSTOMER', max_length=10),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('SERVICE_UNAVAILABLE', 'Service Unavailable'), ('OUTSIDE_WORKING_HOURS', 'Outside Working Hours'), ('SERVICE_AREA_CLOSED', 'Service Area Closed'), ('DUPLICATE_REQUEST', 'Duplicate Request'), ('INVALID_REQUEST', 'Invalid Request'), ('POLICY_VIOLATION', 'Policy Violation'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('PENDING_ADMIN_REVIEW', 'Pending Admin Review'), ('ADMIN_REVIEW', 'Under Admin Review'), ('ADMIN_APPROVED', 'Admin Approved'), ('APPROVED', 'Approved'), ('CUSTOMER_NOTIFIED', 'Customer Notified'), ('SLOT_SUGGESTED', 'Slot Suggested by Admin'), ('CUSTOMER_ACCEPTED_SUGGESTION', 'Customer Accepted Suggestion'), ('CANCELLED_SUGGESTION', 'Cancelled Suggestion'), ('RESCHEDULED', 'Rescheduled Successfully'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=60),
        ),
        migrations.AlterField(
            model_name='workextension',
            name='workforce_job_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='JobReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField()),
                ('reason', models.CharField(choices=[('parts_unavailable', 'Parts Unavailable'), ('technician_unavailable', 'Technician Unavailable'), ('customer_requested', 'Customer Requested'), ('other', 'Other')], default='parts_unavailable', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('customer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delay_count', models.PositiveIntegerField(default=1)),
                ('support_callback_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reschedules', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
