# Generated by Django 6.0.8 on 2026-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0039_remove_reschedulerequest_technician_response_note_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='servicerequest',
                    name='otp_verified',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='servicerequest',
                    name='start_otp',
                    field=models.CharField(blank=True, default='', max_length=10),
                ),
                migrations.AddField(
                    model_name='servicerequest',
                    name='tracking_token',
                    field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
                ),
            ],
            database_operations=[
                migrations.AddField(
                    model_name='servicerequest',
                    name='tracking_token',
                    field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
                ),
                migrations.AddField(
                    model_name='servicerequest',
                    name='otp_verified',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='servicerequest',
                    name='start_otp',
                    field=models.CharField(blank=True, default='', max_length=10),
                ),
            ],
        ),
    ]
