# Generated by Django 6.0.8 on 2026-08-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0035_merge_20260817_1049'),
        ('service_requests', '0038_merge_20260817_1340'),
        ('service_requests', '0040_add_tracking_token'),
    ]

    operations = [
    ]
