# Generated by Django 6.0.8 on 2026-08-18 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('logistics', '0004_alter_servicetier_duration'),
        ('service_requests', '0041_merge_20260818_1500'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cancellation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('CHANGE_OF_PLANS', 'Change of plans / Booked by mistake'), ('EXPECTED_FASTER', 'Expected faster service / Partner too far'), ('WRONG_SERVICE', 'Selected wrong service, date, or address'), ('FOUND_ALTERNATIVE', 'Found alternative service / Solved myself'), ('PRICE_OR_PAYMENT', 'Price or payment issue'), ('OTHER', 'Other reason')], max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cancelled_at_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='cancelled_by_persona',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['company', 'status', 'created_at'], name='service_req_company_ff0409_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['company', 'payment_status', 'created_at'], name='service_req_company_bcb375_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer', 'created_at'], name='service_req_custome_f7d406_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['phone'], name='service_req_phone_6a6c4f_idx'),
        ),
    ]
