# Generated by Django 6.0.8 on 2026-08-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0042_servicerequest_cancellation_note_and_more'),
        ('service_requests', '0042_servicerequest_technician_last_seen_at_and_more'),
    ]

    operations = [
    ]
