# Generated by Django 6.0.8 on 2026-08-19 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('service_requests', '0043_merge_20260819_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='technician_last_seen_at',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='otp_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='otp_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, default='', max_length=100)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=200)),
                ('vendor_logo', models.CharField(blank=True, default='', max_length=500)),
                ('vendor_verified', models.BooleanField(default=False)),
                ('technician_id', models.CharField(blank=True, default='', max_length=100)),
                ('technician_name', models.CharField(blank=True, default='', max_length=200)),
                ('technician_photo', models.CharField(blank=True, default='', max_length=500)),
                ('technician_phone', models.CharField(blank=True, default='', max_length=30)),
                ('technician_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('technician_verified', models.BooleanField(default=False)),
                ('workforce_job_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('assignment_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='offered', max_length=20)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='service_requests.servicerequest')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_assignments', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='service_req_booking_c6df4b_idx'), models.Index(fields=['company', 'status'], name='service_req_company_9ce1e3_idx'), models.Index(fields=['workforce_job_id'], name='service_req_workfor_e8328c_idx'), models.Index(fields=['assignment_id'], name='service_req_assignm_efc857_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkforceWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('workforce_job_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('assignment_id', models.CharField(blank=True, default='', max_length=100)),
                ('booking_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('sequence', models.BigIntegerField(db_index=True, default=0)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_webhook_events', to='companies.company')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_id'], name='service_req_event_i_7d8f11_idx'), models.Index(fields=['booking_id', 'sequence'], name='service_req_booking_51cfa7_idx'), models.Index(fields=['workforce_job_id', 'sequence'], name='service_req_workfor_f56992_idx')],
            },
        ),
    ]
