# Generated by Django 6.0.8 on 2026-08-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0044_remove_servicerequest_technician_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_zone_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_zone_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
