# Generated by Django 6.0.8 on 2026-08-21 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0045_add_service_zone_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_request', 'New Request'), ('unassigned', 'Unassigned'), ('pending_payment', 'Pending Payment'), ('waiting_for_payment', 'Waiting for Payment'), ('confirmed', 'Confirmed'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('received', 'Received'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('proof_submitted', 'Proof Submitted'), ('completed', 'Completed'), ('awaiting_verification', 'Awaiting Verification'), ('verified', 'Verified'), ('feedback_pending', 'Feedback Pending'), ('feedback_received', 'Feedback Received'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('rework_requested', 'Rework Requested'), ('unable_to_complete', 'Unable to Complete'), ('follow_up_required', 'Follow-up Required')], default='new_request', max_length=30),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('service_request_id_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('collected', 'Collected'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=30)),
                ('method', models.CharField(default='ONLINE', max_length=20)),
                ('gateway', models.CharField(default='razorpay', max_length=50)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='service_req_custome_09edde_idx'), models.Index(fields=['customer_id_snapshot', 'created_at'], name='service_req_custome_e25c9a_idx'), models.Index(fields=['service_request', 'created_at'], name='service_req_service_07cfa0_idx'), models.Index(fields=['razorpay_order_id'], name='service_req_razorpa_55e41a_idx'), models.Index(fields=['razorpay_payment_id'], name='service_req_razorpa_3694d8_idx'), models.Index(fields=['status'], name='service_req_status_2d5bd1_idx')],
            },
        ),
    ]
