# Generated by Django 6.0.8 on 2026-08-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0045_add_service_zone_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST percentage (e.g. 18.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='package',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=29.0, help_text='Platform / Convenience Fee in INR (e.g. 29.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_request', 'New Request'), ('unassigned', 'Unassigned'), ('pending_payment', 'Pending Payment'), ('waiting_for_payment', 'Waiting for Payment'), ('confirmed', 'Confirmed'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('received', 'Received'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('proof_submitted', 'Proof Submitted'), ('completed', 'Completed'), ('awaiting_verification', 'Awaiting Verification'), ('verified', 'Verified'), ('feedback_pending', 'Feedback Pending'), ('feedback_received', 'Feedback Received'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('rework_requested', 'Rework Requested'), ('unable_to_complete', 'Unable to Complete'), ('follow_up_required', 'Follow-up Required')], default='new_request', max_length=30),
        ),
    ]
