# Generated by Django 5.0.14 on 2026-08-21 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0045_add_service_zone_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='quote_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('inspection', 'Inspection'), ('quoted_work', 'Quoted Work')], db_index=True, default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('new_request', 'New Request'), ('unassigned', 'Unassigned'), ('pending_payment', 'Pending Payment'), ('waiting_for_payment', 'Waiting for Payment'), ('confirmed', 'Confirmed'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned'), ('received', 'Received'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('proof_submitted', 'Proof Submitted'), ('completed', 'Completed'), ('awaiting_verification', 'Awaiting Verification'), ('verified', 'Verified'), ('feedback_pending', 'Feedback Pending'), ('feedback_received', 'Feedback Received'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('rework_requested', 'Rework Requested'), ('unable_to_complete', 'Unable to Complete'), ('follow_up_required', 'Follow-up Required')], default='new_request', max_length=30),
        ),
    ]
