# Generated by Django 6.0.8 on 2026-08-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0046_alter_servicerequest_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, help_text='Permanent Customer ID snapshot (e.g. CUS0006)', max_length=30, null=True, verbose_name='Customer ID'),
        ),
    ]
