# Generated by Django 6.0.8 on 2026-08-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0046_package_gst_rate_package_platform_fee_and_more'),
        ('service_requests', '0049_convert_legacy_sr_ids'),
    ]

    operations = [
    ]
