# Generated by Django 5.0.14 on 2026-08-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0046_package_gst_rate_package_platform_fee_and_more'),
        ('service_requests', '0046_servicerequest_parent_request_and_more'),
        ('service_requests', '0049_convert_legacy_sr_ids'),
    ]

    operations = [
    ]
