# Generated by Django 6.0.8 on 2026-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0050_merge_20260824_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='parent_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='quote_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_kind',
            field=models.CharField(blank=True, default='DIRECT', max_length=30),
        ),
    ]
