# Generated by Django 5.0.14 on 2026-08-24 08:39

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('logistics', '0004_alter_servicetier_duration'),
        ('service_requests', '0050_merge_20260824_1409'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='sr_email_upper_idx'),
        ),
    ]
