# Generated by Django 6.0.8 on 2026-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0050_merge_20260824_1041'),
    ]

    operations = [
    ]
