# Generated by Django 6.0.8 on 2026-08-25 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0052_merge_20260825_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='quote_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('inspection', 'Inspection'), ('quoted_work', 'Quoted Work')], db_index=True, default='standard', max_length=30),
        ),
    ]
