# Generated by Django 6.0.8 on 2026-08-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0046_servicerequest_parent_request_and_more'),
        ('service_requests', '0051_servicerequest_parent_request_id_and_more'),
    ]

    operations = [
    ]
