# Generated by Django 6.0.8 on 2026-08-25 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0051_servicerequest_parent_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='parent_request_id',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='service_requests.servicerequest'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='quote_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('inspection', 'Inspection'), ('quoted_work', 'Quoted Work')], db_index=True, default='standard', max_length=30),
        ),
    ]
