# Generated by Django 6.0.8 on 2026-08-29 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('service_requests', '0053_unconstrain_legacy_technician_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_service', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('classification', models.CharField(default='both', max_length=50)),
                ('warranty', models.CharField(blank=True, default='', max_length=100)),
                ('inclusions', models.TextField(blank=True, default='')),
                ('exclusions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('has_slabs', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaintingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('quote_version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_ADMIN_REVIEW', 'Pending Admin Review'), ('SENT_TO_CUSTOMER', 'Sent to Customer'), ('VIEWED', 'Viewed'), ('APPROVED', 'Approved'), ('REQUESTED_CHANGES', 'Requested Changes'), ('SUPERSEDED', 'Superseded'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=50)),
                ('property_type', models.CharField(blank=True, default='', max_length=100)),
                ('total_paintable_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, default='', max_length=200)),
                ('customer_decision_token', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('warranty_card', models.FileField(blank=True, null=True, upload_to='quotes/warranties/')),
                ('warranty_certificate', models.FileField(blank=True, null=True, upload_to='quotes/warranties/')),
                ('completion_certificate', models.FileField(blank=True, null=True, upload_to='quotes/warranties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_painting_quotes', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_quotes', to='service_requests.servicerequest')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='painting_quotes', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='PaintingMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculated_area', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('final_area', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='service_requests.paintingquote')),
            ],
        ),
        migrations.CreateModel(
            name='PaintingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=150)),
                ('finish', models.CharField(max_length=100)),
                ('shade', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='service_requests.paintingquote')),
            ],
        ),
        migrations.CreateModel(
            name='PaintingQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('classification', models.CharField(default='both', max_length=50)),
                ('included', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('slab_key', models.CharField(blank=True, default='', max_length=100)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service_requests.paintingquote')),
                ('rate_card_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_requests.paintingratecard')),
            ],
        ),
        migrations.CreateModel(
            name='PaintingRateCardSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_key', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='service_requests.paintingratecard')),
            ],
        ),
        migrations.CreateModel(
            name='QuotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='quotes/photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service_requests.paintingquote')),
            ],
        ),
    ]
