# Generated by Django 6.0.8 on 2026-08-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0054_paintingratecard_paintingquote_paintingmeasurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingratecard',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paintingratecard',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_mode',
            field=models.CharField(choices=[('FIXED', 'Fixed Price'), ('QUOTATION', 'Quotation Required')], default='FIXED', max_length=20),
        ),
    ]
