# Generated by Django 6.0.8 on 2026-09-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0053_servicerequest_accepted_at_and_more'),
        ('service_requests', '0055_paintingratecard_comments_and_more'),
    ]

    operations = [
    ]
