# Generated by Django 6.0.8 on 2026-09-01 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0056_merge_20260901_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogchangelog',
            name='entity_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('SERVICE', 'Service'), ('PACKAGE', 'Package'), ('ADDON', 'Add-on'), ('RECIPE', 'Recipe')], max_length=20),
        ),
        migrations.CreateModel(
            name='VegetableRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('short_description', models.TextField(blank=True)),
                ('prep_time_minutes', models.PositiveIntegerField(default=10)),
                ('cook_time_minutes', models.PositiveIntegerField(default=15)),
                ('total_time_minutes', models.PositiveIntegerField(default=25)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20)),
                ('servings', models.PositiveIntegerField(default=2, help_text='Base recipe serving size')),
                ('calories', models.PositiveIntegerField(default=120, help_text='Calories (kcal) per serving')),
                ('protein', models.CharField(blank=True, default='3g', help_text='Protein per serving', max_length=50)),
                ('carbohydrates', models.CharField(blank=True, default='15g', help_text='Carbohydrates per serving', max_length=50)),
                ('fat', models.CharField(blank=True, default='2g', help_text='Fat per serving', max_length=50)),
                ('fiber', models.CharField(blank=True, default='4g', help_text='Dietary Fiber per serving', max_length=50)),
                ('health_benefits', models.JSONField(blank=True, default=list, help_text="e.g. ['Contains lycopene', 'Provides vitamin C', 'Source of dietary fiber']")),
                ('health_tips', models.JSONField(blank=True, default=list, help_text="e.g. ['Cooking tip: ...', 'Storage tip: ...', 'Usage tip: ...']")),
                ('instructions', models.JSONField(blank=True, default=list, help_text="List of cooking steps: ['Step 1...', 'Step 2...']")),
                ('tags', models.JSONField(blank=True, default=list, help_text="e.g. ['Quick Recipes', 'Easy Recipes', 'Low Calorie', 'High Fiber', 'Popular Recipes']")),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='service_requests.package')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ingredient name e.g. 'Tomato', 'Garlic', 'Mustard seeds'", max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Base quantity for the base serving count', max_digits=8)),
                ('unit', models.CharField(default='pieces', help_text='Unit e.g. pieces, g, kg, tsp, tbsp, cup, cloves', max_length=50)),
                ('notes', models.CharField(blank=True, default='', help_text="e.g. 'Finely chopped', 'Crushed'", max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(blank=True, help_text='Referenced vegetable package in our catalog, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='service_requests.package')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='service_requests.vegetablerecipe')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
