# Generated by Django 6.0.8 on 2026-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0056_merge_20260831_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='saved_address_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_location_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
