# Generated by Django 6.0.8 on 2026-09-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0057_alter_catalogchangelog_entity_type_vegetablerecipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_catalog_vegetable',
            field=models.BooleanField(default=False, help_text='True if linked to a vegetable sold by Calservices'),
        ),
        migrations.AlterField(
            model_name='catalogchangelog',
            name='entity_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('SERVICE', 'Service'), ('PACKAGE', 'Package'), ('ADDON', 'Add-on'), ('RECIPE', 'Recipe'), ('RECOMMENDATION', 'Recommendation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(help_text='Ingredient name e.g. Tomato, Salt, Mustard seeds', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='e.g. Finely chopped, Diced', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Referenced Calservices vegetable package if this is a catalog vegetable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='service_requests.package'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(default='pieces', help_text='e.g. pieces, g, kg, tsp, tbsp, cup, cloves', max_length=50),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='carbohydrates',
            field=models.CharField(blank=True, default='15g', max_length=50),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='fat',
            field=models.CharField(blank=True, default='2g', max_length=50),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='fiber',
            field=models.CharField(blank=True, default='4g', max_length=50),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='health_benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of informational health points'),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='health_tips',
            field=models.JSONField(blank=True, default=list, help_text='List of washing, cooking, or storage tips'),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of step-by-step cooking instructions'),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='package',
            field=models.ForeignKey(help_text='Primary vegetable product in Calservices catalog', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='service_requests.package'),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='protein',
            field=models.CharField(blank=True, default='3g', max_length=50),
        ),
        migrations.AlterField(
            model_name='vegetablerecipe',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags like Quick Recipes, Low Calorie, etc.'),
        ),
        migrations.CreateModel(
            name='VegetableRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('GOES_WELL_WITH', 'Goes Well With'), ('RECIPE_BASED', 'Recipe Based'), ('YOU_MAY_ALSO_LIKE', 'You May Also Like')], default='GOES_WELL_WITH', max_length=30)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Higher priority items appear first')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_product', models.ForeignKey(help_text='Vegetable recommended with the primary vegetable', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_in', to='service_requests.package')),
                ('source_product', models.ForeignKey(help_text='Primary vegetable', on_delete=django.db.models.deletion.CASCADE, related_name='source_recommendations', to='service_requests.package')),
            ],
            options={
                'ordering': ['-priority', 'display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('source_product', 'recommended_product', 'recommendation_type'), name='unique_vegetable_recommendation')],
            },
        ),
    ]
