# Generated by Django 6.0.8 on 2026-09-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_default_daily_quantity_grams_and_more'),
        ('service_requests', '0059_unconstrain_legacy_columns'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceaddon',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serviceaddon',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='serviceaddon',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['package__name', 'sort_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='addon',
            name='addon_type',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='category_slug',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='is_quantity_allowed',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='service',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='vendor_availability',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='proof_images',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='technician_notes',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='package',
            name='stock_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vegetable_package', to='inventory.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='BookingAddOn',
        ),
        migrations.DeleteModel(
            name='ServiceAddOn',
        ),
    ]
