# Generated by Django 6.0.8 on 2026-09-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0058_alter_addon_options_addon_addon_type_and_more'),
        ('service_requests', '0058_recipeingredient_is_catalog_vegetable_and_more'),
        ('service_requests', '0061_x09_booking_message'),
    ]

    operations = [
    ]
