# Generated by Django 6.0.8 on 2026-09-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0059_unconstrain_legacy_columns'),
        ('service_requests', '0060_ac_estimation_system'),
        ('service_requests', '0062_merge_20260902_1401'),
    ]

    operations = [
    ]
