# Hand-verified auto-generated migration (2026-09-04). Unlike most of the
# other hand-written migrations in this remediation pass, this one WAS
# generated by a real `manage.py makemigrations --check` / `makemigrations`
# run, against a real local Django install loaded with this repo's actual
# settings module and .env configuration (see
# GT_PORTER_PARITY_AUDIT_2026-09-04.md and the project memory note on this
# for how -- the sandbox this was built in cannot reach the live DB, but
# `makemigrations` does not need a live DB connection to compare the
# current models.py against the recorded migration graph).
#
# What this captures: service_requests/models.py already dropped several
# fields/models that migration 0063 and earlier still believed existed.
# Traced every removed field/model to confirm nothing in either the
# Customer or vendor backend still references it (BookingAddOn,
# ServiceAddOn, Addon.addon_type/base_price/category_slug/
# is_quantity_allowed/max_quantity/service/unit/vendor_availability,
# Service.pricing_mode, WorkExtensionItem.addon/proof_images/
# technician_notes/unit/unit_price -- all zero references outside
# migrations in both apps' codebases). The ServiceRequest.technician_*
# fields being removed here (technician FK, technician_accuracy,
# technician_arrived_at, technician_heading, technician_location_updated_at,
# technician_speed, plus accepted_at/completed_at/started_at/
# saved_address_id/service_location_snapshot) are likewise unreferenced;
# live tracking now runs through the separate technician_latitude/
# technician_longitude/technician_location_name snapshot fields already on
# this model (see consumers.py, technician_views.py), which this migration
# does not touch. This reads as a completed refactor (flat Addon pricing
# and an FK-based technician link, both replaced elsewhere in the codebase
# -- the quotation/estimation-item system, and a technician-snapshot
# pattern matching the same one used for HS-E-01) that never had its
# migration generated -- not an accidental loss caused by this session.
#
# NOT SAFE TO APPLY BLINDLY: this DROPS the BookingAddOn and ServiceAddOn
# tables and the columns listed above. Before running `migrate` against
# any real database, confirm (a) BookingAddOn/ServiceAddOn have no rows
# you still need, and (b) none of the removed ServiceRequest/WorkExtension
# columns hold data some other consumer (a report, an export, the vendor
# app) still reads. This migration was generated but has NOT been applied
# anywhere -- there was no live DB connection available to apply it from.
#
# ONE OPERATION WAS DELIBERATELY LEFT OUT of what --noinput auto-generated:
# an AlterField on Addon.package, changing it from the nullable/SET_NULL
# FK recorded in migration 0058 to a non-nullable/CASCADE FK matching the
# current model. --noinput generated that AlterField with no default for
# existing NULL package_id rows (Django reported "must be corrected"),
# which will fail outright the moment it runs against any database that
# has an Addon row with package_id IS NULL, and there is no way to know
# from here whether the live DB has any. Resolve that separately, once
# someone can check `SELECT count(*) FROM service_requests_addon WHERE
# package_id IS NULL` against the real database (or supply a real
# backfill/default), then add the AlterField back (or run makemigrations
# again for just that field) as its own migration. Addon.package in
# models.py currently still declares no null=True, so `manage.py
# makemigrations --check` will keep reporting this one field as pending
# until that follow-up migration exists.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0063_merge_20260904_1457'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceaddon',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serviceaddon',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='serviceaddon',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['package__name', 'sort_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='addon',
            name='addon_type',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='category_slug',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='is_quantity_allowed',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='service',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='vendor_availability',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pricing_mode',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='saved_address_id',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_location_snapshot',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='technician_accuracy',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='technician_arrived_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='technician_heading',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='technician_location_updated_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='technician_speed',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='proof_images',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='technician_notes',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='workextensionitem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='catalogchangelog',
            name='entity_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('SERVICE', 'Service'), ('PACKAGE', 'Package'), ('ADDON', 'Add-on')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('collected', 'Collected'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cash_pending', 'Cash Collection Pending')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('collected', 'Collected'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cash_pending', 'Cash Collection Pending')], default='pending', max_length=30),
        ),
        migrations.DeleteModel(
            name='BookingAddOn',
        ),
        migrations.DeleteModel(
            name='ServiceAddOn',
        ),
    ]
