# Hand-verified auto-generated migration (2026-09-04). Generated by a real
# `manage.py makemigrations` run against a real local Django install loaded
# with this repo's actual settings module and .env configuration (see
# GT_PORTER_PARITY_AUDIT_2026-09-04.md / project memory for how -- this
# sandbox has no live DB access, but makemigrations only needs to compare
# model state to the migration graph, not the live schema).
#
# What this captures: adds drop_latitude/drop_longitude to ServiceRequest
# (nullable DecimalField(9,6), same shape as the existing latitude/
# longitude columns). Purely additive -- no data loss, safe to apply to
# any existing database. See the field comment in models.py for why: the
# common single-pickup/single-drop logistics booking had a free-text
# drop_address but no drop-side coordinate anywhere, which blocked (a) a
# fully leg-aware live-tracking destination for bookings without TripStop
# rows (GT-D-02's residual gap), and (b) any real distance-based fare
# calculation (GT-B-01) -- distance needs two real coordinates.
#
# ONE OPERATION WAS AGAIN DELIBERATELY LEFT OUT of what --noinput
# auto-generated, for the same reason as migration 0064: an AlterField on
# Addon.package (nullable/SET_NULL -> non-nullable/CASCADE). --noinput
# still has no default for existing NULL package_id rows and this remains
# unresolved from 0064 -- see that migration's header. Still needs someone
# with real DB access to run `SELECT count(*) FROM
# service_requests_addon WHERE package_id IS NULL` before that field can
# be safely tightened. `manage.py makemigrations --check` will keep
# reporting this one field as pending until that follow-up migration
# exists; that's expected, not an oversight here either.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0064_gt_x04_drop_legacy_addon_and_technician_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='drop_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='drop_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
