# Generated by Django 6.0.8 on 2026-09-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0064_alter_serviceaddon_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='custom_packs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='package',
            name='customization',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='catalogchangelog',
            name='entity_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('SERVICE', 'Service'), ('PACKAGE', 'Package'), ('ADDON', 'Add-on')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('collected', 'Collected'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cash_pending', 'Cash Collection Pending')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('collected', 'Collected'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cash_pending', 'Cash Collection Pending')], default='pending', max_length=30),
        ),
    ]
