# Hand-verified auto-generated migration (2026-09-04). Generated by a real
# `manage.py makemigrations` run against a real local Django install (see
# migration 0064's header for the full explanation of that setup).
#
# Adds ServiceRequest.fare_breakdown: the itemised, server-computed fare
# quote (GT-B-01), stored as JSON at booking time. Purely additive, with a
# dict default, so it is safe to apply to any existing database and every
# existing row simply gets {}.
#
# ONE OPERATION WAS AGAIN DELIBERATELY LEFT OUT, for the third time and
# the same reason as migrations 0064 and 0065: an AlterField on
# Addon.package (nullable/SET_NULL -> non-nullable/CASCADE). --noinput
# still reports "Field 'package' on model 'addon' given a default of NOT
# PROVIDED and must be corrected", and it will fail against any database
# holding an Addon row with package_id IS NULL. It needs someone with real
# DB access to run `SELECT count(*) FROM service_requests_addon WHERE
# package_id IS NULL` and then either backfill or relax the model. Until
# that happens `makemigrations --check` keeps reporting it as pending;
# that is expected, not an oversight here.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0065_servicerequest_drop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='fare_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
