# Hand-verified auto-generated migration (2026-09-04). Generated by a real
# `manage.py makemigrations` run against a real local Django install (see
# migration 0064's header for that setup).
#
# GT-D-01, proof of delivery + per-stop progress:
#   - TripStop.arrived_at / completed_at -- until now a stop was a static
#     address row that nothing ever advanced, so "which stop is the driver
#     at" did not exist as a concept anywhere in the platform.
#   - DeliveryProof -- there was no proof-of-delivery record of any kind.
#     The vendor app's job.completion_proof_submitted webhook existed but
#     only appended free text to ServiceRequest.description: no photo, no
#     signature, no recipient identity, no link to a stop.
#
# Purely additive: two nullable columns and one new table. Nothing is
# dropped or tightened, so this is safe to apply to any existing database
# and every existing row is unaffected.
#
# ONE OPERATION WAS AGAIN DELIBERATELY LEFT OUT -- the fourth time, same
# reason as 0064/0065/0066: the AlterField on Addon.package
# (nullable/SET_NULL -> non-nullable/CASCADE) still has no default for
# existing NULL package_id rows and would fail against any database that
# has one. It needs a real-DB `SELECT count(*) FROM service_requests_addon
# WHERE package_id IS NULL` first. `makemigrations --check` keeps
# reporting it as pending until then; that is expected.

# Generated by Django 5.2.17 on 2026-09-04 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0066_servicerequest_fare_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('PHOTO', 'Photo of delivered goods'), ('SIGNATURE', 'Recipient signature'), ('RECIPIENT_NAME', 'Recipient name captured'), ('OTP', 'Delivery OTP verified'), ('NOTE', 'Driver note')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('captured_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('captured_by_workforce_id', models.CharField(blank=True, default='', max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='service_requests.servicerequest')),
                ('stop', models.ForeignKey(blank=True, help_text='Which stop this proves. Null for a single-drop booking with no TripStop rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_proofs', to='service_requests.tripstop')),
            ],
            options={
                'db_table': 'service_requests_delivery_proof',
                'ordering': ['booking', 'captured_at', 'id'],
                'indexes': [models.Index(fields=['booking', 'proof_type'], name='sr_delivery_proof_bk_ty_idx')],
            },
        ),
    ]
