# Hand-verified auto-generated migration (2026-09-04). Generated by a real
# `manage.py makemigrations` run against a real local Django install (see
# migration 0064's header for that setup).
#
# GT-C-01: adds the FareReconciliation table -- the estimated-vs-final
# fare record written at job completion, with each adjustment itemised
# (distance variance, extra stops actually completed, customer-approved
# extra work, minimum-fare floor). Purely additive: one new table, no
# existing column touched, safe to apply to any existing database.
#
# ONE OPERATION WAS AGAIN DELIBERATELY LEFT OUT -- the fifth time, same
# reason as 0064/0065/0066/0067: the AlterField on Addon.package
# (nullable/SET_NULL -> non-nullable/CASCADE) has no default for existing
# NULL package_id rows and would fail against any database holding one.
# It needs a real-DB `SELECT count(*) FROM service_requests_addon WHERE
# package_id IS NULL` first. Until that is resolved `makemigrations
# --check` keeps reporting it as pending; that is expected, not an
# oversight in this migration.

# Generated by Django 5.2.17 on 2026-09-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0067_tripstop_arrived_at_tripstop_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_breakdown', models.JSONField(blank=True, default=dict)),
                ('final_breakdown', models.JSONField(blank=True, default=dict)),
                ('adjustments', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fare_reconciliation', to='service_requests.servicerequest')),
            ],
            options={
                'db_table': 'service_requests_fare_reconciliation',
                'ordering': ['-created_at'],
            },
        ),
    ]
