# Generated by Django 6.0.8 on 2026-09-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0072_provision_assigned_employee_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='logistics_leg',
            field=models.CharField(blank=True, choices=[('EN_ROUTE_PICKUP', 'En Route to Pickup'), ('LOADING', 'Loading'), ('EN_ROUTE_DROP', 'En Route to Drop'), ('UNLOADING', 'Unloading'), ('DELIVERED', 'Delivered'), ('ASSIGNED', 'Assigned'), ('TEAM_EN_ROUTE', 'Team En Route'), ('ARRIVED_PICKUP', 'Arrived at Pickup'), ('PACKING', 'Packing'), ('DISMANTLING', 'Dismantling'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_DROP', 'Arrived at Drop'), ('REASSEMBLY', 'Reassembly'), ('UNPACKING', 'Unpacking'), ('COMPLETED', 'Completed')], default='', max_length=20),
        ),
    ]
