# Generated by Django 6.0.8 on 2026-09-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0064_repair_0058_live_db_drift'),
        ('service_requests', '0072_provision_assigned_employee_column'),
    ]

    operations = [
    ]
