# Generated by Django 6.0.8 on 2026-09-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0064_alter_serviceaddon_unique_together_and_more'),
        ('service_requests', '0073_merge_20260908_1402'),
    ]

    operations = [
    ]
