# Generated by Django 6.0.8 on 2026-09-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0065_remove_service_pricing_mode_and_more'),
        ('service_requests', '0074_merge_20260909_1248'),
    ]

    operations = [
    ]
