# Generated by Django 6.0.8 on 2026-09-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0059_unconstrain_legacy_columns'),
        ('service_requests', '0075_merge_20260909_1634'),
    ]

    operations = [
    ]
