# Generated by Django 6.0.8 on 2026-09-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0075_merge_20260909_1634'),
        ('service_requests', '0083_gt_relink_and_prune_orphan_tiers'),
    ]

    operations = [
    ]
