# Generated by Django 6.0.8 on 2026-09-11 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0076_merge_20260910_1512'),
        ('service_requests', '0084_merge_20260911_0925'),
    ]

    operations = [
    ]
