# Generated by Django 6.0.8 on 2026-09-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0073_alter_servicerequest_logistics_leg'),
        ('service_requests', '0085_merge_20260911_0935'),
    ]

    operations = [
    ]
