# Generated by Django 5.2.17 on 2026-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0086_alter_addon_package'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicerequest',
            name='unique_customer_idempotency_key',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='service_req_job_typ_6bd73d_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='service_req_job_typ_4f9cb8_idx',
        ),
        migrations.RenameIndex(
            model_name='vendorcapabilityrequest',
            new_name='service_req_vendor__91bc67_idx',
            old_name='vcr_vendor_status_idx',
        ),
        migrations.AlterField(
            model_name='catalogchangelog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('STATUS_CHANGE', 'Status Changed'), ('DELETE', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogchangelog',
            name='entity_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('SERVICE', 'Service'), ('PACKAGE', 'Package'), ('ADDON', 'Add-on'), ('SERVICE_TIER', 'Goods & Transport Tier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='logistics_leg',
            field=models.CharField(blank=True, choices=[('EN_ROUTE_PICKUP', 'En Route to Pickup'), ('LOADING', 'Loading'), ('EN_ROUTE_DROP', 'En Route to Drop'), ('UNLOADING', 'Unloading'), ('DELIVERED', 'Delivered'), ('ASSIGNED', 'Assigned'), ('TEAM_EN_ROUTE', 'Team En Route'), ('ARRIVED_PICKUP', 'Arrived at Pickup'), ('PACKING', 'Packing'), ('DISMANTLING', 'Dismantling'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_DROP', 'Arrived at Drop'), ('REASSEMBLY', 'Reassembly'), ('UNPACKING', 'Unpacking'), ('COMPLETED', 'Completed')], default='', max_length=20),
        ),
    ]
