# Generated by Django 6.0.8 on 2026-09-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0086_merge_20260916_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogchangelog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('STATUS_CHANGE', 'Status Changed'), ('DELETE', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogchangelog',
            name='entity_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('SERVICE', 'Service'), ('PACKAGE', 'Package'), ('ADDON', 'Add-on'), ('SERVICE_TIER', 'Goods & Transport Tier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('CHANGE_OF_PLANS', 'Change of plans / Booked by mistake'), ('EXPECTED_FASTER', 'Expected faster service / Partner too far'), ('WRONG_SERVICE', 'Selected wrong service, date, or address'), ('FOUND_ALTERNATIVE', 'Found alternative service / Solved myself'), ('PRICE_OR_PAYMENT', 'Price or payment issue'), ('SEARCH_EXPIRED', 'Search window expired (no delivery partner found within 10 minutes)'), ('OTHER', 'Other reason')], max_length=50),
        ),
    ]
