# Generated by Django 6.0.8 on 2026-09-18 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('logistics', '0014_merge_20260916_1548'),
        ('service_requests', '0087_alter_catalogchangelog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='dispatch_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of dispatch attempts'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='dispatch_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('PENDING_RETRY', 'Pending Retry'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current dispatch state to external workforce system', max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='last_dispatch_error',
            field=models.TextField(blank=True, default='', help_text='Last recorded dispatch error message'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='last_dispatched_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of latest dispatch attempt', null=True),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['dispatch_status', 'created_at'], name='service_req_disp_stat_idx'),
        ),
    ]
