# Generated by Django 6.0.8 on 2026-09-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0086_servicerequest_delay_fields'),
        ('service_requests', '0087_alter_catalogchangelog_action_and_more'),
    ]

    operations = [
    ]
