# Generated by Django 6.0.8 on 2026-09-21 06:25

from django.db import migrations, models


def add_catalog_service_id_if_missing(apps, schema_editor):
    table_name = "service_requests_servicerequest"
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "postgresql":
            cursor.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = %s AND column_name = 'catalog_service_id';",
                [table_name],
            )
            exists = cursor.fetchone() is not None
            if not exists:
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN catalog_service_id varchar(100) DEFAULT '';")
        elif schema_editor.connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info({table_name});")
            columns = [col[1] for col in cursor.fetchall()]
            if "catalog_service_id" not in columns:
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN catalog_service_id varchar(100) DEFAULT '';")
        else:
            try:
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN catalog_service_id varchar(100) DEFAULT '';")
            except Exception:
                pass


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0088_servicerequest_dispatch_attempts_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='servicerequest',
                    name='catalog_service_id',
                    field=models.CharField(blank=True, db_index=True, default='', help_text='Catalog service ID or package slug', max_length=100),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_catalog_service_id_if_missing,
                    noop_reverse,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_kind',
            field=models.CharField(choices=[('standard', 'Standard'), ('inspection', 'Inspection'), ('quoted_work', 'Quoted Work'), ('ESTIMATION', 'Estimation / Site Consultation'), ('DIRECT', 'Direct Standard Job'), ('WORK', 'Actual Work Execution Job')], db_index=True, default='standard', max_length=50),
        ),
    ]
