# Generated by Django 6.0.8 on 2026-09-23 12:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


import re


def backfill_package_variants(apps, schema_editor):
    Package = apps.get_model("service_requests", "Package")
    PackageVariant = apps.get_model("service_requests", "PackageVariant")
    Vegetable = apps.get_model("inventory", "Vegetable")

    packages = Package.objects.filter(
        models.Q(stock_item__isnull=False) | models.Q(vegetable_stock__isnull=False) | models.Q(service__slug="vegetables")
    )

    for pkg in packages:
        if PackageVariant.objects.filter(package=pkg).exists():
            continue

        linked_veg = getattr(pkg, "stock_item", None) or getattr(pkg, "vegetable_stock", None)
        if linked_veg is None:
            linked_veg = Vegetable.objects.filter(package=pkg).first()

        dur_str = (pkg.duration or "").strip()
        val = Decimal("1.00")
        unit = "kg"
        unit_basis = "WEIGHT"

        if linked_veg:
            unit = linked_veg.unit or "kg"
            unit_basis = getattr(linked_veg, "unit_basis", "WEIGHT") or "WEIGHT"

        if dur_str:
            match = re.match(r"^([\d.]+)\s*([a-zA-Z]+)?", dur_str)
            if match:
                try:
                    val = Decimal(match.group(1))
                except Exception:
                    val = Decimal("1.00")
                if match.group(2):
                    parsed_u = match.group(2).lower()
                    unit = parsed_u
                    if parsed_u in ["pcs", "piece", "pieces", "bunch", "bunches", "packet", "packets", "dozen", "dozens"]:
                        unit_basis = "COUNT"
                    else:
                        unit_basis = "WEIGHT"

        variant_name = dur_str if dur_str else f"{val:g} {unit}".strip()
        selling_price = pkg.base_price or Decimal("0.00")
        mrp_price = pkg.offer_price if (pkg.offer_price and pkg.offer_price > selling_price) else None

        PackageVariant.objects.create(
            package=pkg,
            vegetable=linked_veg,
            name=variant_name,
            pack_value=val,
            unit=unit,
            unit_basis=unit_basis,
            base_price=selling_price,
            mrp=mrp_price,
            sku=getattr(linked_veg, "sku", "") or None,
            is_default=True,
            is_active=True,
            sort_order=0,
            status="APPROVED",
            source="DIRECT",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_vegetablecategory_unit_basis_and_more'),
        ('service_requests', '0088_repoint_package_stock_item_to_vegetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('pack_value', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('unit_basis', models.CharField(choices=[('WEIGHT', 'Weight'), ('COUNT', 'Count')], default='WEIGHT', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', max_length=20)),
                ('source', models.CharField(choices=[('DIRECT', 'Direct'), ('REQUEST', 'Request')], db_index=True, default='DIRECT', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_resubmission', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='service_requests.package')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_package_variants', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_package_variants', to=settings.AUTH_USER_MODEL)),
                ('vegetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.vegetable')),
            ],
            options={
                'ordering': ['sort_order', 'pack_value', 'id'],
            },
        ),
        migrations.RunPython(backfill_package_variants, migrations.RunPython.noop),
    ]
