# Generated by Django 6.0.8 on 2026-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0089_repair_eventoutbox_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACRepairRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('installation', 'Installation / Re-installation'), ('electrical', 'Electrical Parts'), ('minor', 'Minor Parts'), ('gas_refrigeration', 'Gas / Refrigeration Parts'), ('fans_motors', 'Fans / Motors'), ('other_parts', 'Other Parts'), ('adjustment_basic', 'Adjustment / Basic Services')], db_index=True, max_length=50)),
                ('category_name', models.CharField(blank=True, default='', max_length=100)),
                ('item_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AC Repair Rate Card Item',
                'verbose_name_plural': 'AC Repair Rate Card Items',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='service_req_categor_2f1b09_idx'), models.Index(fields=['item_code'], name='service_req_item_co_4b5ffd_idx')],
            },
        ),
    ]
