# Generated by Django 6.0.8 on 2026-09-21 07:04

from django.db import migrations, models


def add_or_fix_catalog_mapping_status(apps, schema_editor):
    table_name = "service_requests_servicerequest"
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "postgresql":
            cursor.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = %s AND column_name = 'catalog_mapping_status';",
                [table_name],
            )
            exists = cursor.fetchone() is not None
            if not exists:
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN catalog_mapping_status varchar(50) DEFAULT 'UNMAPPED';")
            else:
                cursor.execute(f"ALTER TABLE {table_name} ALTER COLUMN catalog_mapping_status SET DEFAULT 'UNMAPPED', ALTER COLUMN catalog_mapping_status DROP NOT NULL;")
        elif schema_editor.connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info({table_name});")
            columns = [col[1] for col in cursor.fetchall()]
            if "catalog_mapping_status" not in columns:
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN catalog_mapping_status varchar(50) DEFAULT 'UNMAPPED';")
        else:
            try:
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN catalog_mapping_status varchar(50) DEFAULT 'UNMAPPED';")
            except Exception:
                pass


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0089_servicerequest_catalog_service_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='servicerequest',
                    name='catalog_mapping_status',
                    field=models.CharField(blank=True, db_index=True, default='UNMAPPED', max_length=50),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_or_fix_catalog_mapping_status,
                    noop_reverse,
                ),
            ],
        ),
    ]
