# Hand-written merge migration (this session, 2026-09-23) -- NOT generated by
# `manage.py makemigrations --merge` (no execution capability against this
# app's full dependency graph within this session's sandbox; see the GT
# Porter-parity implementation log for the execution capability that DOES
# exist and its limits).
#
# WHY THIS EXISTS: service_requests/migrations currently has THREE separate
# migrations all named "0088_*" and all declaring
# dependencies = [("service_requests", "0087_alter_catalogchangelog_action_and_more")]
# with no merge reconciling them:
#   - 0088_provision_legacy_servicerequest_columns.py
#   - 0088_repoint_package_stock_item_to_vegetable.py
#   - 0088_servicerequest_dispatch_attempts_and_more.py
# 0089_servicerequest_catalog_service_id_and_more.py only threads through the
# THIRD of these (dispatch_attempts), leaving the other two as orphaned graph
# leaves. On a fresh clone/CI environment, `manage.py makemigrations` and
# `manage.py migrate` will refuse to run ("Conflicting migrations detected;
# multiple leaf nodes") until this is reconciled -- this is not hypothetical,
# it's Django's own hard-coded behavior for exactly this graph shape.
#
# WHY THIS MERGE IS SAFE: inspected all three 0088 migrations' actual
# operations. Zero overlap:
#   - provision_legacy_servicerequest_columns: a defensive RunPython that
#     ALTERs the physical table to add 4 specific legacy columns (
#     catalog_service_id, package_display, package_id, package_version) ONLY
#     if they don't already exist -- explicitly written to be a safe no-op
#     against a database (e.g. production Supabase) that already has them.
#   - repoint_package_stock_item_to_vegetable: a RunPython + AlterField
#     touching Package.stock_item's FK target -- does not touch
#     ServiceRequest at all.
#   - servicerequest_dispatch_attempts_and_more: AddField x4 + AddIndex on
#     ServiceRequest (dispatch_attempts, dispatch_status, last_dispatch_error,
#     last_dispatched_at) -- different field names than the legacy-columns
#     migration, no collision.
# No two of these touch the same field, model state, or column name, so an
# empty merge (no operations) is exactly what Django's own `--merge` command
# would generate here -- there is nothing to reconcile beyond the graph edge.
#
# BEFORE TRUSTING THIS AGAINST A REAL DATABASE: run
#   python manage.py showmigrations service_requests
#   python manage.py makemigrations --check --dry-run
# against your actual Postgres/Supabase instance. This session's sandbox
# validated this file with `ast.parse` (syntax) and, for the equivalent
# Vendor-app fix in an earlier session, an equivalent merge was proven to
# import and pass `manage.py check` cleanly -- but this exact file was not
# executed against your live database, since that requires credentials this
# session does not have and will not fabricate.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0090_servicerequest_catalog_mapping_status"),
        ("service_requests", "0088_provision_legacy_servicerequest_columns"),
        ("service_requests", "0088_repoint_package_stock_item_to_vegetable"),
    ]

    operations = []
