# Generated by Django 6.0.8 on 2026-09-25 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('service_requests', '0090_servicerequest_catalog_mapping_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(db_index=True, max_length=100, unique=True)),
                ('free_radius_km', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('standard_fee', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Warehouse', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(decimal_places=6, default=12.7409, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=77.8253, max_digits=9)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company')),
            ],
        ),
    ]
