# Generated by Django 6.0.8 on 2026-09-19 09:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0091_acinspectionconfiguration_acinspectionratecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_name_snapshot', models.CharField(default='AC Inspection & Diagnostic Visit', help_text='Authoritative immutable snapshot of inspection title at booking time', max_length=200)),
                ('diagnostic_fee_snapshot', models.DecimalField(decimal_places=2, default=Decimal('199.00'), help_text='Authoritative diagnostic fee snapshot captured at booking confirmation', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='BOOKED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_configuration', models.ForeignKey(blank=True, help_text='Reference to the master configuration used at booking time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_inspections', to='service_requests.acinspectionconfiguration')),
                ('service_request', models.OneToOneField(help_text='The parent booking this inspection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_inspection', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInspectionRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_snapshot', models.CharField(max_length=150)),
                ('item_name_snapshot', models.CharField(max_length=200)),
                ('description_snapshot', models.TextField(blank=True, default='')),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_snapshot', models.CharField(default='fixed', max_length=50)),
                ('service_type_snapshot', models.CharField(default='SPARE_PART', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_snapshots', to='service_requests.customerinspection')),
                ('rate_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_snapshots', to='service_requests.acinspectionrateitem')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='customerinspection',
            index=models.Index(fields=['service_request'], name='service_req_service_eed833_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinspection',
            index=models.Index(fields=['inspection_configuration'], name='service_req_inspect_00c3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinspection',
            index=models.Index(fields=['status'], name='service_req_status_948018_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinspectionratesnapshot',
            index=models.Index(fields=['customer_inspection'], name='service_req_custome_6cc02b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinspectionratesnapshot',
            index=models.Index(fields=['rate_item'], name='service_req_rate_it_a0824a_idx'),
        ),
    ]
