# Hand-written migration (this session, 2026-09-23) -- NOT generated by
# `manage.py makemigrations` (no execution capability against this app's full
# dependency graph). Creates the new GTCancellationPolicy table for the
# configurable cancellation-fee rule described in models.py's docstring for
# this model -- see that docstring for the exact business decision this is
# gated on. This IS real DDL (a brand-new table, not a managed=False mirror
# of an existing column) -- unlike the Vendor-app fare_breakdown migrations
# from earlier sessions, there is no existing physical table to reconcile
# against, so this is a plain CreateModel with no pre-existing-schema risk.
#
# BEFORE TRUSTING THIS AGAINST A REAL DATABASE: run
#   python manage.py showmigrations service_requests
#   python manage.py makemigrations --check --dry-run
# against your actual Postgres/Supabase instance. This file was validated
# with ast.parse (syntax) only -- it depends on 0091_merge_20260923_gt_porter_parity,
# which itself reconciles a real, pre-existing migration-graph conflict (see
# that file's own header) that was not executed against your live database.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0091_merge_20260923_gt_porter_parity"),
    ]

    operations = [
        migrations.CreateModel(
            name="GTCancellationPolicy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_category", models.CharField(blank=True, default="", max_length=100)),
                ("fee_mode", models.CharField(choices=[("NONE", "No cancellation fee (current behavior, default)"), ("FLAT", "Flat rupee amount"), ("PERCENT", "Percentage of the booking's total_amount")], default="NONE", max_length=10)),
                ("flat_fee_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("percent_fee", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("applies_only_after_assignment", models.BooleanField(default=True)),
                ("grace_period_seconds", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GT Cancellation Fee Policy",
                "verbose_name_plural": "GT Cancellation Fee Policies",
            },
        ),
    ]
