# Generated by Django 6.0.8 on 2026-09-23 11:53

from django.db import migrations, models


def _ensure_columns(apps, schema_editor):
    """Add package_display/package_id/package_version only where 0088 (or legacy schema) did not."""
    conn = schema_editor.connection
    Model = apps.get_model("service_requests", "ServiceRequest")
    table = Model._meta.db_table
    with conn.cursor() as cur:
        existing = {c.name for c in conn.introspection.get_table_description(cur, table)}
    wanted = {
        "package_display": models.JSONField(blank=True, default=dict),
        "package_id": models.CharField(blank=True, default="", max_length=100),
        "package_version": models.CharField(blank=True, default="1.0", max_length=50),
    }
    for name, field in wanted.items():
        field.set_attributes_from_name(name)
        if name not in existing:
            schema_editor.add_field(Model, field)
        elif name == "package_display" and conn.vendor == "postgresql":
            # 0088 created it as varchar; the model is a JSONField.
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT data_type FROM information_schema.columns "
                    "WHERE table_name = %s AND column_name = 'package_display'", [table])
                row = cur.fetchone()
                if row and row[0] != "jsonb":
                    cur.execute(f"ALTER TABLE {table} ALTER COLUMN package_display DROP DEFAULT")
                    cur.execute(
                        f"ALTER TABLE {table} ALTER COLUMN package_display TYPE jsonb USING "
                        "CASE WHEN package_display IS NULL OR package_display = '' THEN '{}'::jsonb "
                        "ELSE to_jsonb(package_display) END")
                    cur.execute(f"ALTER TABLE {table} ALTER COLUMN package_display SET DEFAULT '{{}}'::jsonb")


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0092_gt_cancellation_policy"),
    ]

    operations = [
        # 0088 already provisions these physical columns on fresh databases (and production already had
        # them), so a plain AddField fails on PostgreSQL ("column ... already exists"). Keep the model
        # state change, but make the database side idempotent and type-correct.
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.AddField(
                model_name="servicerequest",
                name="package_display",
                field=models.JSONField(blank=True, default=dict),
            ),
            migrations.AddField(
                model_name="servicerequest",
                name="package_id",
                field=models.CharField(blank=True, default="", max_length=100),
            ),
            migrations.AddField(
                model_name="servicerequest",
                name="package_version",
                field=models.CharField(blank=True, default="1.0", max_length=50),
            ),
            ],
            database_operations=[migrations.RunPython(_ensure_columns, migrations.RunPython.noop)],
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="applies_only_after_assignment",
            field=models.BooleanField(
                default=True,
                help_text="If True (recommended, matches Porter's publicly observed behavior), the fee never applies while the booking is still searching for a technician/vehicle -- only once one has been assigned. If False, the fee applies to any cancellation of a paid booking regardless of dispatch state.",
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="fee_mode",
            field=models.CharField(
                choices=[
                    ("NONE", "No cancellation fee (current behavior, default)"),
                    ("FLAT", "Flat rupee amount"),
                    ("PERCENT", "Percentage of the booking's total_amount"),
                ],
                default="NONE",
                help_text="NONE (default) preserves today's behavior exactly: full refund request, no fee, regardless of dispatch progress.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="flat_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Used when fee_mode=FLAT. Rupees deducted from the refund amount if the fee applies.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="grace_period_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cancellations within this many seconds of assignment are still free, even if applies_only_after_assignment would otherwise charge a fee. 0 disables the grace period.",
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="percent_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Used when fee_mode=PERCENT. Percentage (0-100) of total_amount deducted from the refund amount if the fee applies.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="service_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Empty/blank applies platform-wide to all GT bookings (goods_transport, packers_movers, etc). Set a specific category to override for just that category.",
                max_length=100,
            ),
        ),
    ]
