# Generated by Django 6.0.8 on 2026-09-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0090_servicerequest_catalog_mapping_status'),
        ('service_requests', '0092_servicerequest_dispatch_attempts_and_more'),
    ]

    operations = [
    ]
