# Generated by Django 6.0.8 on 2026-09-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0092_gt_cancellation_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="package_display",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="package_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="package_version",
            field=models.CharField(blank=True, default="1.0", max_length=50),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="applies_only_after_assignment",
            field=models.BooleanField(
                default=True,
                help_text="If True (recommended, matches Porter's publicly observed behavior), the fee never applies while the booking is still searching for a technician/vehicle -- only once one has been assigned. If False, the fee applies to any cancellation of a paid booking regardless of dispatch state.",
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="fee_mode",
            field=models.CharField(
                choices=[
                    ("NONE", "No cancellation fee (current behavior, default)"),
                    ("FLAT", "Flat rupee amount"),
                    ("PERCENT", "Percentage of the booking's total_amount"),
                ],
                default="NONE",
                help_text="NONE (default) preserves today's behavior exactly: full refund request, no fee, regardless of dispatch progress.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="flat_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Used when fee_mode=FLAT. Rupees deducted from the refund amount if the fee applies.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="grace_period_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cancellations within this many seconds of assignment are still free, even if applies_only_after_assignment would otherwise charge a fee. 0 disables the grace period.",
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="percent_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Used when fee_mode=PERCENT. Percentage (0-100) of total_amount deducted from the refund amount if the fee applies.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="gtcancellationpolicy",
            name="service_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Empty/blank applies platform-wide to all GT bookings (goods_transport, packers_movers, etc). Set a specific category to override for just that category.",
                max_length=100,
            ),
        ),
    ]
