# Generated by Django 6.0.8 on 2026-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0093_servicerequest_package_display_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GTWaitingChargePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Empty/blank applies platform-wide to all GT bookings. Set a specific category to override for just that category.",
                        max_length=100,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="False (default) preserves today's behavior exactly: no waiting charge is ever computed or applied.",
                    ),
                ),
                (
                    "free_minutes_per_stop",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minutes of dwell time (completed_at - arrived_at) allowed per stop before a charge applies. 0 with is_enabled=True would charge from the first minute -- leave is_enabled=False until a real value is set.",
                    ),
                ),
                (
                    "rate_per_minute",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rupees charged per minute of waiting beyond free_minutes_per_stop, at each stop.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_charge_per_booking",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional cap on the total waiting charge across all stops in one booking. Blank = no cap.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GT Waiting Charge Policy",
                "verbose_name_plural": "GT Waiting Charge Policies",
            },
        ),
    ]
