# Generated by Django 6.0.8 on 2026-09-23 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0093_merge_20260923_1045'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acrepairratecard',
            name='service_req_categor_2f1b09_idx',
        ),
        migrations.RemoveIndex(
            model_name='acrepairratecard',
            name='service_req_item_co_4b5ffd_idx',
        ),
        migrations.DeleteModel(
            name='ACRepairRateCard',
        ),
        migrations.AddField(
            model_name='estimationquotation',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Review comments or send-back instructions from admin'),
        ),
        migrations.AddField(
            model_name='estimationquotation',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimationquotation',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('VENDOR_CONFIRMED', 'Vendor Confirmed'), ('TECHNICIAN_ASSIGNED', 'Technician Assigned'), ('TECHNICIAN_ON_THE_WAY', 'Technician On The Way'), ('TECHNICIAN_ARRIVED', 'Technician Arrived'), ('INSPECTION_IN_PROGRESS', 'Inspection In Progress'), ('INSPECTION_COMPLETED', 'Inspection Completed'), ('ESTIMATION_SUBMITTED', 'Estimation Submitted'), ('ADMIN_APPROVED', 'Admin Approved'), ('SENT_BACK_TO_TECHNICIAN', 'Sent Back to Technician'), ('CUSTOMER_PENDING', 'Customer Pending'), ('QUOTATION_SENT', 'Quotation Sent'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('REPAIR_AUTHORIZED', 'Repair Authorized'), ('TECHNICIAN_REPAIR', 'Technician Repair'), ('TESTING', 'Testing'), ('CONVERTED_TO_SERVICE', 'Converted to Service'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='estimationquotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED_FOR_REVIEW', 'Submitted for Review'), ('ADMIN_APPROVED', 'Admin Approved'), ('SENT_BACK_TO_TECHNICIAN', 'Sent Back to Technician'), ('SENT', 'Sent to Customer'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
    ]
