# Generated by Django 6.0.8 on 2026-09-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0094_gtwaitingchargepolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="GTAdvancePaymentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Empty/blank applies platform-wide to all GT bookings (goods_transport, packers_movers, etc). Set a specific category to override for just that category.",
                        max_length=100,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="False (default) preserves today's behavior exactly: the full booking amount is due whenever a payment order is first created, with no partial-advance option.",
                    ),
                ),
                (
                    "advance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage (0-100) of total_amount due upfront when a payment order is first created for this booking; the remainder is due before/at completion, same as the existing PaintingQuote advance/balance pattern. Only used when is_enabled=True.",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GT Advance Payment Policy",
                "verbose_name_plural": "GT Advance Payment Policies",
            },
        ),
    ]
