# Generated by Django 5.0.14 on 2026-09-23 13:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0094_remove_acrepairratecard_service_req_categor_2f1b09_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTimeSlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('default_end_time', models.TimeField(default=datetime.time(18, 0))),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30)),
                ('slot_capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_config', to='service_requests.service')),
            ],
            options={
                'db_table': 'service_time_slot_config',
                'ordering': ['service_id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('slot_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='service_requests.service')),
            ],
            options={
                'db_table': 'service_date_override',
                'ordering': ['date', 'start_time'],
                'unique_together': {('service', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ServiceWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('slot_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='service_requests.service')),
            ],
            options={
                'db_table': 'service_weekly_schedule',
                'ordering': ['service_id', 'day_of_week'],
                'unique_together': {('service', 'day_of_week')},
            },
        ),
    ]
