# Generated by Django 6.0.8 on 2026-09-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0089_packagevariant"),
        ("service_requests", "0095_gtadvancepaymentpolicy"),
    ]

    operations = []
