# Generated by Django 5.0.14 on 2026-09-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0095_servicetimeslotconfig_servicedateoverride_and_more"),
        (
            "service_requests",
            "0096_merge_0089_packagevariant_0095_gtadvancepaymentpolicy",
        ),
    ]

    operations = []
