# Generated by Django 5.0.14 on 2026-09-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0097_merge_20260925_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of service highlight badges'),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Storage path or URL to the inspection service image', max_length=500),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='includes',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of diagnostic inspection check points'),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='ready',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of customer preparation instructions'),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='subtitle',
            field=models.TextField(blank=True, default='Not sure about the fault? Certified technician visits with diagnostic instruments, inspects cooling, gas pressure & electricals, and provides an itemized quotation before repair.', help_text='Customer-facing description of the diagnostic visit'),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='title',
            field=models.CharField(blank=True, default='AC Inspection & Diagnostic Visit', help_text='Customer-facing service title', max_length=255),
        ),
    ]
