# Generated by Django 6.0.8 on 2026-09-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0087_remove_servicerequest_unique_customer_idempotency_key_and_more'),
        ('service_requests', '0097_merge_20260925_1641'),
    ]

    operations = [
    ]
