# Generated by Django on 2026-09-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_alter_company_data_region_and_more"),
        ("logistics", "0018_packersmoversconfig_max_helpers"),
        ("service_requests", "0098_merge_20260926_1013"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="vendorcapabilityrequest",
            new_name="vcr_vendor_status_idx",
            old_name="service_req_vendor__91bc67_idx",
        ),
        migrations.AlterField(
            model_name="addon",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addons",
                to="service_requests.package",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["job_type", "status"], name="service_req_job_typ_6bd73d_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["job_type", "created_at"], name="service_req_job_typ_4f9cb8_idx"),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False), models.Q(("idempotency_key", ""), _negated=True)),
                fields=("customer", "idempotency_key"),
                name="unique_customer_idempotency_key",
            ),
        ),
    ]
