# Generated by Django 5.0.14 on 2026-09-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0098_acinspectionconfiguration_badges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedulerequest',
            name='new_time_slot',
            field=models.CharField(blank=True, default='09:00 - 10:00', max_length=100),
        ),
    ]
