# Generated by Django 6.0.8 on 2026-09-29 07:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0099_rename_service_req_vendor__91bc67_idx_vcr_vendor_status_idx_and_more'),
    ]

    # SEVO GT Round 7: this file belongs to a regenerated duplicate branch
    # (0099_rename_... -> 0100_acinspection... -> 0101_gtclaimpolicy...) brought in by merge 7ad1eda0.
    # Every operation below already exists in the main chain (0098_acinspection..., 0099_package_gt_gst_rate,
    # 0101_restore_dropped_indexes..., 0104/0106/0107 GT policies). Executing them again fails with
    # "already exists", so they are kept only for reference and are NOT run. Final model state is unchanged
    # (verified: makemigrations --check reports no changes).
    operations = []
    _duplicate_operations_not_run = [
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of service highlight badges'),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Storage path or URL to the inspection service image', max_length=500),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='includes',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of diagnostic inspection check points'),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='ready',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of customer preparation instructions'),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='subtitle',
            field=models.TextField(blank=True, default='Not sure about the fault? Certified technician visits with diagnostic instruments, inspects cooling, gas pressure & electricals, and provides an itemized quotation before repair.', help_text='Customer-facing description of the diagnostic visit'),
        ),
        migrations.AddField(
            model_name='acinspectionconfiguration',
            name='title',
            field=models.CharField(blank=True, default='AC Inspection & Diagnostic Visit', help_text='Customer-facing service title', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='gt_gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Goods & Transport only: GST percentage already INCLUDED in the fare (18.00 = 18%). The fare does not change; invoices show the GST component. Enter 0 to remove GST; blank leaves the tier unchanged. Mirrors ServiceTier.gst_rate.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='new_time_slot',
            field=models.CharField(blank=True, default='09:00 - 10:00', max_length=100),
        ),
    ]
