# Generated by Django 6.0.8 on 2026-09-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0100_acinspectionconfiguration_badges_and_more'),
    ]

    # SEVO GT Round 7: this file belongs to a regenerated duplicate branch
    # (0099_rename_... -> 0100_acinspection... -> 0101_gtclaimpolicy...) brought in by merge 7ad1eda0.
    # Every operation below already exists in the main chain (0098_acinspection..., 0099_package_gt_gst_rate,
    # 0101_restore_dropped_indexes..., 0104/0106/0107 GT policies). Executing them again fails with
    # "already exists", so they are kept only for reference and are NOT run. Final model state is unchanged
    # (verified: makemigrations --check reports no changes).
    operations = []
    _duplicate_operations_not_run = [
        migrations.CreateModel(
            name='GTClaimPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, default='', help_text='Blank applies to all GT bookings; a category value overrides it.', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('included_liability_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Rupee cap of the liability that comes with every booking, without paid insurance. Blank = uninsured bookings cannot claim.', max_digits=10, null=True)),
                ('cap_at_fare', models.BooleanField(default=True, help_text="Also limit the included liability to the booking's fare (lower of the two).")),
                ('claim_window_hours', models.PositiveIntegerField(blank=True, help_text='Claims must be filed within this many hours of delivery. Blank = no limit.', null=True)),
                ('require_photo', models.BooleanField(default=False, help_text='Require at least one damage photo.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Claim Policy',
                'verbose_name_plural': 'GT Claim Policies',
            },
        ),
        migrations.CreateModel(
            name='GTExtraChargePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, default='', help_text='Blank applies to all GT bookings; a category value overrides it.', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('allow_toll', models.BooleanField(default=True)),
                ('allow_parking', models.BooleanField(default=True)),
                ('max_amount_per_item', models.DecimalField(blank=True, decimal_places=2, help_text='Largest single toll/parking receipt accepted. Blank = no limit.', max_digits=10, null=True)),
                ('max_total_per_booking', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on the total pass-through billed per booking. Blank = no limit.', max_digits=10, null=True)),
                ('require_receipt_photo', models.BooleanField(default=False, help_text='When on, a receipt photo must be uploaded by the driver; a typed reference alone is refused.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Extra Charge (Toll/Parking) Policy',
                'verbose_name_plural': 'GT Extra Charge (Toll/Parking) Policies',
            },
        ),
        migrations.CreateModel(
            name='GTInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_offered', models.BooleanField(default=True)),
                ('premium_rate', models.DecimalField(decimal_places=4, default=0.02, help_text='Premium as a fraction of the declared value (0.02 = 2%).', max_digits=6)),
                ('max_liability', models.DecimalField(decimal_places=2, default=500000, help_text='Highest declared value / liability cap.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Insurance Policy',
                'verbose_name_plural': 'GT Insurance Policy',
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_exception',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
