# Generated by Django 5.2.17 on 2026-09-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0101_restore_dropped_indexes_and_idempotency_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
