# Generated by Django 5.2.17 on 2026-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0102_servicerequest_customer_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_exception',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
