# Generated by Django 5.2.17 on 2026-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0103_servicerequest_delivery_exception'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTExtraChargePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, default='', help_text='Blank applies to all GT bookings; a category value overrides it.', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('allow_toll', models.BooleanField(default=True)),
                ('allow_parking', models.BooleanField(default=True)),
                ('max_amount_per_item', models.DecimalField(blank=True, decimal_places=2, help_text='Largest single toll/parking receipt accepted. Blank = no limit.', max_digits=10, null=True)),
                ('max_total_per_booking', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on the total pass-through billed per booking. Blank = no limit.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Extra Charge (Toll/Parking) Policy',
                'verbose_name_plural': 'GT Extra Charge (Toll/Parking) Policies',
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
