# Generated by Django 5.2.17 on 2026-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0104_gt_extra_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtextrachargepolicy',
            name='require_receipt_photo',
            field=models.BooleanField(default=False, help_text='When on, a receipt photo must be uploaded by the driver; a typed reference alone is refused.'),
        ),
    ]
