# Generated by Django 5.2.17 on 2026-09-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0105_gt_extra_charge_receipt_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_offered', models.BooleanField(default=True)),
                ('premium_rate', models.DecimalField(decimal_places=4, default=0.02, help_text='Premium as a fraction of the declared value (0.02 = 2%).', max_digits=6)),
                ('max_liability', models.DecimalField(decimal_places=2, default=500000, help_text='Highest declared value / liability cap.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Insurance Policy',
                'verbose_name_plural': 'GT Insurance Policy',
            },
        ),
    ]
