# Generated by Django 5.2.17 on 2026-09-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0106_gt_insurance_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTClaimPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, default='', help_text='Blank applies to all GT bookings; a category value overrides it.', max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('included_liability_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Rupee cap of the liability that comes with every booking, without paid insurance. Blank = uninsured bookings cannot claim.', max_digits=10, null=True)),
                ('cap_at_fare', models.BooleanField(default=True, help_text="Also limit the included liability to the booking's fare (lower of the two).")),
                ('claim_window_hours', models.PositiveIntegerField(blank=True, help_text='Claims must be filed within this many hours of delivery. Blank = no limit.', null=True)),
                ('require_photo', models.BooleanField(default=False, help_text='Require at least one damage photo.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Claim Policy',
                'verbose_name_plural': 'GT Claim Policies',
            },
        ),
    ]
