# Generated by Django 5.2.17 on 2026-09-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0099_alter_reschedulerequest_new_time_slot'),
        ('service_requests', '0107_gt_claim_policy'),
    ]

    operations = [
    ]
