# Generated by Django 5.2.17 on 2026-09-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0108_merge_20260928_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTOperationsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gt_quote_validity_minutes', models.PositiveIntegerField(default=15, help_text='How long a Mini Truck / Two Wheeler fare quote stays valid.')),
                ('pm_instant_quote_validity_minutes', models.PositiveIntegerField(default=30, help_text='How long a price-locked Packers & Movers instant quote stays valid.')),
                ('pm_estimate_validity_hours', models.PositiveIntegerField(default=48, help_text='How long a non-binding Packers & Movers survey estimate stays valid.')),
                ('online_payment_window_minutes', models.PositiveIntegerField(default=30, help_text='An unpaid online / wallet booking is cancelled after this many minutes.')),
                ('high_value_consignment_threshold', models.DecimalField(decimal_places=2, default=25000, help_text='Declared value at or above which a named receiver is mandatory.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Operations Config',
                'verbose_name_plural': 'GT Operations Config',
            },
        ),
        migrations.RemoveField(
            model_name='gtinsurancepolicy',
            name='premium_rate',
        ),
        migrations.AddField(
            model_name='gtinsurancepolicy',
            name='premium_percent',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Premium as a percentage of the declared value (2 = 2%).', max_digits=5),
        ),
    ]
