# Generated by Django 5.2.17 on 2026-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0109_gt_operations_config_and_insurance_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='checkpoint_radius_meters',
            field=models.PositiveIntegerField(default=250, help_text='How close (metres) a driver must be to the pickup / drop to verify arrival.'),
        ),
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='delivery_otp_required',
            field=models.BooleanField(default=True, help_text="Require the customer's delivery OTP before a trip can be completed."),
        ),
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='delivery_otp_ttl_minutes',
            field=models.PositiveIntegerField(default=30, help_text='How long a delivery OTP stays valid before it must be resent.'),
        ),
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='max_otp_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Wrong delivery-OTP entries allowed before the driver is locked out.'),
        ),
    ]
