# Generated by Django 5.2.17 on 2026-09-28 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0111_gt_wallet_part_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='wallet_max_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A recharge may not take the wallet above this balance. Blank = no cap.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='wallet_max_topup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largest single wallet recharge. Blank = no per-recharge limit.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='wallet_topup_enabled',
            field=models.BooleanField(default=False, help_text='Let customers add money to their SEVO wallet online.'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reason',
            field=models.CharField(choices=[('REFUND', 'Refund Credited to Wallet'), ('GOODWILL', 'Goodwill Credit'), ('REFERRAL', 'Referral Reward'), ('BOOKING_DEBIT', 'Applied to Booking Payment'), ('ADJUSTMENT', 'Manual Adjustment'), ('REVERSAL', 'Reversal'), ('TOPUP', 'Wallet Recharge')], max_length=20),
        ),
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('gateway', models.CharField(default='razorpay', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_requests_wallet_topup',
                'ordering': ['-created_at'],
            },
        ),
    ]
