# Generated by Django 5.2.17 on 2026-09-29 08:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0112_gt_wallet_topup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTPTLPricingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Accept Part Truck Load quotes and bookings.')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, default=0, help_text="Rupees per chargeable kg (GST inclusive at the tier's GST rate).", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_chargeable_weight_kg', models.DecimalField(decimal_places=2, default=0, help_text='Declared weight below this is charged as this weight. 0 = no minimum.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_fare', models.DecimalField(blank=True, decimal_places=2, help_text='Floor on the freight charge. Blank = no floor.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('min_advance_days', models.PositiveIntegerField(default=1, help_text='PTL is advance-booked: the pickup date must be at least this many days ahead (1 = no same-day).')),
                ('load_assist_enabled', models.BooleanField(default=False, help_text='Offer paid driver-assisted loading. Pricing hook only; the driver-side assist workflow is not built yet.')),
                ('load_assist_fee', models.DecimalField(decimal_places=2, default=0, help_text='Flat Load Assist fee per booking, when offered.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Part Truck Load (PTL) Pricing Policy',
                'verbose_name_plural': 'GT Part Truck Load (PTL) Pricing Policy',
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='logistics_booking_mode',
            field=models.CharField(blank=True, choices=[('spot', 'Spot'), ('ptl', 'Part Truck Load')], db_default='spot', db_index=True, default='spot', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ptl_declared_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer-declared cargo weight for a PTL booking (priced per kg).', max_digits=8, null=True),
        ),
    ]
