# Generated by Django 5.2.17 on 2026-09-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0101_gtclaimpolicy_gtextrachargepolicy_gtinsurancepolicy_and_more'),
        ('service_requests', '0113_light_ptl'),
    ]

    operations = [
    ]
