# Generated by Django 5.2.17 on 2026-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0114_merge_20260929_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='gt_max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Goods & Transport only: maximum cargo weight (kg) this vehicle tier can carry. Mirrors ServiceTier.max_weight_kg -- used for cargo fitment checks, PTL eligibility and dispatch/vehicle-compatibility. Blank leaves the tier's existing capacity untouched.", max_digits=10, null=True),
        ),
    ]
