# Generated by Django 5.2.17 on 2026-09-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0115_gt_max_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='eway_bill_required_above',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Declared value at/above which a missing e-way-bill number/document triggers a warning at booking/dispatch (never a hard block).', max_digits=12),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='eway_bill_document',
            field=models.FileField(blank=True, null=True, upload_to='service_requests/eway_bills/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='eway_bill_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
