# Generated by Django 5.2.17 on 2026-09-30 05:21

from django.db import migrations, models


def add_eway_bill_number_if_not_exists(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE service_requests_servicerequest ADD COLUMN IF NOT EXISTS eway_bill_number VARCHAR(50) DEFAULT '';"
        )
    elif connection.vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute("PRAGMA table_info(service_requests_servicerequest);")
            columns = [row[1] for row in cursor.fetchall()]
            if "eway_bill_number" not in columns:
                schema_editor.execute(
                    "ALTER TABLE service_requests_servicerequest ADD COLUMN eway_bill_number VARCHAR(50) DEFAULT '';"
                )


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0115_gt_max_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtoperationsconfig',
            name='eway_bill_required_above',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Declared value at/above which a missing e-way-bill number/document triggers a warning at booking/dispatch (never a hard block).', max_digits=12),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='eway_bill_document',
            field=models.FileField(blank=True, null=True, upload_to='service_requests/eway_bills/'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='servicerequest',
                    name='eway_bill_number',
                    field=models.CharField(blank=True, default='', max_length=50),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_eway_bill_number_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
    ]
