# Generated by Django 5.2.17 on 2026-09-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0119_gt_ptl_porter_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTTaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, default='', help_text="Blank applies platform-wide to all GT bookings (goods_transport, goods_transport_truck, goods_transport_two_wheeler, packers_movers, etc). Set a specific category to scope this policy -- e.g. by service, package or vehicle/service mode, since SEVO's service_category values already distinguish those (truck vs two-wheeler vs packers & movers).", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rows are never resolved, same convention as every other GT policy model.')),
                ('gst_enabled', models.BooleanField(default=True, help_text="Master GST switch for bookings this policy scopes. True (default) keeps today's behavior: GST is shown per whatever rate is configured on the vehicle tier/package (blank/0 there already means 'no GST'). Set False here to force-suppress the GST line for this scope regardless of the tier/package rate -- e.g. while a GST-registration decision is pending.")),
                ('rcm_enabled', models.BooleanField(default=False, help_text='Reverse Charge Mechanism opt-in for this scope. Off by default -- the safe, do-nothing setting. An Admin who has confirmed (outside this system) that RCM genuinely applies to this GT service turns this on; nothing in SEVO decides that for them.')),
                ('rcm_applies_when_gstin_registered', models.BooleanField(default=True, help_text="The simple, configuration-only 'specified person' classification the round's brief calls for: when RCM is enabled for this scope, an order is treated as RCM-applicable if the customer has supplied a GSTIN (ServiceRequest.customer_gstin is non-blank). This is NOT a complete legal classification of which recipient categories actually qualify as a 'specified person' under GST law -- it is the safely-representable-as-configuration proxy the brief asked for. A more precise classification (by recipient business type) remains an external/legal decision; if SEVO ever needs one, it is a new field on top of this, not a replacement of it.")),
                ('rcm_statement', models.TextField(default='Tax payable on reverse charge basis. GST on this consignment is not charged by the supplier and is to be self-assessed and paid by the recipient under the applicable reverse charge provisions.', help_text='Exact wording printed on an invoice when RCM applies to that booking, in place of a charged GST line. This is the standard, universally-true statement GST law requires on an RCM invoice, not a Porter-specific or invented value -- Admin-editable so Finance/Legal can adjust the exact wording without a code change.')),
                ('place_of_supply_note', models.TextField(blank=True, default='', help_text='Not used by any calculation. Free-text space to record a future CGST/SGST vs IGST place-of-supply decision once Legal/Finance makes one -- deliberately NOT wired to any logic this round; see Round 13 report.')),
                ('effective_from', models.DateField(blank=True, help_text='This policy applies only to bookings quoted on/after this date. Blank = no start restriction.', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='This policy applies only to bookings quoted on/before this date (inclusive). Blank = no end restriction.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GT Tax / RCM Policy',
                'verbose_name_plural': 'GT Tax / RCM Policies',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='catalogchangelog',
            name='entity_type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('SERVICE', 'Service'), ('PACKAGE', 'Package'), ('ADDON', 'Add-on'), ('SERVICE_TIER', 'Goods & Transport Tier'), ('TAX_POLICY', 'GT Tax / RCM Policy')], max_length=20),
        ),
    ]
