# Generated by Django 5.2.17 on 2026-09-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0102_eway_bill_number_state_only'),
        ('service_requests', '0120_gttaxpolicy_alter_catalogchangelog_entity_type'),
    ]

    operations = [
    ]
