# Generated by Django 5.2.17 on 2026-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0121_merge_20260930_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='eway_bill_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
