# Generated by Django 5.2.17 on 2026-10-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0117_ensure_eway_bill_number_column"),
        ("service_requests", "0122_alter_servicerequest_eway_bill_number"),
    ]

    operations = []
