# Generated by Django 6.0.8 on 2026-08-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_company_schema_name_company_slug_and_more'),
        ('inventory', '0002_inventory_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransfer',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transfers', to='companies.company'),
            preserve_default=False,
        ),
    ]
