# Generated by Django on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_repair_inventoryitem_fields'),
    ]

    operations = [
        # 1. Delete workforce issuance model
        migrations.DeleteModel(
            name='InventoryIssuance',
        ),

        # 2. Update InventoryItem
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse_name',
            field=models.CharField(blank=True, default='Main Warehouse', max_length=255),
        ),

        # 3. Update InventoryAlert
        migrations.RemoveField(
            model_name='inventoryalert',
            name='employee',
        ),

        # 4. Update InventoryTransfer
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='inventorytransfer',
            name='linked_task',
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='from_warehouse',
            field=models.CharField(blank=True, default='Main Warehouse', max_length=255),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='to_warehouse',
            field=models.CharField(blank=True, default='Secondary Warehouse', max_length=255),
        ),
    ]
