# Generated by Django 6.0.8 on 2026-08-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_clean_workforce_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('consumable', 'Consumable'), ('uniform', 'Uniform'), ('vehicle', 'Vehicle'), ('ppe', 'PPE'), ('tool', 'Tool'), ('part', 'Spare Part'), ('material', 'Raw Material')], max_length=50),
        ),
    ]
