# Generated by Django 6.0.8 on 2026-09-04 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('inventory', '0006_alter_inventoryitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='default_daily_quantity_grams',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_quantity_grams',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Adjustment'), ('DAILY_RESET', 'Daily Reset'), ('SOLD', 'Sold'), ('RESTOCKED_ON_CANCELLATION', 'Restocked on Cancellation')], max_length=30)),
                ('delta_grams', models.IntegerField(help_text='Change in grams (positive for addition, negative for deduction)')),
                ('balance_after_grams', models.PositiveIntegerField(help_text='Stock quantity in grams immediately after this movement')),
                ('reason', models.TextField(blank=True, default='')),
                ('booking_ref', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.inventoryitem')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
