# Generated by Django 6.0.8 on 2026-09-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('inventory', '0008_inventoryitem_image'),
        ('service_requests', '0087_alter_catalogchangelog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('stock_quantity_grams', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('default_daily_quantity_grams', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetables', to='companies.company')),
                ('package', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vegetable_stock', to='service_requests.package')),
            ],
        ),
        migrations.CreateModel(
            name='VegetableStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Adjustment'), ('DAILY_RESET', 'Daily Reset'), ('SOLD', 'Sold'), ('RESTOCKED_ON_CANCELLATION', 'Restocked on Cancellation')], max_length=30)),
                ('delta_grams', models.IntegerField(help_text='Change in grams (positive for addition, negative for deduction)')),
                ('balance_after_grams', models.PositiveIntegerField(help_text='Stock quantity in grams immediately after this movement')),
                ('reason', models.TextField(blank=True, default='')),
                ('booking_ref', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_vegetable_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetable_stock_movements', to='companies.company')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.vegetable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
