# Generated by Django 6.0.8 on 2026-09-20 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('inventory', '0013_vegetablecategory_vegetable_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablestockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Adjustment'), ('DAILY_RESET', 'Daily Reset'), ('SOLD', 'Sold'), ('RESTOCKED_ON_CANCELLATION', 'Restocked on Cancellation'), ('CLAIM_WRITEOFF', 'Claim Write-off')], max_length=30),
        ),
        migrations.CreateModel(
            name='VegetableClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('WAREHOUSE_SPOILAGE', 'Warehouse Spoilage / Rot'), ('TRANSIT_DAMAGE', 'Transit / Delivery Damage'), ('QC_FAILURE', 'QC / Inspection Failure'), ('EXPIRED', 'Shelf Life Expired'), ('INVENTORY_DISCREPANCY', 'Stock Discrepancy / Missing'), ('OTHER', 'Other')], default='WAREHOUSE_SPOILAGE', max_length=30)),
                ('quantity_grams', models.PositiveIntegerField(help_text='Quantity of vegetable stock written off in grams')),
                ('estimated_loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vegetable_claims', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vegetable_claims', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetable_claims', to='companies.company')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_claim', to='inventory.vegetablestockmovement')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='inventory.vegetable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
