# Generated by Django 6.0.8 on 2026-09-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_vegetable_is_resubmission_vegetable_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category if this is a subcategory (maximum depth: 2 levels).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.vegetablecategory'),
        ),
    ]
