# Generated by Django 6.0.8 on 2026-09-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_vegetablecategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='source',
            field=models.CharField(choices=[('DIRECT', 'Created Directly by Admin'), ('REQUEST', 'Submitted via Catalog Uploads')], db_index=True, default='DIRECT', help_text='Origin of produce: DIRECT (Admin-created) or REQUEST (Catalog Uploads submission).', max_length=20),
        ),
        migrations.AddField(
            model_name='vegetablecategory',
            name='source',
            field=models.CharField(choices=[('DIRECT', 'Created Directly by Admin'), ('REQUEST', 'Submitted via Catalog Uploads')], db_index=True, default='DIRECT', help_text='Origin of category: DIRECT (Admin-created) or REQUEST (Catalog Uploads submission).', max_length=20),
        ),
        migrations.AlterField(
            model_name='vegetablecategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category if this is a subcategory (supports unlimited nesting depth).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.vegetablecategory'),
        ),
    ]
