# Generated by Django 6.0.8 on 2026-09-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_vegetable_source_vegetablecategory_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablecategory',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('pcs', 'Pieces (pcs)'), ('bunch', 'Bunch (bunch)'), ('packet', 'Packet / Box (pkt)'), ('dozen', 'Dozen (dz)')], default=None, help_text='Default unit of measurement for products under this category (e.g. kg, g, pcs, bunch).', max_length=20, null=True),
        ),
    ]
