# Generated by Django 6.0.8 on 2026-09-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_vegetablecategory_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablestockmovement',
            name='movement_type',
            field=models.CharField(choices=[('RESTOCK', 'Restock'), ('ADJUSTMENT', 'Adjustment'), ('DAILY_RESET', 'Daily Reset'), ('SOLD', 'Sold'), ('RESTOCKED_ON_CANCELLATION', 'Restocked on Cancellation'), ('CLAIM_WRITEOFF', 'Claim Write-off'), ('RESTOCKED_ON_RETURN', 'Restocked on Return'), ('RETURN_REPLACEMENT', 'Return Replacement'), ('RETURN_WRITEOFF', 'Return Write-off')], max_length=30),
        ),
    ]
