# Generated by Django 6.0.8 on 2026-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_vegetablestockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='unit_basis',
            field=models.CharField(choices=[('WEIGHT', 'Weight (g/kg)'), ('COUNT', 'Count (pcs/bunch/dozen)')], db_index=True, default='WEIGHT', help_text='Base measurement basis: WEIGHT (tracked in grams) or COUNT (tracked in integer pieces).', max_length=10),
        ),
        migrations.AddField(
            model_name='vegetablecategory',
            name='unit_basis',
            field=models.CharField(choices=[('WEIGHT', 'Weight (g/kg)'), ('COUNT', 'Count (pcs/bunch/dozen)')], default='WEIGHT', help_text='Suggested unit basis for products under this category (WEIGHT for grams/kg, COUNT for whole pieces/bunches).', max_length=10),
        ),
        migrations.AddField(
            model_name='vegetablestockmovement',
            name='unit_basis',
            field=models.CharField(choices=[('WEIGHT', 'Weight'), ('COUNT', 'Count')], default='WEIGHT', help_text='Measurement basis of this movement.', max_length=10),
        ),
        migrations.AddField(
            model_name='vegetablestockmovement',
            name='unit_label',
            field=models.CharField(blank=True, default='g', help_text='Unit string at movement time (e.g. g, kg, pcs, bunch).', max_length=20),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='default_daily_quantity_grams',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Default daily reset quota in base units (grams for WEIGHT, integer count for COUNT).', null=True),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='stock_quantity_grams',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Live stock balance in base units (grams for WEIGHT, integer count for COUNT).', null=True),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='unit',
            field=models.CharField(blank=True, default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='vegetablecategory',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('pcs', 'Pieces (pcs)'), ('bunch', 'Bunch (bunch)'), ('packet', 'Packet / Box (pkt)'), ('dozen', 'Dozen (dz)')], default=None, help_text='Suggested default unit for new products under this category. Vendors can freely change it.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vegetablestockmovement',
            name='balance_after_grams',
            field=models.PositiveIntegerField(help_text='Stock quantity in base units immediately after this movement'),
        ),
        migrations.AlterField(
            model_name='vegetablestockmovement',
            name='delta_grams',
            field=models.IntegerField(help_text='Change in base units (positive for addition, negative for deduction)'),
        ),
    ]
