# Generated by Django 6.0.8 on 2026-09-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_vegetable_unit_basis_vegetablecategory_unit_basis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetablecategory',
            name='unit_basis',
        ),
        migrations.RemoveField(
            model_name='vegetablecategory',
            name='unit_of_measurement',
        ),
    ]
