# Generated by Django 6.0.8 on 2026-09-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_daily_reset_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='reorder_threshold',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Reorder alert threshold in base units (grams for WEIGHT, integer count for COUNT).', null=True),
        ),
    ]
