# Generated by Django 6.0.8 on 2026-09-20 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_orders', '0002_copy_grocery_orders_to_vegetable_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('DAMAGED_OR_SPOILED', 'Damaged / Spoiled'), ('WRONG_ITEM', 'Wrong Item Received'), ('SHORT_QUANTITY', 'Short Weight / Missing Item'), ('POOR_QUALITY', 'Poor Quality / Stale'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], db_index=True, default='REQUESTED', max_length=20)),
                ('resolution_action', models.CharField(choices=[('NONE', 'None'), ('REFUND', 'Refund Marked'), ('REPLACEMENT', 'Replacement Dispatched'), ('REJECTED', 'Rejected')], default='NONE', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vegetable_returns', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_vegetable_returns', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Optional specific line item being returned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='vegetable_orders.vegetableorderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='vegetable_orders.vegetableorder')),
            ],
            options={
                'db_table': 'vegetable_orders_vegetablereturn',
                'ordering': ['-created_at'],
            },
        ),
    ]
