# Generated by Django 6.0.8 on 2026-09-23 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_vegetablestockmovement_movement_type'),
        ('vegetable_orders', '0003_vegetablereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablereturn',
            name='stock_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_return', to='inventory.vegetablestockmovement'),
        ),
    ]
