# Generated by Django 6.0.8 on 2026-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_orders', '0004_vegetablereturn_stock_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetableorderitem',
            name='unit_basis',
            field=models.CharField(choices=[('WEIGHT', 'Weight'), ('COUNT', 'Count')], default='WEIGHT', help_text='Measurement basis of this line item.', max_length=10),
        ),
        migrations.AddField(
            model_name='vegetableorderitem',
            name='unit_label',
            field=models.CharField(blank=True, default='g', help_text='Unit string (e.g. g, kg, pcs, bunch).', max_length=20),
        ),
        migrations.AlterField(
            model_name='vegetableorderitem',
            name='quantity_grams',
            field=models.PositiveIntegerField(help_text='Exact base units ordered and deducted (grams for WEIGHT, pieces for COUNT).'),
        ),
    ]
