# Generated by Django 6.0.8 on 2026-09-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0089_packagevariant'),
        ('vegetable_orders', '0005_vegetableorderitem_unit_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetableorderitem',
            name='pack_value_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of the pack size value at order creation.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vegetableorderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vegetable_order_items', to='service_requests.packagevariant'),
        ),
        migrations.AddField(
            model_name='vegetableorderitem',
            name='variant_name_snapshot',
            field=models.CharField(blank=True, default='', help_text="Snapshot of the chosen variant name at order creation (e.g. '500 g', '2 kg').", max_length=120),
        ),
    ]
