# Generated by Django 6.0.8 on 2026-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_orders', '0006_vegetableorderitem_pack_value_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableDeliverySlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Morning Delivery, Evening Delivery', max_length=100)),
                ('slot_label', models.CharField(help_text='e.g. 6:00 AM – 8:00 AM, 6:00 PM – 8:00 PM', max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('cutoff_time', models.TimeField(blank=True, help_text='Cutoff time for same-day booking (e.g. 12:00:00)', null=True)),
                ('is_same_day_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vegetable_orders_delivery_slot_config',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='vegetableorder',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vegetableorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vegetableorder',
            name='delivery_slot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vegetableorder',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vegetableorder',
            name='items_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vegetableorder',
            name='small_cart_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vegetableorder',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
