# Generated by Django 6.0.8 on 2026-09-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_orders', '0007_vegetabledeliveryslotconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetabledeliveryslotconfig',
            name='code',
            field=models.CharField(blank=True, default='', help_text='e.g. morning, evening, afternoon', max_length=50),
        ),
        migrations.AlterField(
            model_name='vegetabledeliveryslotconfig',
            name='cutoff_time',
            field=models.TimeField(blank=True, help_text='Default cutoff time for same-day booking (e.g. 12:00:00)', null=True),
        ),
        migrations.AlterField(
            model_name='vegetabledeliveryslotconfig',
            name='slot_label',
            field=models.CharField(help_text='e.g. 6:30 AM – 9:30 AM, 6:00 PM – 8:00 PM', max_length=100),
        ),
        migrations.CreateModel(
            name='VegetableSlotDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('is_closed', models.BooleanField(default=True, help_text='True to close/disable, False to force-open')),
                ('cutoff_time_override', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', help_text='e.g. Festival Holiday, Maintenance', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_config', models.ForeignKey(blank=True, help_text='If blank, applies to all slots on this date (full day closure)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='vegetable_orders.vegetabledeliveryslotconfig')),
            ],
            options={
                'db_table': 'vegetable_orders_slot_date_override',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VegetableWeekdaySlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], db_index=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('cutoff_time_override', models.TimeField(blank=True, help_text='Optional cutoff time override for this weekday', null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Optional max orders capacity for this slot on this weekday', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_configs', to='vegetable_orders.vegetabledeliveryslotconfig')),
            ],
            options={
                'db_table': 'vegetable_orders_weekday_slot_config',
                'ordering': ['weekday', 'slot_config__sort_order', 'id'],
                'unique_together': {('weekday', 'slot_config')},
            },
        ),
    ]
