# Generated by Django 6.0.8 on 2026-09-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable_orders', '0008_vegetabledeliveryslotconfig_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryCartPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=200, help_text='Cart subtotal at or above which delivery is free (e.g. ₹200.00)', max_digits=10)),
                ('small_cart_fee_threshold', models.DecimalField(decimal_places=2, default=100, help_text='Cart subtotal below which small cart fee applies and low tier delivery fee applies (e.g. ₹100.00)', max_digits=10)),
                ('small_cart_fee_amount', models.DecimalField(decimal_places=2, default=5, help_text='Small cart fee charged for orders under small_cart_fee_threshold (e.g. ₹5.00)', max_digits=10)),
                ('low_tier_delivery_fee', models.DecimalField(decimal_places=2, default=15, help_text='Delivery fee for orders below small_cart_fee_threshold (e.g. ₹15.00)', max_digits=10)),
                ('mid_tier_delivery_fee', models.DecimalField(decimal_places=2, default=10, help_text='Delivery fee for orders between small_cart_fee_threshold and free_delivery_threshold (e.g. ₹10.00)', max_digits=10)),
                ('handling_fee_amount', models.DecimalField(decimal_places=2, default=2, help_text='Fixed handling / convenience fee per order (e.g. ₹2.00)', max_digits=10)),
                ('tip_preset_amounts', models.JSONField(blank=True, default=list, help_text='List of tip preset options in INR, e.g. [20, 30, 50]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vegetable_orders_cart_pricing_config',
                'ordering': ['-is_active', '-id'],
            },
        ),
    ]
