# Generated by Django 5.2.17 on 2026-08-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('truck', 'Truck / Mini Truck'), ('two_wheeler', 'Two Wheeler'), ('packers_movers', 'Packers & Movers')], db_index=True, max_length=20)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('destination_label', models.CharField(max_length=150)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eta_label', models.CharField(blank=True, default='', max_length=50)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lane (Popular Route)',
                'ordering': ['category', 'city', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ['city', 'order', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('truck', 'Truck / Mini Truck'), ('two_wheeler', 'Two Wheeler'), ('packers_movers', 'Packers & Movers')], db_index=True, max_length=20)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=150)),
                ('capacity_label', models.CharField(blank=True, default='', max_length=100)),
                ('dimensions_label', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Tier',
                'ordering': ['category', 'city', 'order', 'name'],
                'unique_together': {('category', 'city', 'slug')},
            },
        ),
    ]
