# Generated by Django 5.2.17 on 2026-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetier',
            name='weight_class',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('heavy', 'Heavy')], default='', max_length=10),
        ),
    ]
