# Generated by Django 6.0.8 on 2026-08-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_servicetier_weight_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetier',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
