# Generated by Django 6.0.8 on 2026-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_servicetier_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetier',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
