# Hand-verified auto-generated migration (2026-09-04). Generated by a real
# `manage.py makemigrations` run against a real local Django install (see
# service_requests migration 0064's header for that setup).
#
# GT-B-01: adds the distance-based pricing inputs to ServiceTier, per
# CALTRACK_PHASE_14 PART H.1. Purely additive and entirely
# nullable/zero-default, so applying it changes NO existing behaviour:
# with per_km_rate left unset on a tier, resolve_logistics_fare_v2()
# falls straight through to the previous flat lane/tier lookup for that
# tier. Distance pricing switches on per-tier, by an admin setting
# per_km_rate (and optionally base_fare / free_km / surge / minimum).
#
# Safe to apply to any existing database: no data migration, no
# backfill needed, no column made non-nullable.

# Generated by Django 5.2.17 on 2026-09-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_servicetier_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetier',
            name='additional_stop_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Charged per stop beyond the standard two (one pickup, one drop).', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='base_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed component of the fare. Falls back to starting_price when unset.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='free_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance included in base_fare before per_km_rate starts applying.', max_digits=6),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='loading_unloading_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='minimum_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Floor applied after everything else. Unset means no floor.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='per_km_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-km charge beyond free_km. Leave unset to keep this tier on flat pricing.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='surge_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Applied to the whole computed fare. A configurable per-tier value, not a live demand engine -- time-band/demand surge is its own system.', max_digits=4),
        ),
    ]
