# Generated by Django 6.0.8 on 2026-09-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_servicetier_image'),
        ('logistics', '0009_packersmoversconfig'),
    ]

    operations = [
    ]
