# Generated by Django 6.0.8 on 2026-09-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_servicetier_crew_size_and_alter_vehicle_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='default_cft',
            field=models.DecimalField(decimal_places=2, help_text='Explicit item volume in CFT. Must be explicitly configured; zero indicates unconfigured.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='default_weight_kg',
            field=models.DecimalField(decimal_places=2, help_text='Explicit item weight in kg. Must be explicitly configured; zero indicates unconfigured.', max_digits=7),
        ),
    ]
