# Generated by Django 6.0.8 on 2026-09-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_merge_0007_servicetier_image_0009_packersmoversconfig'),
        ('logistics', '0013_configure_pm_capacities_and_empty_categories'),
    ]

    operations = [
    ]
