# Generated by Django 5.0.14 on 2026-09-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0014_merge_20260916_1548"),
    ]

    operations = [
        migrations.CreateModel(
            name="GTFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("truck", "Truck / Mini Truck"),
                            ("two_wheeler", "Two Wheeler"),
                            ("packers_movers", "Packers & Movers"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Leave blank to show on all GT category pages.",
                        max_length=20,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Leave blank to show in all cities.",
                        max_length=100,
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GT FAQ",
                "verbose_name_plural": "GT FAQs",
                "ordering": ["category", "city", "order"],
            },
        ),
        migrations.AddField(
            model_name="lane",
            name="destination_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="City-centre latitude for P&M intercity drop coordinate resolution. Leave blank to fall back to geocoding.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lane",
            name="destination_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="City-centre longitude for P&M intercity drop coordinate resolution. Leave blank to fall back to geocoding.",
                max_digits=9,
                null=True,
            ),
        ),
    ]
