# Generated by Django 5.0.14 on 2026-09-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0015_gt_faq_and_lane_coords"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Service category (e.g. 'truck', 'two_wheeler', 'packers_movers'), or blank for all.",
                        max_length=30,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Operating city (e.g. 'hosur'), or blank for all.",
                        max_length=50,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        default="Morning",
                        help_text="Slot group heading (e.g. 'Morning', 'Afternoon', 'Evening')",
                        max_length=50,
                    ),
                ),
                (
                    "slot_label",
                    models.CharField(
                        help_text="Standard slot time representation (e.g. '07:00 AM - 08:00 AM')",
                        max_length=50,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Max concurrent bookings supported in this window",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Logistics Slot",
                "verbose_name_plural": "Logistics Slots",
                "ordering": ["category", "city", "order", "start_time"],
            },
        ),
    ]
