# Generated by Django 5.0.14 on 2026-09-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0016_logisticsslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodscategory",
            name="info_banner",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom info or tips banner displayed in customer inventory modal (e.g. 'What we pack in Bedrooms')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="goodsitem",
            name="subcategory",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional subcategory for UI grouping (e.g. 'Bed', 'Chair', 'Table', 'Cartons & Packaging', 'Appliances')",
                max_length=100,
            ),
        ),
    ]
