# Generated by Django 5.2.17 on 2026-09-28 09:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_prohibitedgoodsrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackersMoversSurchargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('WEEKDAY', 'Days of the week'), ('DAY_OF_MONTH', 'Days of the month (peak period)'), ('DATE', 'Specific date (holiday / auspicious day)'), ('OUTSIDE_HOURS', 'Outside normal service hours')], max_length=20)),
                ('city', models.CharField(blank=True, default='', help_text='Blank = every city.', max_length=50)),
                ('weekdays', models.CharField(blank=True, default='', help_text='Comma-separated, Monday=0 ... Sunday=6.', max_length=20)),
                ('day_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('on_date', models.DateField(blank=True, null=True)),
                ('window_start', models.TimeField(blank=True, null=True)),
                ('window_end', models.TimeField(blank=True, null=True)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
