# Generated by Django 5.2.17 on 2026-09-29 05:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_packersmoverssurchargerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMAddOnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable identifier used by the booking payload, e.g. 'rope_pulling'.", max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, default='', help_text='Blank = available in every city.', max_length=50)),
                ('pricing_mode', models.CharField(choices=[('FLAT', 'Flat fee'), ('PER_UNIT', 'Per unit'), ('PER_CFT', 'Per CFT')], default='FLAT', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_quantity', models.PositiveSmallIntegerField(default=1, help_text='Largest quantity a customer may select (ignored for FLAT).')),
                ('is_labour_only', models.BooleanField(default=False, help_text="This add-on represents a helper/labour-only line (Porter's helper-with-vehicle booking) rather than a physical task.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'P&M Add-on Service',
                'verbose_name_plural': 'P&M Add-on Services',
                'ordering': ['name'],
            },
        ),
    ]
