# Generated by Django 5.2.17 on 2026-09-29 08:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_pm_addon_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='ptl_rate_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Part Truck Load rate per kg on this route. Blank = use the platform PTL rate.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='ptl_eligible',
            field=models.BooleanField(db_default=False, default=False, help_text='Allow this vehicle tier for Part Truck Load (per-kg, slot-booked) bookings. 4-wheeler and larger only.'),
        ),
    ]
