# Generated by Django 5.2.17 on 2026-09-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0026_prohibited_goods_porter_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetier',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Tier is not bookable before this date. Blank = no start restriction.', null=True),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Tier is not bookable after this date (inclusive). Blank = no end restriction.', null=True),
        ),
    ]
