# Generated by Django 6.0.5 on 2026-06-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_seed_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="data_region",
            field=models.CharField(default="us-east", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="company",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
