# Generated by Django 6.0.5 on 2026-06-24 09:09

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0005_company_address_company_data_region_company_industry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="module_permissions",
            field=models.JSONField(
                blank=True, default=companies.models.default_module_permissions
            ),
        ),
    ]
