# Generated by Django 6.0.5 on 2026-07-21 05:02

from django.db import migrations, models


IN_REGION = dict(
    code="IN",
    name="India",
    currency="INR",
    currency_symbol="₹",
    date_format="DD/MM/YYYY",
    week_start=0,           # Monday
    overtime_weekly_hours=48,
    max_weekly_hours=48,
    statutory_leave_days=15,
    tax_year_start_month=4,
    tax_year_start_day=1,
    payroll_frequency="monthly",
    min_wage="150.00",
    national_insurance_enabled=False,
    paye_enabled=False,
    flsa_enabled=False,
    state_tax_enabled=True,
)


def seed_india_region(apps, schema_editor):
    Region = apps.get_model("companies", "Region")
    Region.objects.update_or_create(code="IN", defaults=IN_REGION)


def rollback_india_region(apps, schema_editor):
    Region = apps.get_model("companies", "Region")
    Region.objects.filter(code="IN").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_module_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='primary_country',
            field=models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('IN', 'India')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('IN', 'India')], max_length=2, unique=True),
        ),
        migrations.RunPython(seed_india_region, reverse_code=rollback_india_region),
    ]
