# Generated by Django 6.0.5 on 2026-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_primary_country_alter_region_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reschedule_rejection_strategy',
            field=models.CharField(choices=[('auto_reassign', 'Auto Reassign Technician'), ('suggest_alternate_slots', 'Suggest Alternate Slots')], default='auto_reassign', max_length=30),
        ),
    ]
