# Generated by Django 6.0.8 on 2026-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_reschedule_rejection_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='schema_name',
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
