# Generated by Django on 2026-08-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_company_schema_name_company_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='geofence_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='geofence_radius_meters',
        ),
        migrations.RemoveField(
            model_name='company',
            name='geofence_strict_mode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='geofence_admin_override',
        ),
        migrations.RemoveField(
            model_name='company',
            name='shift_enforcement_mode',
        ),
    ]
