# Generated by Django 6.0.8 on 2026-08-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_remove_workforce_from_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='data_region',
            field=models.CharField(default='ap-south-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_country',
            field=models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('IN', 'India')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='max_weekly_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='region',
            name='payroll_frequency',
            field=models.CharField(default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='tax_year_start_month',
            field=models.IntegerField(default=4),
        ),
    ]
