export const routes = {
  landing: "/home",
  login: "/login",
  organization_signup: "/organization-signup",
  dashboard: "/dashboard",
  reports: "/reports",
  settings: "/settings",
  get_started: "/get-started",
  settings_profile: "/settings/profile",
  settings_preferences: "/settings/preferences",
  settings_team: "/settings/team",
  settings_reports: "/settings/reports",
  settings_notifications: "/settings/notifications",
  settings_security: "/settings/security",
  settings_rbac: "/settings/rbac",
  settings_audit: "/settings/audit",
  settings_devices: "/settings/devices",
  settings_branding: "/settings/branding",
  settings_organization: "/settings/organization",
  settings_integrations: "/settings/integrations",
  settings_developer: "/settings/developer",
  settings_billing: "/settings/billing",
  settings_data: "/settings/data",
  onboarding: "/onboarding",
  accept_invite: "/accept-invite",
  settings_invoices: "/settings/invoices",
  reset_password: "/reset-password",
  inventory: "/inventory",
  inventory_vegetables: "/inventory/vegetables",
  booking: "/booking",
  booking_services: "/booking/services",
  booking_checkout: "/booking/checkout",
  feedback: "/feedback/:token",
  admin_service_requests: "/admin/service-requests",
  admin_feedback: "/admin/feedback",
  customer_work_extension: "/customer/work-extensions/:token",
  // Public quotation decision — the token in the path is the credential, so
  // the link works on a device that has never signed in.
  customer_quotation: "/customer/quote/:token",
  booking_quotation: "/booking/quote/:token",
  truck_booking_hosur: "/trucks/hosur",
  two_wheeler_booking_hosur: "/two-wheelers/hosur",
  two_wheeler_booking: "/two-wheelers",
  packers_movers_booking_hosur: "/packers-and-movers/hosur",
  packers_movers_booking: "/packers-and-movers",
  vegetables: "/vegetables",
  catalog_dashboard: "/catalog",
  catalog_categories: "/catalog/categories",
  catalog_services: "/catalog/services",
  catalog_packages: "/catalog/packages",
  catalog_addons: "/catalog/addons",
  catalog_recipes: "/catalog/recipes",
  catalog_recommendations: "/catalog/recommendations",
  catalog_change_log: "/catalog/change-log",
  catalog_painting_rates: "/catalog/painting-rates",
  catalog_gt_pricing: "/catalog/goods-transport-rates",
  marketing_coupons: "/marketing/coupons",
  marketing_offers: "/marketing/offers",
  marketing_referrals: "/marketing/referrals",
  homepage_customizer: "/admin/homepage-customizer",
  // Public customer live tracking page — accessible at /track/:bookingId?token=<uuid>
  // The tracking_token query param is the authorization credential (not in the path).
  live_tracking: "/track/:bookingId",
  customers_dashboard: "/customers/dashboard",
  customers_list: "/customers/list",
  customers_detail: "/customers/:id",
  customers_payments: "/customers/payments",
  customers_merges: "/customers/merges",
  // Public Legal & Policies
  terms: "/terms",
  terms_and_conditions: "/terms-and-conditions",
  privacy: "/privacy",
  privacy_policy: "/privacy-policy",
  service_delivery: "/service-delivery",
  service_delivery_policy: "/service-delivery-policy",
  cancellation_refund: "/cancellation-refund",
  cancellation_refund_policy: "/cancellation-and-refund-policy",
  contact: "/contact",
  contact_us: "/contact-us",
  help: "/help",
  help_and_support: "/help-and-support",
  // HS-A-03: logged-in customer account area -- real, bookmarkable/shareable
  // routes for a customer's own bookings/addresses/wallet/etc, instead of only
  // being reachable through the account button opening a modal on /home.
  account: "/account",
  account_bookings: "/account/bookings",
  account_addresses: "/account/addresses",
  account_wallet: "/account/wallet",
  account_referral: "/account/referral",
  account_amc: "/account/amc",
  account_insurance: "/account/insurance-claims",
  account_notifications: "/account/notifications",
  account_help: "/account/help",
  // GT-B-06: generic logistics booking entry point, parameterized by
  // category + city (replaces the idea of a new hardcoded page per city).
  logistics_booking: "/logistics/:category/:city",
}

