# Generated by Django 5.2.17 on 2026-09-28 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _blank_duplicate_idempotency_keys(apps, schema_editor):
    """Migration 0087 dropped unique_customer_idempotency_key (and it was never re-added although the
    model still declares it), so duplicate (customer, idempotency_key) pairs may exist by now. Keep the
    earliest booking's key and blank the rest, otherwise re-adding the constraint would fail on a live
    database. The key is only a de-duplication token; blanking a later duplicate loses nothing."""
    ServiceRequest = apps.get_model("service_requests", "ServiceRequest")
    from django.db.models import Count
    dupes = (
        ServiceRequest.objects.exclude(idempotency_key__isnull=True).exclude(idempotency_key="")
        .values("customer_id", "idempotency_key").annotate(n=Count("id")).filter(n__gt=1)
    )
    for group in dupes:
        rows = list(
            ServiceRequest.objects.filter(
                customer_id=group["customer_id"], idempotency_key=group["idempotency_key"],
            ).order_by("id").values_list("id", flat=True)
        )
        ServiceRequest.objects.filter(id__in=rows[1:]).update(idempotency_key="")


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_company_data_region_and_more'),
        ('logistics', '0019_servicetier_gst_rate'),
        ('service_requests', '0099_package_gt_gst_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_blank_duplicate_idempotency_keys, migrations.RunPython.noop),
        migrations.RenameIndex(
            model_name='vendorcapabilityrequest',
            new_name='vcr_vendor_status_idx',
            old_name='service_req_vendor__91bc67_idx',
        ),
        migrations.AlterField(
            model_name='addon',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='service_requests.package'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['job_type', 'status'], name='service_req_job_typ_6bd73d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['job_type', 'created_at'], name='service_req_job_typ_4f9cb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('customer', 'idempotency_key'), name='unique_customer_idempotency_key'),
        ),
    ]
