# Generated by Django 6.0.8 on 2026-08-05 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_company_schema_name_company_slug_and_more'),
        ('employees', '0011_alter_employee_payroll_group'),
        ('live_locations', '0003_rename_live_loc_breach_emp_ts_idx_live_locati_employe_ac8113_idx_and_more'),
        ('time_tracking', '0007_add_unique_open_timelog_per_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelocation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geofencebreach',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_breaches', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosalert',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='employeelocation',
            index=models.Index(fields=['company', 'timestamp'], name='live_locati_company_32cd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='geofencebreach',
            index=models.Index(fields=['company', 'timestamp'], name='live_locati_company_b79c63_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['company', 'triggered_at'], name='live_locati_company_986f7a_idx'),
        ),
    ]
