# Generated by Django 6.0.5 on 2026-06-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_seed_regions"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("converted", "Converted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("trial_start", models.DateTimeField()),
                ("trial_end", models.DateTimeField()),
                ("reminder_10d_sent", models.BooleanField(default=False)),
                ("reminder_5d_sent", models.BooleanField(default=False)),
                ("reminder_3d_sent", models.BooleanField(default=False)),
                ("reminder_1d_sent", models.BooleanField(default=False)),
                ("expired_email_sent", models.BooleanField(default=False)),
                ("upgraded_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_plan", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_plan",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrialNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("banner", "Trial Banner"),
                            ("bell", "Notification Bell"),
                            ("countdown", "Countdown Alert"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trial_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="trial_management.trialplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrialEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "milestone",
                    models.CharField(
                        choices=[
                            ("activated", "Trial Activated"),
                            ("10d", "10 Days Remaining"),
                            ("5d", "5 Days Remaining"),
                            ("3d", "3 Days Remaining"),
                            ("1d", "1 Day Remaining"),
                            ("expired", "Trial Expired"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "trial_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="trial_management.trialplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="TrialAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(db_index=True)),
                ("actor_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("trial_started", "Trial Started"),
                            ("reminder_sent", "Reminder Sent"),
                            ("trial_expired", "Trial Expired"),
                            ("upgrade_clicked", "Upgrade Clicked"),
                            ("subscription_purchased", "Subscription Purchased"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trial_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="trial_management.trialplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trialplan",
            index=models.Index(fields=["status"], name="trial_manag_status_5a5141_idx"),
        ),
        migrations.AddIndex(
            model_name="trialplan",
            index=models.Index(
                fields=["trial_end"], name="trial_manag_trial_e_baa8ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trialplan",
            index=models.Index(
                fields=["company", "status"], name="trial_manag_company_0b3931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trialnotification",
            index=models.Index(
                fields=["company_id", "is_read"], name="trial_manag_company_7c7f48_idx"
            ),
        ),
    ]
