# Generated by Django 6.0.5 on 2026-06-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trial_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialplan",
            name="trial_type",
            field=models.CharField(default="14-day", max_length=50),
        ),
        migrations.AlterField(
            model_name="trialplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("converted", "Converted"),
                    ("converted_to_paid", "Converted To Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trialplan",
            name="trial_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trialplan",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
